// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unused_field, unnecessary_non_null_assertion
library custom_shadow_demo;

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'dart:typed_data';

typedef MaybeBlobMap = Map<String, Uint8List?>;

final class _RustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external ffi.Pointer<Utf8> errorBuf;
}

const int _rustCallStatusSuccess = 0;
const int _rustCallStatusError = 1;
const int _rustCallStatusUnexpectedError = 2;
const int _rustCallStatusCancelled = 3;
const int _rustFuturePollReady = 0;
const int _rustFuturePollWake = 1;

class CustomShadowDemoFfi {
  CustomShadowDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_custom_shadow_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final int Function(ffi.Pointer<Utf8> input) _asyncEchoMap = _lib.lookupFunction<ffi.Uint64 Function(ffi.Pointer<Utf8> input), int Function(ffi.Pointer<Utf8> input)>('async_echo_map');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _asyncEchoMapRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('rust_future_poll_string');
  late final void Function(int handle) _asyncEchoMapRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_cancel_string');
  late final ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<_RustCallStatus> outStatus) _asyncEchoMapRustFutureComplete = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Pointer<_RustCallStatus> outStatus), ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<_RustCallStatus> outStatus)>('rust_future_complete_string');
  late final void Function(int handle) _asyncEchoMapRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_free_string');

  Future<Map<String, Uint8List?>> asyncEchoMap(Map<String, Uint8List?> input) async {
    final String inputNativeJson = jsonEncode(input.map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value!; return base64Encode(__tmp); })())));
    final ffi.Pointer<Utf8> inputNative = inputNativeJson.toNativeUtf8();
    final int futureHandle;
    try {
      futureHandle = _asyncEchoMap(inputNative);
    } finally {
    calloc.free(inputNative);
    }
    final StreamController<int> pollEvents = StreamController<int>.broadcast();
    final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
      pollEvents.add(pollResult);
    });
    try {
      _asyncEchoMapRustFuturePoll(futureHandle, callback.nativeFunction, 0);
      while (true) {
        final int pollResult = await pollEvents.stream.first;
        if (pollResult == _rustFuturePollReady) {
          break;
        }
        if (pollResult == _rustFuturePollWake) {
          _asyncEchoMapRustFuturePoll(futureHandle, callback.nativeFunction, 0);
          continue;
        }
        throw StateError('Rust future poll returned invalid status for async_echo_map: $pollResult');
      }
      final ffi.Pointer<_RustCallStatus> outStatusPtr = calloc<_RustCallStatus>();
      try {
        final ffi.Pointer<Utf8> resultPtr = _asyncEchoMapRustFutureComplete(futureHandle, outStatusPtr);
        final int statusCode = outStatusPtr.ref.code;
        if (statusCode == _rustCallStatusSuccess) {
          if (resultPtr == ffi.nullptr) {
            throw StateError('Rust returned null for async_echo_map');
          }
          try {
            final String payload = resultPtr.toDartString();
            return (jsonDecode(payload) as Map<String, dynamic>).map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value; return base64Decode(__tmp as String); })()));
          } finally {
            _rustStringFree(resultPtr);
          }
        }
        if (statusCode == _rustCallStatusCancelled) {
          throw StateError('Rust future was cancelled for async_echo_map');
        }
        final ffi.Pointer<Utf8> errorPtr = outStatusPtr.ref.errorBuf;
        if (errorPtr != ffi.nullptr) {
          try {
            throw StateError(errorPtr.toDartString());
          } finally {
            _rustStringFree(errorPtr);
          }
        }
        throw StateError('Rust future failed for async_echo_map with status code: $statusCode');
      } finally {
        calloc.free(outStatusPtr);
      }
    } catch (_) {
      _asyncEchoMapRustFutureCancel(futureHandle);
      rethrow;
    } finally {
      await pollEvents.close();
      callback.close();
      _asyncEchoMapRustFutureFree(futureHandle);
    }
  }

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input) _echoMap = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input)>('echo_map');

  Map<String, Uint8List?> echoMap(Map<String, Uint8List?> input) {
    final String inputNativeJson = jsonEncode(input.map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value!; return base64Encode(__tmp); })())));
    final ffi.Pointer<Utf8> inputNative = inputNativeJson.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _echoMap(inputNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for echo_map');
      }
      try {
        final String payload = resultPtr.toDartString();
        return (jsonDecode(payload) as Map<String, dynamic>).map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value; return base64Decode(__tmp as String); })()));
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    calloc.free(inputNative);
    }
  }

  late final void Function(int handle) _holderFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('holder_free');

  late final int Function() _holderCtorNew = _lib.lookupFunction<ffi.Uint64 Function(), int Function()>('holder_new');

  Holder holderCreateNew() {
    final int handle = _holderCtorNew();
    return Holder._(this, handle);
  }

  late final int Function(int handle, ffi.Pointer<Utf8> input) _holderAsyncEchoMap = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle, ffi.Pointer<Utf8> input), int Function(int handle, ffi.Pointer<Utf8> input)>('holder_async_echo_map');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _holderAsyncEchoMapRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('rust_future_poll_string');
  late final void Function(int handle) _holderAsyncEchoMapRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_cancel_string');
  late final ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<_RustCallStatus> outStatus) _holderAsyncEchoMapRustFutureComplete = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Pointer<_RustCallStatus> outStatus), ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<_RustCallStatus> outStatus)>('rust_future_complete_string');
  late final void Function(int handle) _holderAsyncEchoMapRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_free_string');

  Future<Map<String, Uint8List?>> holderInvokeAsyncEchoMap(int handle, Map<String, Uint8List?> input) async {
    final String inputNativeJson = jsonEncode(input.map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value!; return base64Encode(__tmp); })())));
    final ffi.Pointer<Utf8> inputNative = inputNativeJson.toNativeUtf8();
    final int futureHandle;
    try {
      futureHandle = _holderAsyncEchoMap(handle, inputNative);
    } finally {
    calloc.free(inputNative);
    }
    final StreamController<int> pollEvents = StreamController<int>.broadcast();
    final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
      pollEvents.add(pollResult);
    });
    try {
      _holderAsyncEchoMapRustFuturePoll(futureHandle, callback.nativeFunction, 0);
      while (true) {
        final int pollResult = await pollEvents.stream.first;
        if (pollResult == _rustFuturePollReady) {
          break;
        }
        if (pollResult == _rustFuturePollWake) {
          _holderAsyncEchoMapRustFuturePoll(futureHandle, callback.nativeFunction, 0);
          continue;
        }
        throw StateError('Rust future poll returned invalid status for holder_async_echo_map: $pollResult');
      }
      final ffi.Pointer<_RustCallStatus> outStatusPtr = calloc<_RustCallStatus>();
      try {
        final ffi.Pointer<Utf8> resultPtr = _holderAsyncEchoMapRustFutureComplete(futureHandle, outStatusPtr);
        final int statusCode = outStatusPtr.ref.code;
        if (statusCode == _rustCallStatusSuccess) {
          if (resultPtr == ffi.nullptr) {
            throw StateError('Rust returned null for holder_async_echo_map');
          }
          try {
            final String payload = resultPtr.toDartString();
            return (jsonDecode(payload) as Map<String, dynamic>).map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value; return base64Decode(__tmp as String); })()));
          } finally {
            _rustStringFree(resultPtr);
          }
        }
        if (statusCode == _rustCallStatusCancelled) {
          throw StateError('Rust future was cancelled for holder_async_echo_map');
        }
        final ffi.Pointer<Utf8> errorPtr = outStatusPtr.ref.errorBuf;
        if (errorPtr != ffi.nullptr) {
          try {
            throw StateError(errorPtr.toDartString());
          } finally {
            _rustStringFree(errorPtr);
          }
        }
        throw StateError('Rust future failed for holder_async_echo_map with status code: $statusCode');
      } finally {
        calloc.free(outStatusPtr);
      }
    } catch (_) {
      _holderAsyncEchoMapRustFutureCancel(futureHandle);
      rethrow;
    } finally {
      await pollEvents.close();
      callback.close();
      _holderAsyncEchoMapRustFutureFree(futureHandle);
    }
  }

  late final ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<Utf8> input) _holderEchoMap = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Pointer<Utf8> input), ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<Utf8> input)>('holder_echo_map');

  Map<String, Uint8List?> holderInvokeEchoMap(int handle, Map<String, Uint8List?> input) {
    final String inputNativeJson = jsonEncode(input.map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value!; return base64Encode(__tmp); })())));
    final ffi.Pointer<Utf8> inputNative = inputNativeJson.toNativeUtf8();
    try {
    final ffi.Pointer<Utf8> resultPtr = _holderEchoMap(handle, inputNative);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for holder_echo_map');
    }
    try {
      final String payload = resultPtr.toDartString();
      return (jsonDecode(payload) as Map<String, dynamic>).map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value; return base64Decode(__tmp as String); })()));
    } finally {
      _rustStringFree(resultPtr);
    }
    } finally {
    calloc.free(inputNative);
    }
  }
}

final class _HolderFinalizerToken {
  const _HolderFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class Holder {
  Holder._(this._ffi, this._handle) {
    _finalizer.attach(this, _HolderFinalizerToken(_ffi._holderFree, _handle), detach: this);
  }

  final CustomShadowDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_HolderFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._holderFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('Holder is closed');
    }
  }

  static Holder create() {
    return _bindings().holderCreateNew();
  }

  Future<Map<String, Uint8List?>> asyncEchoMap(Map<String, Uint8List?> input) {
    _ensureOpen();
    return _ffi.holderInvokeAsyncEchoMap(_handle, input);
  }

  Map<String, Uint8List?> echoMap(Map<String, Uint8List?> input) {
    _ensureOpen();
    return _ffi.holderInvokeEchoMap(_handle, input);
  }

}

final class HolderFfiCodec {
  const HolderFfiCodec._();

  static int lower(Holder value) => value._handle;

  static Holder lift(int handle) => Holder._(_bindings(), handle);
}

CustomShadowDemoFfi? _defaultBindings;

CustomShadowDemoFfi _bindings() => _defaultBindings ??= CustomShadowDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = CustomShadowDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

Future<Map<String, Uint8List?>> asyncEchoMap(Map<String, Uint8List?> input) {
  return _bindings().asyncEchoMap(input);
}

Map<String, Uint8List?> echoMap(Map<String, Uint8List?> input) {
  return _bindings().echoMap(input);
}

