// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element
library coverall_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'dart:typed_data';

final class _RustBuffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Uint64()
  external int len;
}

final class _RustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external ffi.Pointer<Utf8> errorBuf;
}

const int _rustCallStatusSuccess = 0;
const int _rustCallStatusError = 1;
const int _rustCallStatusUnexpectedError = 2;
const int _rustCallStatusCancelled = 3;
/// Primary test record with a rich set of field types.
class SimpleDict {
  const SimpleDict({
    required this.text,
    required this.maybeCount,
    required this.flag,
    required this.color,
    required this.tags,
    required this.counts,
    required this.maybeText,
    required this.maybePatch,
  });

  final String text;
  final int maybeCount;
  final bool flag;
  final Color color;
  final List<String> tags;
  final Map<String, int> counts;
  final String? maybeText;
  final Patch? maybePatch;

  Map<String, dynamic> toJson() {
    return {
      'text': this.text,
      'maybeCount': this.maybeCount,
      'flag': this.flag,
      'color': ColorFfiCodec.encode(this.color),
      'tags': this.tags.map((item) => item).toList(),
      'counts': this.counts.map((key, value) => MapEntry(key, value)),
      'maybeText': this.maybeText == null ? null : (() { final __tmp = this.maybeText; return __tmp; })(),
      'maybePatch': this.maybePatch == null ? null : (() { final __tmp = this.maybePatch; return __tmp; })(),
    };
  }

  static SimpleDict fromJson(Map<String, dynamic> json) {
    return SimpleDict(
      text: json['text'] as String,
      maybeCount: (json['maybeCount'] as num).toInt(),
      flag: json['flag'] as bool,
      color: ColorFfiCodec.decode(json['color'] as String),
      tags: (json['tags'] as List).map((item) => item as String).toList(),
      counts: (json['counts'] as Map<String, dynamic>).map((key, value) => MapEntry(key, (value as num).toInt())),
      maybeText: json['maybeText'] == null ? null : (() { final __tmp = json['maybeText']; return __tmp as String; })(),
      maybePatch: json['maybePatch'] == null ? null : (() { final __tmp = json['maybePatch']; return PatchFfiCodec.lift((__tmp as num).toInt()); })(),
    );
  }

  SimpleDict copyWith({
    String? text,
    int? maybeCount,
    bool? flag,
    Color? color,
    List<String>? tags,
    Map<String, int>? counts,
    String? maybeText,
    Patch? maybePatch,
  }) {
    return SimpleDict(
      text: text ?? this.text,
      maybeCount: maybeCount ?? this.maybeCount,
      flag: flag ?? this.flag,
      color: color ?? this.color,
      tags: tags ?? this.tags,
      counts: counts ?? this.counts,
      maybeText: maybeText ?? this.maybeText,
      maybePatch: maybePatch ?? this.maybePatch,
    );
  }
}

/// Simple three-variant flat enum.
enum Color {
  red,
  blue,
  green,
}

/// Rich error with structured variant data.
sealed class ComplexError {
  const ComplexError();
}

final class ComplexErrorOsError extends ComplexError {
  const ComplexErrorOsError({
    required this.code,
    required this.extendedCode,
  });
  final int code;
  final int extendedCode;
}

final class ComplexErrorPermissionDenied extends ComplexError {
  const ComplexErrorPermissionDenied({
    required this.reason,
  });
  final String reason;
}

final class ComplexErrorUnknownError extends ComplexError {
  const ComplexErrorUnknownError();
}

/// Simple flat error (single tag discriminator).
sealed class CoverallError {
  const CoverallError();
}

final class CoverallErrorTooManyHoles extends CoverallError {
  const CoverallErrorTooManyHoles();
}

/// Enum wrapping a record — tests enum-with-associated-data.
sealed class MaybeSimpleDict {
  const MaybeSimpleDict();
}

final class MaybeSimpleDictYeah extends MaybeSimpleDict {
  const MaybeSimpleDictYeah({
    required this.value,
  });
  final SimpleDict value;
}

final class MaybeSimpleDictNah extends MaybeSimpleDict {
  const MaybeSimpleDictNah();
}

/// Rich error with structured variant data.
sealed class ComplexErrorException implements Exception {
  const ComplexErrorException();
}

final class ComplexErrorExceptionOsError extends ComplexErrorException {
  const ComplexErrorExceptionOsError({
    required this.code,
    required this.extendedCode,
  });
  final int code;
  final int extendedCode;
}

final class ComplexErrorExceptionPermissionDenied extends ComplexErrorException {
  const ComplexErrorExceptionPermissionDenied({
    required this.reason,
  });
  final String reason;
}

final class ComplexErrorExceptionUnknownError extends ComplexErrorException {
  const ComplexErrorExceptionUnknownError();
}

/// Simple flat error (single tag discriminator).
sealed class CoverallErrorException implements Exception {
  const CoverallErrorException();
}

final class CoverallErrorExceptionTooManyHoles extends CoverallErrorException {
  const CoverallErrorExceptionTooManyHoles();
}

String _encodeColor(Color value) {
  return switch (value) {
    Color.red => 'red',
    Color.blue => 'blue',
    Color.green => 'green',
  };
}

Color _decodeColor(String raw) {
  switch (raw) {
    case 'red':
      return Color.red;
    case 'blue':
      return Color.blue;
    case 'green':
      return Color.green;
    default:
      throw StateError('Unknown Color variant: $raw');
  }
}

String _encodeComplexError(ComplexError value) {
  if (value is ComplexErrorOsError) {
    return jsonEncode({
      'tag': 'osError',
      'code': value.code,
      'extendedCode': value.extendedCode,
    });
  }
  if (value is ComplexErrorPermissionDenied) {
    return jsonEncode({
      'tag': 'permissionDenied',
      'reason': value.reason,
    });
  }
  if (value is ComplexErrorUnknownError) {
    return jsonEncode({
      'tag': 'unknownError',
    });
  }
  throw StateError('Unknown ComplexError variant instance: $value');
}

ComplexError _decodeComplexError(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'osError':
      return ComplexErrorOsError(
        code: (map['code'] as num).toInt(),
        extendedCode: (map['extendedCode'] as num).toInt(),
      );
    case 'permissionDenied':
      return ComplexErrorPermissionDenied(
        reason: map['reason'] as String,
      );
    case 'unknownError':
      return ComplexErrorUnknownError(
      );
    default:
      throw StateError('Unknown ComplexError variant tag: $tag');
  }
}

String _encodeCoverallError(CoverallError value) {
  if (value is CoverallErrorTooManyHoles) {
    return jsonEncode({
      'tag': 'tooManyHoles',
    });
  }
  throw StateError('Unknown CoverallError variant instance: $value');
}

CoverallError _decodeCoverallError(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'tooManyHoles':
      return CoverallErrorTooManyHoles(
      );
    default:
      throw StateError('Unknown CoverallError variant tag: $tag');
  }
}

String _encodeMaybeSimpleDict(MaybeSimpleDict value) {
  if (value is MaybeSimpleDictYeah) {
    return jsonEncode({
      'tag': 'yeah',
      'value': value.value.toJson(),
    });
  }
  if (value is MaybeSimpleDictNah) {
    return jsonEncode({
      'tag': 'nah',
    });
  }
  throw StateError('Unknown MaybeSimpleDict variant instance: $value');
}

MaybeSimpleDict _decodeMaybeSimpleDict(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'yeah':
      return MaybeSimpleDictYeah(
        value: SimpleDict.fromJson(map['value'] as Map<String, dynamic>),
      );
    case 'nah':
      return MaybeSimpleDictNah(
      );
    default:
      throw StateError('Unknown MaybeSimpleDict variant tag: $tag');
  }
}

String _encodeComplexErrorException(ComplexErrorException value) {
  if (value is ComplexErrorExceptionOsError) {
    return jsonEncode({
      'tag': 'osError',
      'code': value.code,
      'extendedCode': value.extendedCode,
    });
  }
  if (value is ComplexErrorExceptionPermissionDenied) {
    return jsonEncode({
      'tag': 'permissionDenied',
      'reason': value.reason,
    });
  }
  if (value is ComplexErrorExceptionUnknownError) {
    return jsonEncode({
      'tag': 'unknownError',
    });
  }
  throw StateError('Unknown ComplexErrorException exception instance: $value');
}

ComplexErrorException _decodeComplexErrorException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'osError':
      return ComplexErrorExceptionOsError(
        code: (map['code'] as num).toInt(),
        extendedCode: (map['extendedCode'] as num).toInt(),
      );
    case 'permissionDenied':
      return ComplexErrorExceptionPermissionDenied(
        reason: map['reason'] as String,
      );
    case 'unknownError':
      return const ComplexErrorExceptionUnknownError();
    default:
      throw StateError('Unknown ComplexErrorException exception tag: $tag');
  }
}

String _encodeCoverallErrorException(CoverallErrorException value) {
  if (value is CoverallErrorExceptionTooManyHoles) {
    return jsonEncode({
      'tag': 'tooManyHoles',
    });
  }
  throw StateError('Unknown CoverallErrorException exception instance: $value');
}

CoverallErrorException _decodeCoverallErrorException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'tooManyHoles':
      return const CoverallErrorExceptionTooManyHoles();
    default:
      throw StateError('Unknown CoverallErrorException exception tag: $tag');
  }
}

final class ColorFfiCodec {
  const ColorFfiCodec._();

  static String encode(Color value) => _encodeColor(value);

  static Color decode(String raw) => _decodeColor(raw);
}

final class ComplexErrorFfiCodec {
  const ComplexErrorFfiCodec._();

  static String encode(ComplexError value) => _encodeComplexError(value);

  static ComplexError decode(String raw) => _decodeComplexError(raw);
}

final class CoverallErrorFfiCodec {
  const CoverallErrorFfiCodec._();

  static String encode(CoverallError value) => _encodeCoverallError(value);

  static CoverallError decode(String raw) => _decodeCoverallError(raw);
}

final class MaybeSimpleDictFfiCodec {
  const MaybeSimpleDictFfiCodec._();

  static String encode(MaybeSimpleDict value) => _encodeMaybeSimpleDict(value);

  static MaybeSimpleDict decode(String raw) => _decodeMaybeSimpleDict(raw);
}

final class ComplexErrorExceptionFfiCodec {
  const ComplexErrorExceptionFfiCodec._();

  static String encode(ComplexErrorException value) => _encodeComplexErrorException(value);

  static ComplexErrorException decode(Object? raw) => _decodeComplexErrorException(raw);
}

final class CoverallErrorExceptionFfiCodec {
  const CoverallErrorExceptionFfiCodec._();

  static String encode(CoverallErrorException value) => _encodeCoverallErrorException(value);

  static CoverallErrorException decode(Object? raw) => _decodeCoverallErrorException(raw);
}

/// Callback interface exercising multiple return types and error paths.
abstract interface class Getters {
  bool getBool(bool v, bool arg2);
  String getString(String v, bool arg2);
  String? getOption(String v, bool arg2);
  List<int> getList(List<int> v, bool arg2);
  void getNothing(String v);
}

/// Callback interface for tree-like trait object graphs.
abstract interface class NodeTrait {
  String name();
  void setParent(NodeTrait? parent);
  NodeTrait? getParent();
}

final class _GettersVTable extends ffi.Struct {
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle)>> uniffiFree;

  external ffi.Pointer<ffi.NativeFunction<ffi.Uint64 Function(ffi.Uint64 handle)>> uniffiClone;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Bool v, ffi.Bool arg2, ffi.Pointer<ffi.Bool> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>> getBool;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>> getString;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>> getOption;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>> getList;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>> getNothing;

}

final class _GettersCallbackBridge {
  _GettersCallbackBridge._();
  static final _GettersCallbackBridge instance = _GettersCallbackBridge._();

  final Map<int, Getters> _callbacks = <int, Getters>{};
  final Map<int, int> _refCounts = <int, int>{};
  int _nextHandle = 1;

  int register(Getters callback) {
    final int handle = _nextHandle++;
    _callbacks[handle] = callback;
    _refCounts[handle] = 1;
    return handle;
  }

  void release(int handle) {
    final int? refs = _refCounts[handle];
    if (refs == null) {
      return;
    }
    if (refs <= 1) {
      _refCounts.remove(handle);
      _callbacks.remove(handle);
      return;
    }
    _refCounts[handle] = refs - 1;
  }

  int cloneHandle(int handle) {
    final int? refs = _refCounts[handle];
    if (refs == null) {
      throw StateError('Invalid callback handle: $handle');
    }
    _refCounts[handle] = refs + 1;
    return handle;
  }

  Getters? lookup(int handle) => _callbacks[handle];

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)> _freeNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    instance.release(handle);
  });

  static final ffi.NativeCallable<ffi.Uint64 Function(ffi.Uint64 handle)> _cloneNative = ffi.NativeCallable<ffi.Uint64 Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    return instance.cloneHandle(handle);
  }, exceptionalReturn: 0);

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Bool v, ffi.Bool arg2, ffi.Pointer<ffi.Bool> outReturn, ffi.Pointer<_RustCallStatus> outStatus)> _getBoolNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Bool v, ffi.Bool arg2, ffi.Pointer<ffi.Bool> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>.isolateLocal((int handle, bool v, bool arg2, ffi.Pointer<ffi.Bool> outReturn, ffi.Pointer<_RustCallStatus> outStatus) {
    final Getters? callback = instance.lookup(handle);
    if (callback == null) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      return;
    }
    try {
      final result = callback.getBool(v, arg2);
      outReturn.value = result ? 1 : 0;
      outStatus.ref
        ..code = _rustCallStatusSuccess
        ..errorBuf = ffi.nullptr;
    } catch (err) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = err.toString().toNativeUtf8();
    }
  });

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)> _getStringNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>.isolateLocal((int handle, ffi.Pointer<Utf8> v, bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus) {
    final Getters? callback = instance.lookup(handle);
    if (callback == null) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      return;
    }
    try {
      final result = callback.getString(v == ffi.nullptr ? (throw StateError('Rust passed null string callback arg')) : v.toDartString(), arg2);
      outReturn.value = result.toNativeUtf8();
      outStatus.ref
        ..code = _rustCallStatusSuccess
        ..errorBuf = ffi.nullptr;
    } catch (err) {
      if (err is CoverallErrorException) {
        outStatus.ref
          ..code = _rustCallStatusError
          ..errorBuf = CoverallErrorExceptionFfiCodec.encode(err).toNativeUtf8();
      } else {
        outStatus.ref
          ..code = _rustCallStatusUnexpectedError
          ..errorBuf = err.toString().toNativeUtf8();
      }
    }
  });

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)> _getOptionNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>.isolateLocal((int handle, ffi.Pointer<Utf8> v, bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus) {
    final Getters? callback = instance.lookup(handle);
    if (callback == null) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      return;
    }
    try {
      final result = callback.getOption(v == ffi.nullptr ? (throw StateError('Rust passed null string callback arg')) : v.toDartString(), arg2);
      outReturn.value = result == null ? ffi.nullptr : result.toNativeUtf8();
      outStatus.ref
        ..code = _rustCallStatusSuccess
        ..errorBuf = ffi.nullptr;
    } catch (err) {
      if (err is ComplexErrorException) {
        outStatus.ref
          ..code = _rustCallStatusError
          ..errorBuf = ComplexErrorExceptionFfiCodec.encode(err).toNativeUtf8();
      } else {
        outStatus.ref
          ..code = _rustCallStatusUnexpectedError
          ..errorBuf = err.toString().toNativeUtf8();
      }
    }
  });

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)> _getListNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>.isolateLocal((int handle, ffi.Pointer<Utf8> v, bool arg2, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus) {
    final Getters? callback = instance.lookup(handle);
    if (callback == null) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      return;
    }
    try {
      final result = callback.getList(v == ffi.nullptr ? (throw StateError('Rust passed null sequence callback arg')) : (jsonDecode(v.toDartString()) as List).map((item) => (item as num).toInt()).toList(), arg2);
      outReturn.value = jsonEncode(result.map((item) => item).toList()).toNativeUtf8();
      outStatus.ref
        ..code = _rustCallStatusSuccess
        ..errorBuf = ffi.nullptr;
    } catch (err) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = err.toString().toNativeUtf8();
    }
  });

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)> _getNothingNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> v, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>.isolateLocal((int handle, ffi.Pointer<Utf8> v, ffi.Pointer<ffi.Void> outReturn, ffi.Pointer<_RustCallStatus> outStatus) {
    final Getters? callback = instance.lookup(handle);
    if (callback == null) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      return;
    }
    try {
      callback.getNothing(v == ffi.nullptr ? (throw StateError('Rust passed null string callback arg')) : v.toDartString());
      outStatus.ref
        ..code = _rustCallStatusSuccess
        ..errorBuf = ffi.nullptr;
    } catch (err) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = err.toString().toNativeUtf8();
    }
  });

  static ffi.Pointer<_GettersVTable> createVTable() {
    final ffi.Pointer<_GettersVTable> vtablePtr = calloc<_GettersVTable>();
    vtablePtr.ref
      ..uniffiFree = _freeNative.nativeFunction
      ..uniffiClone = _cloneNative.nativeFunction
      ..getBool = _getBoolNative.nativeFunction
      ..getString = _getStringNative.nativeFunction
      ..getOption = _getOptionNative.nativeFunction
      ..getList = _getListNative.nativeFunction
      ..getNothing = _getNothingNative.nativeFunction
    ;
    return vtablePtr;
  }
}

class CoverallDemoFfi {
  CoverallDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_coverall_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  void _ensureApiIntegrity(ffi.DynamicLibrary lib) {
    const int bindingsContractVersion = 30;
    final int scaffoldingContractVersion;
    try {
      final int Function() ffiContractVersion = lib.lookupFunction<ffi.Uint32 Function(), int Function()>('ffi_crate_name_uniffi_contract_version');
      scaffoldingContractVersion = ffiContractVersion();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI contract-version symbol `ffi_crate_name_uniffi_contract_version`: $err');
    }
    if (bindingsContractVersion != scaffoldingContractVersion) {
      throw StateError('UniFFI contract version mismatch: expected $bindingsContractVersion, got $scaffoldingContractVersion');
    }
    final int _checksum_uniffi_crate_name_checksum_func_ancestor_names;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_ancestor_names');
      _checksum_uniffi_crate_name_checksum_func_ancestor_names = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_ancestor_names`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_ancestor_names != 32092) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_ancestor_names`: expected 32092, got $_checksum_uniffi_crate_name_checksum_func_ancestor_names');
    }
    final int _checksum_uniffi_crate_name_checksum_func_create_none_dict;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_create_none_dict');
      _checksum_uniffi_crate_name_checksum_func_create_none_dict = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_create_none_dict`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_create_none_dict != 59197) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_create_none_dict`: expected 59197, got $_checksum_uniffi_crate_name_checksum_func_create_none_dict');
    }
    final int _checksum_uniffi_crate_name_checksum_func_create_patch;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_create_patch');
      _checksum_uniffi_crate_name_checksum_func_create_patch = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_create_patch`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_create_patch != 45585) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_create_patch`: expected 45585, got $_checksum_uniffi_crate_name_checksum_func_create_patch');
    }
    final int _checksum_uniffi_crate_name_checksum_func_create_some_dict;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_create_some_dict');
      _checksum_uniffi_crate_name_checksum_func_create_some_dict = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_create_some_dict`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_create_some_dict != 59765) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_create_some_dict`: expected 59765, got $_checksum_uniffi_crate_name_checksum_func_create_some_dict');
    }
    final int _checksum_uniffi_crate_name_checksum_func_divide_by_text;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_divide_by_text');
      _checksum_uniffi_crate_name_checksum_func_divide_by_text = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_divide_by_text`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_divide_by_text != 35670) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_divide_by_text`: expected 35670, got $_checksum_uniffi_crate_name_checksum_func_divide_by_text');
    }
    final int _checksum_uniffi_crate_name_checksum_func_get_int_map;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_get_int_map');
      _checksum_uniffi_crate_name_checksum_func_get_int_map = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_get_int_map`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_get_int_map != 13540) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_get_int_map`: expected 13540, got $_checksum_uniffi_crate_name_checksum_func_get_int_map');
    }
    final int _checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_get_maybe_simple_dict');
      _checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_get_maybe_simple_dict`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict != 52642) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_get_maybe_simple_dict`: expected 52642, got $_checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict');
    }
    final int _checksum_uniffi_crate_name_checksum_func_get_num_alive;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_get_num_alive');
      _checksum_uniffi_crate_name_checksum_func_get_num_alive = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_get_num_alive`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_get_num_alive != 52390) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_get_num_alive`: expected 52390, got $_checksum_uniffi_crate_name_checksum_func_get_num_alive');
    }
    final int _checksum_uniffi_crate_name_checksum_func_make_rust_getters;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_make_rust_getters');
      _checksum_uniffi_crate_name_checksum_func_make_rust_getters = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_make_rust_getters`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_make_rust_getters != 31082) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_make_rust_getters`: expected 31082, got $_checksum_uniffi_crate_name_checksum_func_make_rust_getters');
    }
    final int _checksum_uniffi_crate_name_checksum_func_println;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_println');
      _checksum_uniffi_crate_name_checksum_func_println = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_println`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_println != 14318) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_println`: expected 14318, got $_checksum_uniffi_crate_name_checksum_func_println');
    }
    final int _checksum_uniffi_crate_name_checksum_func_reverse_bytes;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_reverse_bytes');
      _checksum_uniffi_crate_name_checksum_func_reverse_bytes = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_reverse_bytes`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_reverse_bytes != 20911) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_reverse_bytes`: expected 20911, got $_checksum_uniffi_crate_name_checksum_func_reverse_bytes');
    }
    final int _checksum_uniffi_crate_name_checksum_func_test_getters;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_test_getters');
      _checksum_uniffi_crate_name_checksum_func_test_getters = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_test_getters`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_test_getters != 40682) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_test_getters`: expected 40682, got $_checksum_uniffi_crate_name_checksum_func_test_getters');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_clone_me;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_clone_me');
      _checksum_uniffi_crate_name_checksum_method_coveralls_clone_me = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_clone_me`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_clone_me != 58508) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_clone_me`: expected 58508, got $_checksum_uniffi_crate_name_checksum_method_coveralls_clone_me');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_get_metadata');
      _checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_get_metadata`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata != 31141) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_get_metadata`: expected 31141, got $_checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_get_name;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_get_name');
      _checksum_uniffi_crate_name_checksum_method_coveralls_get_name = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_get_name`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_name != 25929) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_get_name`: expected 25929, got $_checksum_uniffi_crate_name_checksum_method_coveralls_get_name');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_get_other;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_get_other');
      _checksum_uniffi_crate_name_checksum_method_coveralls_get_other = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_get_other`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_other != 22943) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_get_other`: expected 22943, got $_checksum_uniffi_crate_name_checksum_method_coveralls_get_other');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_get_tags;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_get_tags');
      _checksum_uniffi_crate_name_checksum_method_coveralls_get_tags = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_get_tags`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_tags != 58217) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_get_tags`: expected 58217, got $_checksum_uniffi_crate_name_checksum_method_coveralls_get_tags');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_maybe_throw');
      _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_maybe_throw`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw != 33331) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_maybe_throw`: expected 33331, got $_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex');
      _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex != 24041) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex`: expected 24041, got $_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_reverse_bytes');
      _checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_reverse_bytes`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes != 28911) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_reverse_bytes`: expected 28911, got $_checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_set_name;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_set_name');
      _checksum_uniffi_crate_name_checksum_method_coveralls_set_name = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_set_name`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_set_name != 10857) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_set_name`: expected 10857, got $_checksum_uniffi_crate_name_checksum_method_coveralls_set_name');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_strong_count;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_strong_count');
      _checksum_uniffi_crate_name_checksum_method_coveralls_strong_count = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_strong_count`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_strong_count != 23642) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_strong_count`: expected 23642, got $_checksum_uniffi_crate_name_checksum_method_coveralls_strong_count');
    }
    final int _checksum_uniffi_crate_name_checksum_method_coveralls_take_other;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_coveralls_take_other');
      _checksum_uniffi_crate_name_checksum_method_coveralls_take_other = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_coveralls_take_other`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_coveralls_take_other != 64379) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_coveralls_take_other`: expected 64379, got $_checksum_uniffi_crate_name_checksum_method_coveralls_take_other');
    }
    final int _checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_falliblepatch_get_color');
      _checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_falliblepatch_get_color`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color != 47454) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_falliblepatch_get_color`: expected 47454, got $_checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color');
    }
    final int _checksum_uniffi_crate_name_checksum_method_patch_get_color;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_patch_get_color');
      _checksum_uniffi_crate_name_checksum_method_patch_get_color = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_patch_get_color`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_patch_get_color != 7243) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_patch_get_color`: expected 7243, got $_checksum_uniffi_crate_name_checksum_method_patch_get_color');
    }
    final int _checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_threadsafecounter_get_count');
      _checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_threadsafecounter_get_count`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count != 36276) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_threadsafecounter_get_count`: expected 36276, got $_checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count');
    }
    final int _checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_threadsafecounter_increment');
      _checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_threadsafecounter_increment`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment != 17778) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_threadsafecounter_increment`: expected 17778, got $_checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment');
    }
    final int _checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_constructor_coveralls_fallible_new');
      _checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_constructor_coveralls_fallible_new`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new != 6836) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_constructor_coveralls_fallible_new`: expected 6836, got $_checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new');
    }
    final int _checksum_uniffi_crate_name_checksum_constructor_coveralls_new;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_constructor_coveralls_new');
      _checksum_uniffi_crate_name_checksum_constructor_coveralls_new = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_constructor_coveralls_new`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_constructor_coveralls_new != 1263) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_constructor_coveralls_new`: expected 1263, got $_checksum_uniffi_crate_name_checksum_constructor_coveralls_new');
    }
    final int _checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_constructor_falliblepatch_new');
      _checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_constructor_falliblepatch_new`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new != 12136) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_constructor_falliblepatch_new`: expected 12136, got $_checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new');
    }
    final int _checksum_uniffi_crate_name_checksum_constructor_patch_new;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_constructor_patch_new');
      _checksum_uniffi_crate_name_checksum_constructor_patch_new = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_constructor_patch_new`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_constructor_patch_new != 2665) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_constructor_patch_new`: expected 2665, got $_checksum_uniffi_crate_name_checksum_constructor_patch_new');
    }
    final int _checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_constructor_threadsafecounter_new');
      _checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_constructor_threadsafecounter_new`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new != 57006) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_constructor_threadsafecounter_new`: expected 57006, got $_checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new');
    }
    final int _checksum_uniffi_crate_name_checksum_method_getters_get_bool;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_getters_get_bool');
      _checksum_uniffi_crate_name_checksum_method_getters_get_bool = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_getters_get_bool`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_getters_get_bool != 55542) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_getters_get_bool`: expected 55542, got $_checksum_uniffi_crate_name_checksum_method_getters_get_bool');
    }
    final int _checksum_uniffi_crate_name_checksum_method_getters_get_string;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_getters_get_string');
      _checksum_uniffi_crate_name_checksum_method_getters_get_string = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_getters_get_string`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_getters_get_string != 61353) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_getters_get_string`: expected 61353, got $_checksum_uniffi_crate_name_checksum_method_getters_get_string');
    }
    final int _checksum_uniffi_crate_name_checksum_method_getters_get_option;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_getters_get_option');
      _checksum_uniffi_crate_name_checksum_method_getters_get_option = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_getters_get_option`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_getters_get_option != 62176) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_getters_get_option`: expected 62176, got $_checksum_uniffi_crate_name_checksum_method_getters_get_option');
    }
    final int _checksum_uniffi_crate_name_checksum_method_getters_get_list;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_getters_get_list');
      _checksum_uniffi_crate_name_checksum_method_getters_get_list = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_getters_get_list`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_getters_get_list != 61896) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_getters_get_list`: expected 61896, got $_checksum_uniffi_crate_name_checksum_method_getters_get_list');
    }
    final int _checksum_uniffi_crate_name_checksum_method_getters_get_nothing;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_getters_get_nothing');
      _checksum_uniffi_crate_name_checksum_method_getters_get_nothing = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_getters_get_nothing`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_getters_get_nothing != 22876) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_getters_get_nothing`: expected 22876, got $_checksum_uniffi_crate_name_checksum_method_getters_get_nothing');
    }
    final int _checksum_uniffi_crate_name_checksum_method_nodetrait_name;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_nodetrait_name');
      _checksum_uniffi_crate_name_checksum_method_nodetrait_name = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_nodetrait_name`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_nodetrait_name != 46427) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_nodetrait_name`: expected 46427, got $_checksum_uniffi_crate_name_checksum_method_nodetrait_name');
    }
    final int _checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_nodetrait_set_parent');
      _checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_nodetrait_set_parent`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent != 14407) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_nodetrait_set_parent`: expected 14407, got $_checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent');
    }
    final int _checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_nodetrait_get_parent');
      _checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_nodetrait_get_parent`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent != 18470) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_nodetrait_get_parent`: expected 18470, got $_checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent');
    }
  }

  late final ffi.DynamicLibrary _lib = (() {
    final ffi.DynamicLibrary lib = open();
    _ensureApiIntegrity(lib);
    return lib;
  })();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final void Function(_RustBuffer) _rustBytesFree = _lib.lookupFunction<ffi.Void Function(_RustBuffer), void Function(_RustBuffer)>('rust_bytes_free');

  late final void Function(ffi.Pointer<_GettersVTable>) _gettersCallbackInit = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_GettersVTable>), void Function(ffi.Pointer<_GettersVTable>)>('getters_callback_init');
  late final ffi.Pointer<_GettersVTable> _gettersCallbackVTable = _GettersCallbackBridge.createVTable();
  late final bool _gettersCallbackInitDone = (() {
    _gettersCallbackInit(_gettersCallbackVTable);
    return true;
  })();
  // WARNING: Function 'ancestor_names(NodeTrait node)' was omitted because
  // the function signature is not yet supported in this FFI binding mode.


  late final ffi.Pointer<Utf8> Function() _createNoneDict = _lib.lookupFunction<ffi.Pointer<Utf8> Function(), ffi.Pointer<Utf8> Function()>('create_none_dict');

  SimpleDict createNoneDict() {
      final ffi.Pointer<Utf8> resultPtr = _createNoneDict();
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for create_none_dict');
      }
      try {
        final String payload = resultPtr.toDartString();
        return SimpleDict.fromJson(jsonDecode(payload) as Map<String, dynamic>);
      } finally {
        _rustStringFree(resultPtr);
      }
  }

  late final int Function(ffi.Pointer<Utf8> color) _createPatch = _lib.lookupFunction<ffi.Uint64 Function(ffi.Pointer<Utf8> color), int Function(ffi.Pointer<Utf8> color)>('create_patch');

  Patch createPatch(Color color) {
    final String colorNativeJson = ColorFfiCodec.encode(color);
    final ffi.Pointer<Utf8> colorNative = colorNativeJson.toNativeUtf8();
    try {
      return Patch._(this, _createPatch(colorNative));
    } finally {
    calloc.free(colorNative);
    }
  }

  late final ffi.Pointer<Utf8> Function() _createSomeDict = _lib.lookupFunction<ffi.Pointer<Utf8> Function(), ffi.Pointer<Utf8> Function()>('create_some_dict');

  SimpleDict createSomeDict() {
      final ffi.Pointer<Utf8> resultPtr = _createSomeDict();
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for create_some_dict');
      }
      try {
        final String payload = resultPtr.toDartString();
        return SimpleDict.fromJson(jsonDecode(payload) as Map<String, dynamic>);
      } finally {
        _rustStringFree(resultPtr);
      }
  }

  late final ffi.Pointer<Utf8> Function(double value, ffi.Pointer<Utf8> divisor) _divideByText = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Double value, ffi.Pointer<Utf8> divisor), ffi.Pointer<Utf8> Function(double value, ffi.Pointer<Utf8> divisor)>('divide_by_text');

  double divideByText(double value, String divisor) {
    final ffi.Pointer<Utf8> divisorNative = divisor.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _divideByText(value, divisorNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for divide_by_text');
      }
      final String payload;
      try {
        payload = resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
      final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
      final Object? errRaw = envelope['err'];
      if (errRaw != null) {
        throw ComplexErrorExceptionFfiCodec.decode(errRaw);
      }
      if (!envelope.containsKey('ok')) {
        throw StateError('Rust returned malformed result for divide_by_text');
      }
      final Object? okRaw = envelope['ok'];
      return (okRaw as num).toDouble();
    } finally {
    calloc.free(divisorNative);
    }
  }

  late final _RustBuffer Function(int key, int value) _getIntMap = _lib.lookupFunction<_RustBuffer Function(ffi.Uint32 key, ffi.Uint64 value), _RustBuffer Function(int key, int value)>('get_int_map');

  Map<int, int> getIntMap(int key, int value) {
      final _RustBuffer resultBuf = _getIntMap(key, value);
      final ffi.Pointer<ffi.Uint8> resultData = resultBuf.data;
      final int resultLen = resultBuf.len;
      if (resultData == ffi.nullptr) {
        _rustBytesFree(resultBuf);
        final mapReader = _UniFfiBinaryReader(Uint8List(0));
        return (() { final int __len = mapReader.readI32(); final out = <int, int>{}; for (var i = 0; i < __len; i++) { final key = mapReader.readU32(); final value = mapReader.readU64(); out[key] = value; } return out; })();
      }
      try {
        final Uint8List resultBytes = Uint8List.fromList(resultData.asTypedList(resultLen));
        final mapReader = _UniFfiBinaryReader(resultBytes);
        return (() { final int __len = mapReader.readI32(); final out = <int, int>{}; for (var i = 0; i < __len; i++) { final key = mapReader.readU32(); final value = mapReader.readU64(); out[key] = value; } return out; })();
      } finally {
        _rustBytesFree(resultBuf);
      }
  }

  late final ffi.Pointer<Utf8> Function(int index) _getMaybeSimpleDict = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Int8 index), ffi.Pointer<Utf8> Function(int index)>('get_maybe_simple_dict');

  MaybeSimpleDict getMaybeSimpleDict(int index) {
      final ffi.Pointer<Utf8> resultPtr = _getMaybeSimpleDict(index);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for get_maybe_simple_dict');
      }
      try {
        final String payload = resultPtr.toDartString();
        return MaybeSimpleDictFfiCodec.decode(payload);
      } finally {
        _rustStringFree(resultPtr);
      }
  }

  late final int Function() _getNumAlive = _lib.lookupFunction<ffi.Uint64 Function(), int Function()>('get_num_alive');

  int getNumAlive() {
      return _getNumAlive();
  }
  // WARNING: Function 'make_rust_getters()' was omitted because
  // the function signature is not yet supported in this FFI binding mode.


  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> value) _println = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> value), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> value)>('println');

  String println(String value) {
    final ffi.Pointer<Utf8> valueNative = value.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _println(valueNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for println');
      }
      final String payload;
      try {
        payload = resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
      final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
      final Object? errRaw = envelope['err'];
      if (errRaw != null) {
        throw ComplexErrorExceptionFfiCodec.decode(errRaw);
      }
      if (!envelope.containsKey('ok')) {
        throw StateError('Rust returned malformed result for println');
      }
      final Object? okRaw = envelope['ok'];
      return okRaw as String;
    } finally {
    calloc.free(valueNative);
    }
  }

  late final _RustBuffer Function(_RustBuffer input) _reverseBytes = _lib.lookupFunction<_RustBuffer Function(_RustBuffer input), _RustBuffer Function(_RustBuffer input)>('reverse_bytes');

  Uint8List reverseBytes(Uint8List input) {
    final ffi.Pointer<ffi.Uint8> inputData = input.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(input.length);
    if (inputData != ffi.nullptr) {
      inputData.asTypedList(input.length).setAll(0, input);
    }
    final ffi.Pointer<_RustBuffer> inputBufferPtr = calloc<_RustBuffer>();
    inputBufferPtr.ref.data = inputData;
    inputBufferPtr.ref.len = input.length;
    final _RustBuffer inputNative = inputBufferPtr.ref;
    try {
      final _RustBuffer resultBuf = _reverseBytes(inputNative);
      final ffi.Pointer<ffi.Uint8> resultData = resultBuf.data;
      final int resultLen = resultBuf.len;
      if (resultData == ffi.nullptr) {
        if (resultLen == 0) {
          _rustBytesFree(resultBuf);
          return Uint8List(0);
        }
        throw StateError('Rust returned invalid buffer for reverse_bytes');
      }
      try {
        return Uint8List.fromList(resultData.asTypedList(resultLen));
      } finally {
        _rustBytesFree(resultBuf);
      }
    } finally {
    if (inputData != ffi.nullptr) calloc.free(inputData);
    calloc.free(inputBufferPtr);
    }
  }

  late final ffi.Pointer<Utf8> Function(int getters) _testGetters = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 getters), ffi.Pointer<Utf8> Function(int getters)>('test_getters');

  void testGetters(Getters getters) {
    _gettersCallbackInitDone;
    final int gettersHandle = _GettersCallbackBridge.instance.register(getters);
    try {
      final ffi.Pointer<Utf8> resultPtr = _testGetters(gettersHandle);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for test_getters');
      }
      final String payload;
      try {
        payload = resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
      final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
      final Object? errRaw = envelope['err'];
      if (errRaw != null) {
        throw CoverallErrorExceptionFfiCodec.decode(errRaw);
      }
      return;
    } finally {
    _GettersCallbackBridge.instance.release(gettersHandle);
    }
  }

  late final void Function(int handle) _coverallsFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('coveralls_free');

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> name, bool shouldFail) _coverallsCtorFallibleNew = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> name, ffi.Bool shouldFail), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> name, bool shouldFail)>('coveralls_fallible_new');

  Coveralls coverallsCreateFallibleNew(String name, bool shouldFail) {
    final ffi.Pointer<Utf8> nameNative = name.toNativeUtf8();
    try {
    final ffi.Pointer<Utf8> resultPtr = _coverallsCtorFallibleNew(nameNative, shouldFail);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for coveralls_fallible_new');
    }
    final String payload;
    try {
      payload = resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
    final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
    final Object? errRaw = envelope['err'];
    if (errRaw != null) {
      throw CoverallErrorExceptionFfiCodec.decode(errRaw);
    }
    final Object? okRaw = envelope['ok'];
    final int handle = (okRaw as num).toInt();
    return Coveralls._(this, handle);
    } finally {
    calloc.free(nameNative);
    }
  }

  late final int Function(ffi.Pointer<Utf8> name) _coverallsCtorNew = _lib.lookupFunction<ffi.Uint64 Function(ffi.Pointer<Utf8> name), int Function(ffi.Pointer<Utf8> name)>('coveralls_new');

  Coveralls coverallsCreateNew(String name) {
    final ffi.Pointer<Utf8> nameNative = name.toNativeUtf8();
    try {
    final int handle = _coverallsCtorNew(nameNative);
    return Coveralls._(this, handle);
    } finally {
    calloc.free(nameNative);
    }
  }

  late final int Function(int handle) _coverallsCloneMe = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle), int Function(int handle)>('coveralls_clone_me');

  Coveralls coverallsInvokeCloneMe(int handle) {
    return CoverallsFfiCodec.lift(_coverallsCloneMe(handle));
  }

  late final ffi.Pointer<Utf8> Function(int handle) _coverallsGetMetadata = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('coveralls_get_metadata');

  Map<String, String?> coverallsInvokeGetMetadata(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _coverallsGetMetadata(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for coveralls_get_metadata');
    }
    try {
      final String payload = resultPtr.toDartString();
      return (jsonDecode(payload) as Map<String, dynamic>).map((key, value) => MapEntry(key, value == null ? null : (() { final __tmp = value; return __tmp as String; })()));
    } finally {
      _rustStringFree(resultPtr);
    }
  }

  late final ffi.Pointer<Utf8> Function(int handle) _coverallsGetName = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('coveralls_get_name');

  String coverallsInvokeGetName(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _coverallsGetName(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for coveralls_get_name');
    }
    try {
      return resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
  }
  // WARNING: Method 'Coveralls.get_other()' was omitted because
  // the method signature is not yet supported in this FFI binding mode.


  late final ffi.Pointer<Utf8> Function(int handle) _coverallsGetTags = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('coveralls_get_tags');

  List<String?> coverallsInvokeGetTags(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _coverallsGetTags(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for coveralls_get_tags');
    }
    try {
      final String payload = resultPtr.toDartString();
      return (jsonDecode(payload) as List).map((item) => item == null ? null : (() { final __tmp = item; return __tmp as String; })()).toList();
    } finally {
      _rustStringFree(resultPtr);
    }
  }

  late final ffi.Pointer<Utf8> Function(int handle, bool shouldThrow) _coverallsMaybeThrow = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Bool shouldThrow), ffi.Pointer<Utf8> Function(int handle, bool shouldThrow)>('coveralls_maybe_throw');

  bool coverallsInvokeMaybeThrow(int handle, bool shouldThrow) {
    final ffi.Pointer<Utf8> resultPtr = _coverallsMaybeThrow(handle, shouldThrow);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for coveralls_maybe_throw');
    }
    final String payload;
    try {
      payload = resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
    final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
    final Object? errRaw = envelope['err'];
    if (errRaw != null) {
      throw CoverallErrorExceptionFfiCodec.decode(errRaw);
    }
    final Object? okRaw = envelope['ok'];
    return okRaw as bool;
  }

  late final ffi.Pointer<Utf8> Function(int handle, int selector) _coverallsMaybeThrowComplex = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Int8 selector), ffi.Pointer<Utf8> Function(int handle, int selector)>('coveralls_maybe_throw_complex');

  bool coverallsInvokeMaybeThrowComplex(int handle, int selector) {
    final ffi.Pointer<Utf8> resultPtr = _coverallsMaybeThrowComplex(handle, selector);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for coveralls_maybe_throw_complex');
    }
    final String payload;
    try {
      payload = resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
    final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
    final Object? errRaw = envelope['err'];
    if (errRaw != null) {
      throw ComplexErrorExceptionFfiCodec.decode(errRaw);
    }
    final Object? okRaw = envelope['ok'];
    return okRaw as bool;
  }

  late final _RustBuffer Function(int handle, _RustBuffer input) _coverallsReverseBytes = _lib.lookupFunction<_RustBuffer Function(ffi.Uint64 handle, _RustBuffer input), _RustBuffer Function(int handle, _RustBuffer input)>('coveralls_reverse_bytes');

  Uint8List coverallsInvokeReverseBytes(int handle, Uint8List input) {
    final ffi.Pointer<ffi.Uint8> inputData = input.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(input.length);
    if (inputData != ffi.nullptr) {
      inputData.asTypedList(input.length).setAll(0, input);
    }
    final ffi.Pointer<_RustBuffer> inputBufferPtr = calloc<_RustBuffer>();
    inputBufferPtr.ref.data = inputData;
    inputBufferPtr.ref.len = input.length;
    final _RustBuffer inputNative = inputBufferPtr.ref;
    try {
    final _RustBuffer resultBuf = _coverallsReverseBytes(handle, inputNative);
    final ffi.Pointer<ffi.Uint8> resultData = resultBuf.data;
    final int resultLen = resultBuf.len;
    if (resultData == ffi.nullptr) {
      if (resultLen == 0) {
        _rustBytesFree(resultBuf);
        return Uint8List(0);
      }
      throw StateError('Rust returned invalid buffer for coveralls_reverse_bytes');
    }
    try {
      return Uint8List.fromList(resultData.asTypedList(resultLen));
    } finally {
      _rustBytesFree(resultBuf);
    }
    } finally {
    if (inputData != ffi.nullptr) calloc.free(inputData);
    calloc.free(inputBufferPtr);
    }
  }

  late final void Function(int handle, ffi.Pointer<Utf8> name) _coverallsSetName = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> name), void Function(int handle, ffi.Pointer<Utf8> name)>('coveralls_set_name');

  void coverallsInvokeSetName(int handle, String name) {
    final ffi.Pointer<Utf8> nameNative = name.toNativeUtf8();
    try {
    _coverallsSetName(handle, nameNative);
    } finally {
    calloc.free(nameNative);
    }
  }

  late final int Function(int handle) _coverallsStrongCount = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle), int Function(int handle)>('coveralls_strong_count');

  int coverallsInvokeStrongCount(int handle) {
    return _coverallsStrongCount(handle);
  }
  // WARNING: Method 'Coveralls.take_other(Coveralls? other)' was omitted because
  // the method signature is not yet supported in this FFI binding mode.


  late final void Function(int handle) _falliblePatchFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('falliblepatch_free');

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> color, bool shouldFail) _falliblePatchCtorNew = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> color, ffi.Bool shouldFail), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> color, bool shouldFail)>('falliblepatch_new');

  FalliblePatch falliblePatchCreateNew(Color color, bool shouldFail) {
    final String colorNativeJson = ColorFfiCodec.encode(color);
    final ffi.Pointer<Utf8> colorNative = colorNativeJson.toNativeUtf8();
    try {
    final ffi.Pointer<Utf8> resultPtr = _falliblePatchCtorNew(colorNative, shouldFail);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for falliblepatch_new');
    }
    final String payload;
    try {
      payload = resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
    final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
    final Object? errRaw = envelope['err'];
    if (errRaw != null) {
      throw CoverallErrorExceptionFfiCodec.decode(errRaw);
    }
    final Object? okRaw = envelope['ok'];
    final int handle = (okRaw as num).toInt();
    return FalliblePatch._(this, handle);
    } finally {
    calloc.free(colorNative);
    }
  }

  late final ffi.Pointer<Utf8> Function(int handle) _falliblePatchGetColor = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('falliblepatch_get_color');

  Color falliblePatchInvokeGetColor(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _falliblePatchGetColor(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for falliblepatch_get_color');
    }
    try {
      final String payload = resultPtr.toDartString();
      return ColorFfiCodec.decode(payload);
    } finally {
      _rustStringFree(resultPtr);
    }
  }

  late final void Function(int handle) _patchFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('patch_free');

  late final int Function(ffi.Pointer<Utf8> color) _patchCtorNew = _lib.lookupFunction<ffi.Uint64 Function(ffi.Pointer<Utf8> color), int Function(ffi.Pointer<Utf8> color)>('patch_new');

  Patch patchCreateNew(Color color) {
    final String colorNativeJson = ColorFfiCodec.encode(color);
    final ffi.Pointer<Utf8> colorNative = colorNativeJson.toNativeUtf8();
    try {
    final int handle = _patchCtorNew(colorNative);
    return Patch._(this, handle);
    } finally {
    calloc.free(colorNative);
    }
  }

  late final ffi.Pointer<Utf8> Function(int handle) _patchGetColor = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('patch_get_color');

  Color patchInvokeGetColor(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _patchGetColor(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for patch_get_color');
    }
    try {
      final String payload = resultPtr.toDartString();
      return ColorFfiCodec.decode(payload);
    } finally {
      _rustStringFree(resultPtr);
    }
  }

  late final void Function(int handle) _threadsafeCounterFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('threadsafecounter_free');

  late final int Function() _threadsafeCounterCtorNew = _lib.lookupFunction<ffi.Uint64 Function(), int Function()>('threadsafecounter_new');

  ThreadsafeCounter threadsafeCounterCreateNew() {
    final int handle = _threadsafeCounterCtorNew();
    return ThreadsafeCounter._(this, handle);
  }

  late final int Function(int handle) _threadsafeCounterGetCount = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle), int Function(int handle)>('threadsafecounter_get_count');

  int threadsafeCounterInvokeGetCount(int handle) {
    return _threadsafeCounterGetCount(handle);
  }

  late final void Function(int handle) _threadsafeCounterIncrement = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('threadsafecounter_increment');

  void threadsafeCounterInvokeIncrement(int handle) {
    _threadsafeCounterIncrement(handle);
  }
}

final class _CoverallsFinalizerToken {
  const _CoverallsFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

/// Main object exercising self-references, state, errors, and Arc semantics.
final class Coveralls {
  Coveralls._(this._ffi, this._handle) {
    _finalizer.attach(this, _CoverallsFinalizerToken(_ffi._coverallsFree, _handle), detach: this);
  }

  final CoverallDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_CoverallsFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._coverallsFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('Coveralls is closed');
    }
  }

  static Coveralls fallibleNew(String name, bool shouldFail) {
    return _bindings().coverallsCreateFallibleNew(name, shouldFail);
  }

  static Coveralls create(String name) {
    return _bindings().coverallsCreateNew(name);
  }

  /// Clone into a new instance (tests object return from method).
  Coveralls cloneMe() {
    _ensureOpen();
    return _ffi.coverallsInvokeCloneMe(_handle);
  }

  /// Return a map with string keys and optional string values.
  Map<String, String?> getMetadata() {
    _ensureOpen();
    return _ffi.coverallsInvokeGetMetadata(_handle);
  }

  String getName() {
    _ensureOpen();
    return _ffi.coverallsInvokeGetName(_handle);
  }

  // WARNING: Method 'Coveralls.get_other()' was omitted because
  // the method signature is not yet supported in this FFI binding mode.

  /// Return a sequence of optional strings.
  List<String?> getTags() {
    _ensureOpen();
    return _ffi.coverallsInvokeGetTags(_handle);
  }

  /// Method that always throws a simple error.
  bool maybeThrow(bool shouldThrow) {
    _ensureOpen();
    return _ffi.coverallsInvokeMaybeThrow(_handle, shouldThrow);
  }

  /// Method that throws a complex (rich) error.
  bool maybeThrowComplex(int selector) {
    _ensureOpen();
    return _ffi.coverallsInvokeMaybeThrowComplex(_handle, selector);
  }

  /// Reverse some bytes via a method (tests binary on object).
  Uint8List reverseBytes(Uint8List input) {
    _ensureOpen();
    return _ffi.coverallsInvokeReverseBytes(_handle, input);
  }

  void setName(String name) {
    _ensureOpen();
    _ffi.coverallsInvokeSetName(_handle, name);
  }

  /// Strong reference count (tests Self=ByArc on the Rust side).
  int strongCount() {
    _ensureOpen();
    return _ffi.coverallsInvokeStrongCount(_handle);
  }

  // WARNING: Method 'Coveralls.take_other(Coveralls? other)' was omitted because
  // the method signature is not yet supported in this FFI binding mode.

}

final class CoverallsFfiCodec {
  const CoverallsFfiCodec._();

  static int lower(Coveralls value) => value._handle;

  static Coveralls lift(int handle) => Coveralls._(_bindings(), handle);
}

final class _FalliblePatchFinalizerToken {
  const _FalliblePatchFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

/// Object with fallible constructor only — no default constructor.
final class FalliblePatch {
  FalliblePatch._(this._ffi, this._handle) {
    _finalizer.attach(this, _FalliblePatchFinalizerToken(_ffi._falliblePatchFree, _handle), detach: this);
  }

  final CoverallDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_FalliblePatchFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._falliblePatchFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('FalliblePatch is closed');
    }
  }

  static FalliblePatch create(Color color, bool shouldFail) {
    return _bindings().falliblePatchCreateNew(color, shouldFail);
  }

  Color getColor() {
    _ensureOpen();
    return _ffi.falliblePatchInvokeGetColor(_handle);
  }

}

final class FalliblePatchFfiCodec {
  const FalliblePatchFfiCodec._();

  static int lower(FalliblePatch value) => value._handle;

  static FalliblePatch lift(int handle) => FalliblePatch._(_bindings(), handle);
}

final class _PatchFinalizerToken {
  const _PatchFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

/// A simple object that wraps a Color.
final class Patch {
  Patch._(this._ffi, this._handle) {
    _finalizer.attach(this, _PatchFinalizerToken(_ffi._patchFree, _handle), detach: this);
  }

  final CoverallDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_PatchFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._patchFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('Patch is closed');
    }
  }

  static Patch create(Color color) {
    return _bindings().patchCreateNew(color);
  }

  Color getColor() {
    _ensureOpen();
    return _ffi.patchInvokeGetColor(_handle);
  }

}

final class PatchFfiCodec {
  const PatchFfiCodec._();

  static int lower(Patch value) => value._handle;

  static Patch lift(int handle) => Patch._(_bindings(), handle);
}

final class _ThreadsafeCounterFinalizerToken {
  const _ThreadsafeCounterFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

/// Thread-safe counter (tests atomic state and thread safety).
final class ThreadsafeCounter {
  ThreadsafeCounter._(this._ffi, this._handle) {
    _finalizer.attach(this, _ThreadsafeCounterFinalizerToken(_ffi._threadsafeCounterFree, _handle), detach: this);
  }

  final CoverallDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_ThreadsafeCounterFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._threadsafeCounterFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('ThreadsafeCounter is closed');
    }
  }

  static ThreadsafeCounter create() {
    return _bindings().threadsafeCounterCreateNew();
  }

  int getCount() {
    _ensureOpen();
    return _ffi.threadsafeCounterInvokeGetCount(_handle);
  }

  void increment() {
    _ensureOpen();
    _ffi.threadsafeCounterInvokeIncrement(_handle);
  }

}

final class ThreadsafeCounterFfiCodec {
  const ThreadsafeCounterFfiCodec._();

  static int lower(ThreadsafeCounter value) => value._handle;

  static ThreadsafeCounter lift(int handle) => ThreadsafeCounter._(_bindings(), handle);
}

CoverallDemoFfi? _defaultBindings;

CoverallDemoFfi _bindings() => _defaultBindings ??= CoverallDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = CoverallDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

/// Walk up a NodeTrait tree, collecting ancestor names.
List<String> ancestorNames(NodeTrait node) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

/// Create a SimpleDict whose optional fields are all null.
SimpleDict createNoneDict() {
  return _bindings().createNoneDict();
}

/// Create a Patch with a specific color.
Patch createPatch(Color color) {
  return _bindings().createPatch(color);
}

/// Create a SimpleDict with sample values filled in.
SimpleDict createSomeDict() {
  return _bindings().createSomeDict();
}

/// Divide a float by a text-parsed divisor; exercises error paths.
double divideByText(double value, String divisor) {
  return _bindings().divideByText(value, divisor);
}

/// Round-trip a map with non-string keys (record<u32, u64>).
Map<int, int> getIntMap(int key, int value) {
  return _bindings().getIntMap(key, value);
}

/// Return an enum variant based on a numeric selector.
MaybeSimpleDict getMaybeSimpleDict(int index) {
  return _bindings().getMaybeSimpleDict(index);
}

/// Return the number of live Coveralls instances (tracking via constructor/destructor).
int getNumAlive() {
  return _bindings().getNumAlive();
}

/// Create a Rust-implemented Getters for trait round-trip tests.
Getters makeRustGetters() {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

/// Round-trip a string; throws ComplexError on certain inputs.
String println(String value) {
  return _bindings().println(value);
}

/// Reverse arbitrary bytes (binary data round-trip).
Uint8List reverseBytes(Uint8List input) {
  return _bindings().reverseBytes(input);
}

/// Exercise a foreign-implemented Getters.
void testGetters(Getters getters) {
  _bindings().testGetters(getters);
}

