// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unused_field, unnecessary_non_null_assertion, dead_code
library record_enum_methods;

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'dart:typed_data';

typedef MethodLabel = String;

final class _UniFfiFfiBufferElement extends ffi.Union {
  @ffi.Uint8()
  external int u8;

  @ffi.Int8()
  external int i8;

  @ffi.Uint16()
  external int u16;

  @ffi.Int16()
  external int i16;

  @ffi.Uint32()
  external int u32;

  @ffi.Int32()
  external int i32;

  @ffi.Uint64()
  external int u64;

  @ffi.Int64()
  external int i64;

  @ffi.Float()
  external double float32;

  @ffi.Double()
  external double float64;

  external ffi.Pointer<ffi.Void> ptr;
}

final class _UniFfiRustBuffer extends ffi.Struct {
  @ffi.Uint64()
  external int capacity;

  @ffi.Uint64()
  external int len;

  external ffi.Pointer<ffi.Uint8> data;
}

final class _UniFfiForeignBytes extends ffi.Struct {
  @ffi.Int32()
  external int len;

  external ffi.Pointer<ffi.Uint8> data;
}

final class _UniFfiRustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external _UniFfiRustBuffer errorBuf;
}

const int _uniFfiRustCallStatusSuccess = 0;
const int _uniFfiRustCallStatusError = 1;
const int _uniFfiRustCallStatusUnexpectedError = 2;
const int _uniFfiRustCallStatusCancelled = 3;

final class _RustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external ffi.Pointer<Utf8> errorBuf;
}

const int _rustCallStatusSuccess = 0;
const int _rustCallStatusError = 1;
const int _rustCallStatusUnexpectedError = 2;
const int _rustCallStatusCancelled = 3;
const int _rustFuturePollReady = 0;
const int _rustFuturePollWake = 1;

class MethodPoint {
  const MethodPoint({
    required this.x,
    required this.y,
  });

  final int x;
  final int y;

  Map<String, dynamic> toJson() {
    return {
      'x': this.x,
      'y': this.y,
    };
  }

  factory MethodPoint.fromJson(Map<String, dynamic> json) {
    return MethodPoint(
      x: (json['x'] as num).toInt(),
      y: (json['y'] as num).toInt(),
    );
  }

  MethodPoint copyWith({
    int? x,
    int? y,
  }) {
    return MethodPoint(
      x: x ?? this.x,
      y: y ?? this.y,
    );
  }

  MethodState asState() {
    return _bindings().methodpointAsState(this);
  }

  Future<String> asyncLabel(String prefix) {
    return _bindings().methodpointAsyncLabel(this, prefix);
  }

  int checkedDivide(int divisor) {
    return _bindings().methodpointCheckedDivide(this, divisor);
  }

  int checksum() {
    return _bindings().methodpointChecksum(this);
  }

  @override
  String toString() {
    return 'MethodPoint(x: $x, y: $y)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MethodPoint && x == other.x && y == other.y;

  @override
  int get hashCode => Object.hash(x, y);
}

sealed class MethodError {
  const MethodError();
}

final class MethodErrorDivisionByZero extends MethodError {
  const MethodErrorDivisionByZero();

  @override
  String toString() {
    return 'MethodErrorDivisionByZero()';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MethodErrorDivisionByZero;

  @override
  int get hashCode => runtimeType.hashCode;
}

final class MethodErrorNegativeInput extends MethodError {
  const MethodErrorNegativeInput({
    required this.value,
  });
  final int value;

  @override
  String toString() {
    return 'MethodErrorNegativeInput(value: $value)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MethodErrorNegativeInput && value == other.value;

  @override
  int get hashCode => value.hashCode;
}

sealed class MethodOutcome {
  const MethodOutcome();

  Future<String> asyncLabel(String prefix) {
    return _bindings().methodoutcomeAsyncLabel(this, prefix);
  }

  int checkedValue() {
    return _bindings().methodoutcomeCheckedValue(this);
  }

  int score() {
    return _bindings().methodoutcomeScore(this);
  }
}

final class MethodOutcomeOk extends MethodOutcome {
  const MethodOutcomeOk({
    required this.value,
  });
  final int value;

  @override
  String toString() {
    return 'MethodOutcomeOk(value: $value)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MethodOutcomeOk && value == other.value;

  @override
  int get hashCode => value.hashCode;
}

final class MethodOutcomeErr extends MethodOutcome {
  const MethodOutcomeErr({
    required this.message,
  });
  final String message;

  @override
  String toString() {
    return 'MethodOutcomeErr(message: $message)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MethodOutcomeErr && message == other.message;

  @override
  int get hashCode => message.hashCode;
}

enum MethodState {
  idle,
  busy,
}

extension MethodStateMethods on MethodState {

  Future<String> asyncLabel(String prefix) {
    return _bindings().methodstateAsyncLabel(this, prefix);
  }

  int checkedCode(bool allowBusy) {
    return _bindings().methodstateCheckedCode(this, allowBusy);
  }

  MethodOutcome toOutcome() {
    return _bindings().methodstateToOutcome(this);
  }

  int weight() {
    return _bindings().methodstateWeight(this);
  }
}

sealed class MethodErrorException implements Exception {
  const MethodErrorException();
}

final class MethodErrorExceptionDivisionByZero extends MethodErrorException {
  const MethodErrorExceptionDivisionByZero();

  @override
  String toString() {
    return 'MethodErrorExceptionDivisionByZero()';
  }
}

final class MethodErrorExceptionNegativeInput extends MethodErrorException {
  const MethodErrorExceptionNegativeInput({
    required this.value,
  });
  final int value;

  @override
  String toString() {
    return 'MethodErrorExceptionNegativeInput(value: $value)';
  }
}

MethodErrorException _uniffiLiftMethodErrorException(Uint8List bytes) {
  final MethodError value = _uniffiDecodeMethodError(bytes);
  if (value is MethodErrorDivisionByZero) return const MethodErrorExceptionDivisionByZero();
  if (value is MethodErrorNegativeInput) {
    return MethodErrorExceptionNegativeInput(
      value: value.value,
    );
  }
  throw StateError('Unknown MethodError error variant while lifting exception: $value');
}

String _encodeMethodError(MethodError value) {
  if (value is MethodErrorDivisionByZero) {
    return jsonEncode({
      'tag': 'divisionByZero',
    });
  }
  if (value is MethodErrorNegativeInput) {
    return jsonEncode({
      'tag': 'negativeInput',
      'value': value.value,
    });
  }
  throw StateError('Unknown MethodError variant instance: $value');
}

MethodError _decodeMethodError(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'divisionByZero':
      return MethodErrorDivisionByZero(
      );
    case 'negativeInput':
      return MethodErrorNegativeInput(
        value: (map['value'] as num).toInt(),
      );
    default:
      throw StateError('Unknown MethodError variant tag: $tag');
  }
}

String _encodeMethodOutcome(MethodOutcome value) {
  if (value is MethodOutcomeOk) {
    return jsonEncode({
      'tag': 'ok',
      'value': value.value,
    });
  }
  if (value is MethodOutcomeErr) {
    return jsonEncode({
      'tag': 'err',
      'message': value.message,
    });
  }
  throw StateError('Unknown MethodOutcome variant instance: $value');
}

MethodOutcome _decodeMethodOutcome(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'ok':
      return MethodOutcomeOk(
        value: (map['value'] as num).toInt(),
      );
    case 'err':
      return MethodOutcomeErr(
        message: map['message'] as String,
      );
    default:
      throw StateError('Unknown MethodOutcome variant tag: $tag');
  }
}

String _encodeMethodState(MethodState value) {
  return switch (value) {
    MethodState.idle => 'idle',
    MethodState.busy => 'busy',
  };
}

MethodState _decodeMethodState(String raw) {
  return switch (raw) {
    'idle' => MethodState.idle,
    'busy' => MethodState.busy,
    _ => throw StateError('Unknown MethodState variant: $raw'),
  };
}

String _encodeMethodErrorException(MethodErrorException value) {
  if (value is MethodErrorExceptionDivisionByZero) {
    return jsonEncode({
      'tag': 'divisionByZero',
    });
  }
  if (value is MethodErrorExceptionNegativeInput) {
    return jsonEncode({
      'tag': 'negativeInput',
      'value': value.value,
    });
  }
  throw StateError('Unknown MethodErrorException exception instance: $value');
}

MethodErrorException _decodeMethodErrorException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'divisionByZero':
      return const MethodErrorExceptionDivisionByZero();
    case 'negativeInput':
      return MethodErrorExceptionNegativeInput(
        value: (map['value'] as num).toInt(),
      );
    default:
      throw StateError('Unknown MethodErrorException exception tag: $tag');
  }
}

final class MethodErrorFfiCodec {
  const MethodErrorFfiCodec._();

  static String encode(MethodError value) => _encodeMethodError(value);

  static MethodError decode(String raw) => _decodeMethodError(raw);
}

final class MethodOutcomeFfiCodec {
  const MethodOutcomeFfiCodec._();

  static String encode(MethodOutcome value) => _encodeMethodOutcome(value);

  static MethodOutcome decode(String raw) => _decodeMethodOutcome(raw);
}

final class MethodStateFfiCodec {
  const MethodStateFfiCodec._();

  static String encode(MethodState value) => _encodeMethodState(value);

  static MethodState decode(String raw) => _decodeMethodState(raw);
}

final class MethodErrorExceptionFfiCodec {
  const MethodErrorExceptionFfiCodec._();

  static String encode(MethodErrorException value) => _encodeMethodErrorException(value);

  static MethodErrorException decode(Object? raw) => _decodeMethodErrorException(raw);
}

final class _UniFfiBinaryWriter {
  final BytesBuilder _builder = BytesBuilder(copy: false);

  void writeU8(int value) => _builder.add([value & 0xFF]);
  void writeI8(int value) => _builder.add([(value) & 0xFF]);
  void writeU16(int value) {
    final data = ByteData(2)..setUint16(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI16(int value) {
    final data = ByteData(2)..setInt16(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeU32(int value) {
    final data = ByteData(4)..setUint32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI32(int value) {
    final data = ByteData(4)..setInt32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeU64(int value) {
    final data = ByteData(8)..setUint64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeI64(int value) {
    final data = ByteData(8)..setInt64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeF32(double value) {
    final data = ByteData(4)..setFloat32(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeF64(double value) {
    final data = ByteData(8)..setFloat64(0, value, Endian.big);
    _builder.add(data.buffer.asUint8List());
  }
  void writeBool(bool value) => writeI8(value ? 1 : 0);
  void writeBytes(Uint8List bytes) => _builder.add(bytes);
  void writeString(String value) {
    final bytes = Uint8List.fromList(utf8.encode(value));
    writeI32(bytes.length);
    writeBytes(bytes);
  }

  Uint8List toBytes() => _builder.takeBytes();
}

final class _UniFfiBinaryReader {
  _UniFfiBinaryReader(this._bytes);
  final Uint8List _bytes;
  int _offset = 0;

  bool get isDone => _offset == _bytes.length;

  ByteData _readData(int len) {
    if (_offset + len > _bytes.length) {
      throw StateError('buffer underflow while decoding UniFFI payload');
    }
    final data = ByteData.sublistView(_bytes, _offset, _offset + len);
    _offset += len;
    return data;
  }

  int readU8() => _readData(1).getUint8(0);
  int readI8() => _readData(1).getInt8(0);
  int readU16() => _readData(2).getUint16(0, Endian.big);
  int readI16() => _readData(2).getInt16(0, Endian.big);
  int readU32() => _readData(4).getUint32(0, Endian.big);
  int readI32() => _readData(4).getInt32(0, Endian.big);
  int readU64() => _readData(8).getUint64(0, Endian.big);
  int readI64() => _readData(8).getInt64(0, Endian.big);
  double readF32() => _readData(4).getFloat32(0, Endian.big);
  double readF64() => _readData(8).getFloat64(0, Endian.big);
  bool readBool() {
    final value = readI8();
    if (value == 0) return false;
    if (value == 1) return true;
    throw StateError('invalid boolean payload value: $value');
  }
  Uint8List readBytes(int len) {
    if (_offset + len > _bytes.length) {
      throw StateError('buffer underflow while decoding UniFFI payload bytes');
    }
    final out = Uint8List.fromList(_bytes.sublist(_offset, _offset + len));
    _offset += len;
    return out;
  }
  String readString() {
    final len = readI32();
    if (len < 0) {
      throw StateError('invalid string length in UniFFI payload: $len');
    }
    return utf8.decode(readBytes(len));
  }
}

void _uniffiWriteMethodPoint(MethodPoint value, _UniFfiBinaryWriter writer) {
  writer.writeU32(value.x);
  writer.writeU32(value.y);
}

Uint8List _uniffiEncodeMethodPoint(MethodPoint value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteMethodPoint(value, writer);
  return writer.toBytes();
}

MethodPoint _uniffiReadMethodPoint(_UniFfiBinaryReader reader) {
  return MethodPoint(
    x: reader.readU32(),
    y: reader.readU32(),
  );
}

MethodPoint _uniffiDecodeMethodPoint(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadMethodPoint(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding MethodPoint');
  }
  return value;
}

void _uniffiWriteMethodError(MethodError value, _UniFfiBinaryWriter writer) {
  if (value is MethodErrorDivisionByZero) {
    writer.writeI32(1);
  }
  else if (value is MethodErrorNegativeInput) {
    writer.writeI32(2);
    writer.writeI32(value.value);
  }
  else {
    throw StateError('Unknown MethodError variant instance: $value');
  }
}

Uint8List _uniffiEncodeMethodError(MethodError value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteMethodError(value, writer);
  return writer.toBytes();
}

MethodError _uniffiReadMethodError(_UniFfiBinaryReader reader) {
  final int tag = reader.readI32();
  switch (tag) {
    case 1:
      return const MethodErrorDivisionByZero();
    case 2:
      return MethodErrorNegativeInput(
        value: reader.readI32(),
      );
    default:
      throw StateError('Unknown MethodError variant tag: $tag');
  }
}

MethodError _uniffiDecodeMethodError(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadMethodError(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding MethodError');
  }
  return value;
}

void _uniffiWriteMethodOutcome(MethodOutcome value, _UniFfiBinaryWriter writer) {
  if (value is MethodOutcomeOk) {
    writer.writeI32(1);
    writer.writeU32(value.value);
  }
  else if (value is MethodOutcomeErr) {
    writer.writeI32(2);
    writer.writeString(value.message);
  }
  else {
    throw StateError('Unknown MethodOutcome variant instance: $value');
  }
}

Uint8List _uniffiEncodeMethodOutcome(MethodOutcome value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteMethodOutcome(value, writer);
  return writer.toBytes();
}

MethodOutcome _uniffiReadMethodOutcome(_UniFfiBinaryReader reader) {
  final int tag = reader.readI32();
  switch (tag) {
    case 1:
      return MethodOutcomeOk(
        value: reader.readU32(),
      );
    case 2:
      return MethodOutcomeErr(
        message: reader.readString(),
      );
    default:
      throw StateError('Unknown MethodOutcome variant tag: $tag');
  }
}

MethodOutcome _uniffiDecodeMethodOutcome(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadMethodOutcome(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding MethodOutcome');
  }
  return value;
}

void _uniffiWriteMethodState(MethodState value, _UniFfiBinaryWriter writer) {
  final int tag = switch (value) {
    MethodState.idle => 1,
    MethodState.busy => 2,
  };
  writer.writeI32(tag);
}

Uint8List _uniffiEncodeMethodState(MethodState value) {
  final writer = _UniFfiBinaryWriter();
  _uniffiWriteMethodState(value, writer);
  return writer.toBytes();
}

MethodState _uniffiReadMethodState(_UniFfiBinaryReader reader) {
  final int tag = reader.readI32();
  switch (tag) {
    case 1:
      return MethodState.idle;
    case 2:
      return MethodState.busy;
    default:
      throw StateError('Unknown MethodState variant tag: $tag');
  }
}

MethodState _uniffiDecodeMethodState(Uint8List bytes) {
  final reader = _UniFfiBinaryReader(bytes);
  final value = _uniffiReadMethodState(reader);
  if (!reader.isDone) {
    throw StateError('extra bytes remaining while decoding MethodState');
  }
  return value;
}

class RecordEnumMethodsFfi {
  RecordEnumMethodsFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_record_enum_methods';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  void _ensureApiIntegrity(ffi.DynamicLibrary lib) {
    const int bindingsContractVersion = 30;
    final int scaffoldingContractVersion;
    try {
      final int Function() ffiContractVersion = lib.lookupFunction<ffi.Uint32 Function(), int Function()>('ffi_uniffi_record_enum_methods_uniffi_contract_version');
      scaffoldingContractVersion = ffiContractVersion();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI contract-version symbol `ffi_uniffi_record_enum_methods_uniffi_contract_version`: $err');
    }
    if (bindingsContractVersion != scaffoldingContractVersion) {
      throw StateError('UniFFI contract version mismatch: expected $bindingsContractVersion, got $scaffoldingContractVersion');
    }
    final int _checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_outcome_ok;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_uniffi_record_enum_methods_checksum_func_method_outcome_ok');
      _checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_outcome_ok = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_uniffi_record_enum_methods_checksum_func_method_outcome_ok`: $err');
    }
    if (_checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_outcome_ok != 31606) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_uniffi_record_enum_methods_checksum_func_method_outcome_ok`: expected 31606, got $_checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_outcome_ok');
    }
    final int _checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_point_new;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_uniffi_record_enum_methods_checksum_func_method_point_new');
      _checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_point_new = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_uniffi_record_enum_methods_checksum_func_method_point_new`: $err');
    }
    if (_checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_point_new != 52766) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_uniffi_record_enum_methods_checksum_func_method_point_new`: expected 52766, got $_checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_point_new');
    }
    final int _checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_state_busy;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_uniffi_record_enum_methods_checksum_func_method_state_busy');
      _checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_state_busy = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_uniffi_record_enum_methods_checksum_func_method_state_busy`: $err');
    }
    if (_checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_state_busy != 30812) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_uniffi_record_enum_methods_checksum_func_method_state_busy`: expected 30812, got $_checksum_uniffi_uniffi_record_enum_methods_checksum_func_method_state_busy');
    }
  }

  late final ffi.DynamicLibrary _lib = (() {
    final ffi.DynamicLibrary lib = open();
    _ensureApiIntegrity(lib);
    return lib;
  })();

  late final _UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _uniFfiRustBufferFromBytes = _lib.lookupFunction<_UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus), _UniFfiRustBuffer Function(_UniFfiForeignBytes bytes, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_record_enum_methods_rustbuffer_from_bytes');
  late final void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _uniFfiRustBufferFree = _lib.lookupFunction<ffi.Void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus), void Function(_UniFfiRustBuffer buf, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_record_enum_methods_rustbuffer_free');

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodOutcomeOkFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_func_method_outcome_ok');

  MethodOutcome methodOutcomeOk(int value) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(1);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      (argBuf + 0).ref.u32 = value;
      _methodOutcomeOkFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeMethodOutcome(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodPointNewFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_func_method_point_new');

  MethodPoint methodPointNew(int x, int y) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(2);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      (argBuf + 0).ref.u32 = x;
      (argBuf + 1).ref.u32 = y;
      _methodPointNewFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeMethodPoint(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodStateBusyFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_func_method_state_busy');

  MethodState methodStateBusy() {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(0);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      _methodStateBusyFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeMethodState(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodpointAsStateFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodpoint_as_state');

  MethodState methodpointAsState(MethodPoint self) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodPoint(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      _methodpointAsStateFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeMethodState(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodpointAsyncLabelFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodpoint_async_label');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _methodpointAsyncLabelFfiBufferRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('ffi_uniffi_record_enum_methods_rust_future_poll_rust_buffer');
  late final void Function(int handle) _methodpointAsyncLabelFfiBufferRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_record_enum_methods_rust_future_cancel_rust_buffer');
  late final _UniFfiRustBuffer Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _methodpointAsyncLabelFfiBufferRustFutureComplete = _lib.lookupFunction<_UniFfiRustBuffer Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), _UniFfiRustBuffer Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_record_enum_methods_rust_future_complete_rust_buffer');
  late final void Function(int handle) _methodpointAsyncLabelFfiBufferRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_record_enum_methods_rust_future_free_rust_buffer');

  Future<String> methodpointAsyncLabel(MethodPoint self, String prefix) async {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(6);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodPoint(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      final Uint8List prefixBytes = Uint8List.fromList(utf8.encode(prefix));
      final ffi.Pointer<ffi.Uint8> prefixPtr = prefixBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(prefixBytes.length);
      if (prefixBytes.isNotEmpty) { prefixPtr.asTypedList(prefixBytes.length).setAll(0, prefixBytes); }
      foreignArgPtrs.add(prefixPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> prefixFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      prefixFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      prefixFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> prefixForeignPtr = calloc<_UniFfiForeignBytes>();
      prefixForeignPtr.ref
        ..len = prefixBytes.length
        ..data = prefixPtr;
      final _UniFfiRustBuffer prefixRustBuffer = _uniFfiRustBufferFromBytes(prefixForeignPtr.ref, prefixFromBytesStatusPtr);
      calloc.free(prefixForeignPtr);
      final int prefixFromBytesCode = prefixFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer prefixFromBytesErrBuf = prefixFromBytesStatusPtr.ref.errorBuf;
      calloc.free(prefixFromBytesStatusPtr);
      if (prefixFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> prefixFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        prefixFromBytesErrBufPtr.ref
          ..capacity = prefixFromBytesErrBuf.capacity
          ..len = prefixFromBytesErrBuf.len
          ..data = prefixFromBytesErrBuf.data;
        rustRetBufferPtrs.add(prefixFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $prefixFromBytesCode');
      }
      (argBuf + 3).ref.u64 = prefixRustBuffer.capacity;
      (argBuf + 4).ref.u64 = prefixRustBuffer.len;
      (argBuf + 5).ref.ptr = prefixRustBuffer.data.cast<ffi.Void>();
      _methodpointAsyncLabelFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer async start failed with status $statusCode');
      }
      final int futureHandle = (returnBuf + 0).ref.u64;
      final StreamController<int> pollEvents = StreamController<int>.broadcast();
      final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
        pollEvents.add(pollResult);
      });
      try {
        _methodpointAsyncLabelFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
        while (true) {
          final int pollResult = await pollEvents.stream.first;
          if (pollResult == _rustFuturePollReady) {
            break;
          }
          if (pollResult == _rustFuturePollWake) {
            _methodpointAsyncLabelFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
            continue;
          }
          throw StateError('Rust future poll returned invalid status for methodpoint_async_label: $pollResult');
        }
        final ffi.Pointer<_UniFfiRustCallStatus> outStatusPtr = calloc<_UniFfiRustCallStatus>();
        outStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        outStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        try {
          final _UniFfiRustBuffer resultValue = _methodpointAsyncLabelFfiBufferRustFutureComplete(futureHandle, outStatusPtr);
          final int completeStatusCode = outStatusPtr.ref.code;
          if (completeStatusCode == _uniFfiRustCallStatusSuccess) {
            final ffi.Pointer<_UniFfiRustBuffer> resultBufPtr = calloc<_UniFfiRustBuffer>();
            resultBufPtr.ref
              ..capacity = resultValue.capacity
              ..len = resultValue.len
              ..data = resultValue.data;
            rustRetBufferPtrs.add(resultBufPtr);
            final Uint8List resultBytes = resultBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(resultBufPtr.ref.data.asTypedList(resultBufPtr.ref.len));
            return utf8.decode(resultBytes);
          }
          if (completeStatusCode == _uniFfiRustCallStatusCancelled) {
            throw StateError('Rust future was cancelled for methodpoint_async_label');
          }
          final _UniFfiRustBuffer errorBuf = outStatusPtr.ref.errorBuf;
          if (!(errorBuf.data == ffi.nullptr && errorBuf.len == 0 && errorBuf.capacity == 0)) {
            final ffi.Pointer<_UniFfiRustBuffer> errorBufPtr = calloc<_UniFfiRustBuffer>();
            errorBufPtr.ref
              ..capacity = errorBuf.capacity
              ..len = errorBuf.len
              ..data = errorBuf.data;
            rustRetBufferPtrs.add(errorBufPtr);
            final Uint8List errorBytes = errorBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errorBufPtr.ref.data.asTypedList(errorBufPtr.ref.len));
            if (errorBytes.isNotEmpty) {
              throw StateError(utf8.decode(errorBytes, allowMalformed: true));
            }
          }
          throw StateError('Rust future failed for methodpoint_async_label with status code: $completeStatusCode');
        } finally {
          calloc.free(outStatusPtr);
        }
      } catch (_) {
        _methodpointAsyncLabelFfiBufferRustFutureCancel(futureHandle);
        rethrow;
      } finally {
        await pollEvents.close();
        callback.close();
        _methodpointAsyncLabelFfiBufferRustFutureFree(futureHandle);
      }
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodpointCheckedDivideFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodpoint_checked_divide');

  int methodpointCheckedDivide(MethodPoint self, int divisor) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(4);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodPoint(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      (argBuf + 3).ref.u32 = divisor;
      _methodpointCheckedDivideFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        if (statusCode == _uniFfiRustCallStatusError) {
          final Uint8List errBytes = errBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errBufPtr.ref.data.asTypedList(errBufPtr.ref.len));
          throw _uniffiLiftMethodErrorException(errBytes);
        }
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return (returnBuf + 0).ref.u32;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodpointChecksumFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodpoint_checksum');

  int methodpointChecksum(MethodPoint self) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodPoint(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      _methodpointChecksumFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return (returnBuf + 0).ref.u32;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodoutcomeAsyncLabelFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodoutcome_async_label');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _methodoutcomeAsyncLabelFfiBufferRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('ffi_uniffi_record_enum_methods_rust_future_poll_rust_buffer');
  late final void Function(int handle) _methodoutcomeAsyncLabelFfiBufferRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_record_enum_methods_rust_future_cancel_rust_buffer');
  late final _UniFfiRustBuffer Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _methodoutcomeAsyncLabelFfiBufferRustFutureComplete = _lib.lookupFunction<_UniFfiRustBuffer Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), _UniFfiRustBuffer Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_record_enum_methods_rust_future_complete_rust_buffer');
  late final void Function(int handle) _methodoutcomeAsyncLabelFfiBufferRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_record_enum_methods_rust_future_free_rust_buffer');

  Future<String> methodoutcomeAsyncLabel(MethodOutcome self, String prefix) async {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(6);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodOutcome(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      final Uint8List prefixBytes = Uint8List.fromList(utf8.encode(prefix));
      final ffi.Pointer<ffi.Uint8> prefixPtr = prefixBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(prefixBytes.length);
      if (prefixBytes.isNotEmpty) { prefixPtr.asTypedList(prefixBytes.length).setAll(0, prefixBytes); }
      foreignArgPtrs.add(prefixPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> prefixFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      prefixFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      prefixFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> prefixForeignPtr = calloc<_UniFfiForeignBytes>();
      prefixForeignPtr.ref
        ..len = prefixBytes.length
        ..data = prefixPtr;
      final _UniFfiRustBuffer prefixRustBuffer = _uniFfiRustBufferFromBytes(prefixForeignPtr.ref, prefixFromBytesStatusPtr);
      calloc.free(prefixForeignPtr);
      final int prefixFromBytesCode = prefixFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer prefixFromBytesErrBuf = prefixFromBytesStatusPtr.ref.errorBuf;
      calloc.free(prefixFromBytesStatusPtr);
      if (prefixFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> prefixFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        prefixFromBytesErrBufPtr.ref
          ..capacity = prefixFromBytesErrBuf.capacity
          ..len = prefixFromBytesErrBuf.len
          ..data = prefixFromBytesErrBuf.data;
        rustRetBufferPtrs.add(prefixFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $prefixFromBytesCode');
      }
      (argBuf + 3).ref.u64 = prefixRustBuffer.capacity;
      (argBuf + 4).ref.u64 = prefixRustBuffer.len;
      (argBuf + 5).ref.ptr = prefixRustBuffer.data.cast<ffi.Void>();
      _methodoutcomeAsyncLabelFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer async start failed with status $statusCode');
      }
      final int futureHandle = (returnBuf + 0).ref.u64;
      final StreamController<int> pollEvents = StreamController<int>.broadcast();
      final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
        pollEvents.add(pollResult);
      });
      try {
        _methodoutcomeAsyncLabelFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
        while (true) {
          final int pollResult = await pollEvents.stream.first;
          if (pollResult == _rustFuturePollReady) {
            break;
          }
          if (pollResult == _rustFuturePollWake) {
            _methodoutcomeAsyncLabelFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
            continue;
          }
          throw StateError('Rust future poll returned invalid status for methodoutcome_async_label: $pollResult');
        }
        final ffi.Pointer<_UniFfiRustCallStatus> outStatusPtr = calloc<_UniFfiRustCallStatus>();
        outStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        outStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        try {
          final _UniFfiRustBuffer resultValue = _methodoutcomeAsyncLabelFfiBufferRustFutureComplete(futureHandle, outStatusPtr);
          final int completeStatusCode = outStatusPtr.ref.code;
          if (completeStatusCode == _uniFfiRustCallStatusSuccess) {
            final ffi.Pointer<_UniFfiRustBuffer> resultBufPtr = calloc<_UniFfiRustBuffer>();
            resultBufPtr.ref
              ..capacity = resultValue.capacity
              ..len = resultValue.len
              ..data = resultValue.data;
            rustRetBufferPtrs.add(resultBufPtr);
            final Uint8List resultBytes = resultBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(resultBufPtr.ref.data.asTypedList(resultBufPtr.ref.len));
            return utf8.decode(resultBytes);
          }
          if (completeStatusCode == _uniFfiRustCallStatusCancelled) {
            throw StateError('Rust future was cancelled for methodoutcome_async_label');
          }
          final _UniFfiRustBuffer errorBuf = outStatusPtr.ref.errorBuf;
          if (!(errorBuf.data == ffi.nullptr && errorBuf.len == 0 && errorBuf.capacity == 0)) {
            final ffi.Pointer<_UniFfiRustBuffer> errorBufPtr = calloc<_UniFfiRustBuffer>();
            errorBufPtr.ref
              ..capacity = errorBuf.capacity
              ..len = errorBuf.len
              ..data = errorBuf.data;
            rustRetBufferPtrs.add(errorBufPtr);
            final Uint8List errorBytes = errorBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errorBufPtr.ref.data.asTypedList(errorBufPtr.ref.len));
            if (errorBytes.isNotEmpty) {
              throw StateError(utf8.decode(errorBytes, allowMalformed: true));
            }
          }
          throw StateError('Rust future failed for methodoutcome_async_label with status code: $completeStatusCode');
        } finally {
          calloc.free(outStatusPtr);
        }
      } catch (_) {
        _methodoutcomeAsyncLabelFfiBufferRustFutureCancel(futureHandle);
        rethrow;
      } finally {
        await pollEvents.close();
        callback.close();
        _methodoutcomeAsyncLabelFfiBufferRustFutureFree(futureHandle);
      }
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodoutcomeCheckedValueFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodoutcome_checked_value');

  int methodoutcomeCheckedValue(MethodOutcome self) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodOutcome(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      _methodoutcomeCheckedValueFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        if (statusCode == _uniFfiRustCallStatusError) {
          final Uint8List errBytes = errBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errBufPtr.ref.data.asTypedList(errBufPtr.ref.len));
          throw _uniffiLiftMethodErrorException(errBytes);
        }
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return (returnBuf + 0).ref.u32;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodoutcomeScoreFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodoutcome_score');

  int methodoutcomeScore(MethodOutcome self) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodOutcome(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      _methodoutcomeScoreFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return (returnBuf + 0).ref.u32;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodstateAsyncLabelFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodstate_async_label');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _methodstateAsyncLabelFfiBufferRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('ffi_uniffi_record_enum_methods_rust_future_poll_rust_buffer');
  late final void Function(int handle) _methodstateAsyncLabelFfiBufferRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_record_enum_methods_rust_future_cancel_rust_buffer');
  late final _UniFfiRustBuffer Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus) _methodstateAsyncLabelFfiBufferRustFutureComplete = _lib.lookupFunction<_UniFfiRustBuffer Function(ffi.Uint64 handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus), _UniFfiRustBuffer Function(int handle, ffi.Pointer<_UniFfiRustCallStatus> outStatus)>('ffi_uniffi_record_enum_methods_rust_future_complete_rust_buffer');
  late final void Function(int handle) _methodstateAsyncLabelFfiBufferRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('ffi_uniffi_record_enum_methods_rust_future_free_rust_buffer');

  Future<String> methodstateAsyncLabel(MethodState self, String prefix) async {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(6);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodState(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      final Uint8List prefixBytes = Uint8List.fromList(utf8.encode(prefix));
      final ffi.Pointer<ffi.Uint8> prefixPtr = prefixBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(prefixBytes.length);
      if (prefixBytes.isNotEmpty) { prefixPtr.asTypedList(prefixBytes.length).setAll(0, prefixBytes); }
      foreignArgPtrs.add(prefixPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> prefixFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      prefixFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      prefixFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> prefixForeignPtr = calloc<_UniFfiForeignBytes>();
      prefixForeignPtr.ref
        ..len = prefixBytes.length
        ..data = prefixPtr;
      final _UniFfiRustBuffer prefixRustBuffer = _uniFfiRustBufferFromBytes(prefixForeignPtr.ref, prefixFromBytesStatusPtr);
      calloc.free(prefixForeignPtr);
      final int prefixFromBytesCode = prefixFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer prefixFromBytesErrBuf = prefixFromBytesStatusPtr.ref.errorBuf;
      calloc.free(prefixFromBytesStatusPtr);
      if (prefixFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> prefixFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        prefixFromBytesErrBufPtr.ref
          ..capacity = prefixFromBytesErrBuf.capacity
          ..len = prefixFromBytesErrBuf.len
          ..data = prefixFromBytesErrBuf.data;
        rustRetBufferPtrs.add(prefixFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $prefixFromBytesCode');
      }
      (argBuf + 3).ref.u64 = prefixRustBuffer.capacity;
      (argBuf + 4).ref.u64 = prefixRustBuffer.len;
      (argBuf + 5).ref.ptr = prefixRustBuffer.data.cast<ffi.Void>();
      _methodstateAsyncLabelFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer async start failed with status $statusCode');
      }
      final int futureHandle = (returnBuf + 0).ref.u64;
      final StreamController<int> pollEvents = StreamController<int>.broadcast();
      final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
        pollEvents.add(pollResult);
      });
      try {
        _methodstateAsyncLabelFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
        while (true) {
          final int pollResult = await pollEvents.stream.first;
          if (pollResult == _rustFuturePollReady) {
            break;
          }
          if (pollResult == _rustFuturePollWake) {
            _methodstateAsyncLabelFfiBufferRustFuturePoll(futureHandle, callback.nativeFunction, 0);
            continue;
          }
          throw StateError('Rust future poll returned invalid status for methodstate_async_label: $pollResult');
        }
        final ffi.Pointer<_UniFfiRustCallStatus> outStatusPtr = calloc<_UniFfiRustCallStatus>();
        outStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        outStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        try {
          final _UniFfiRustBuffer resultValue = _methodstateAsyncLabelFfiBufferRustFutureComplete(futureHandle, outStatusPtr);
          final int completeStatusCode = outStatusPtr.ref.code;
          if (completeStatusCode == _uniFfiRustCallStatusSuccess) {
            final ffi.Pointer<_UniFfiRustBuffer> resultBufPtr = calloc<_UniFfiRustBuffer>();
            resultBufPtr.ref
              ..capacity = resultValue.capacity
              ..len = resultValue.len
              ..data = resultValue.data;
            rustRetBufferPtrs.add(resultBufPtr);
            final Uint8List resultBytes = resultBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(resultBufPtr.ref.data.asTypedList(resultBufPtr.ref.len));
            return utf8.decode(resultBytes);
          }
          if (completeStatusCode == _uniFfiRustCallStatusCancelled) {
            throw StateError('Rust future was cancelled for methodstate_async_label');
          }
          final _UniFfiRustBuffer errorBuf = outStatusPtr.ref.errorBuf;
          if (!(errorBuf.data == ffi.nullptr && errorBuf.len == 0 && errorBuf.capacity == 0)) {
            final ffi.Pointer<_UniFfiRustBuffer> errorBufPtr = calloc<_UniFfiRustBuffer>();
            errorBufPtr.ref
              ..capacity = errorBuf.capacity
              ..len = errorBuf.len
              ..data = errorBuf.data;
            rustRetBufferPtrs.add(errorBufPtr);
            final Uint8List errorBytes = errorBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errorBufPtr.ref.data.asTypedList(errorBufPtr.ref.len));
            if (errorBytes.isNotEmpty) {
              throw StateError(utf8.decode(errorBytes, allowMalformed: true));
            }
          }
          throw StateError('Rust future failed for methodstate_async_label with status code: $completeStatusCode');
        } finally {
          calloc.free(outStatusPtr);
        }
      } catch (_) {
        _methodstateAsyncLabelFfiBufferRustFutureCancel(futureHandle);
        rethrow;
      } finally {
        await pollEvents.close();
        callback.close();
        _methodstateAsyncLabelFfiBufferRustFutureFree(futureHandle);
      }
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodstateCheckedCodeFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodstate_checked_code');

  int methodstateCheckedCode(MethodState self, bool allowBusy) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(4);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodState(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      (argBuf + 3).ref.i8 = allowBusy ? 1 : 0;
      _methodstateCheckedCodeFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        if (statusCode == _uniFfiRustCallStatusError) {
          final Uint8List errBytes = errBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(errBufPtr.ref.data.asTypedList(errBufPtr.ref.len));
          throw _uniffiLiftMethodErrorException(errBytes);
        }
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return (returnBuf + 0).ref.u32;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodstateToOutcomeFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodstate_to_outcome');

  MethodOutcome methodstateToOutcome(MethodState self) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(7);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodState(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      _methodstateToOutcomeFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 3).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 4).ref.u64
          ..len = (returnBuf + 5).ref.u64
          ..data = (returnBuf + 6).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      final ffi.Pointer<_UniFfiRustBuffer> retBufPtr = calloc<_UniFfiRustBuffer>();
      retBufPtr.ref
        ..capacity = (returnBuf + 0).ref.u64
        ..len = (returnBuf + 1).ref.u64
        ..data = (returnBuf + 2).ref.ptr.cast<ffi.Uint8>();
      rustRetBufferPtrs.add(retBufPtr);
      final Uint8List retBytes = retBufPtr.ref.len == 0 ? Uint8List(0) : Uint8List.fromList(retBufPtr.ref.data.asTypedList(retBufPtr.ref.len));
      final decodedValue = _uniffiDecodeMethodOutcome(retBytes);
      return decodedValue;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }

  late final void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr) _methodstateWeightFfiBuffer = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr), void Function(ffi.Pointer<_UniFfiFfiBufferElement> argPtr, ffi.Pointer<_UniFfiFfiBufferElement> returnPtr)>('uniffi_ffibuffer_uniffi_record_enum_methods_fn_method_methodstate_weight');

  int methodstateWeight(MethodState self) {
    final ffi.Pointer<_UniFfiFfiBufferElement> argBuf = calloc<_UniFfiFfiBufferElement>(3);
    final ffi.Pointer<_UniFfiFfiBufferElement> returnBuf = calloc<_UniFfiFfiBufferElement>(5);
    final foreignArgPtrs = <ffi.Pointer<ffi.Uint8>>[];
    final rustRetBufferPtrs = <ffi.Pointer<_UniFfiRustBuffer>>[];
    try {
      final Uint8List selfBytes = _uniffiEncodeMethodState(self);
      final ffi.Pointer<ffi.Uint8> selfPtr = selfBytes.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(selfBytes.length);
      if (selfBytes.isNotEmpty) { selfPtr.asTypedList(selfBytes.length).setAll(0, selfBytes); }
      foreignArgPtrs.add(selfPtr);
      final ffi.Pointer<_UniFfiRustCallStatus> selfFromBytesStatusPtr = calloc<_UniFfiRustCallStatus>();
      selfFromBytesStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
      selfFromBytesStatusPtr.ref.errorBuf
        ..capacity = 0
        ..len = 0
        ..data = ffi.nullptr;
      final ffi.Pointer<_UniFfiForeignBytes> selfForeignPtr = calloc<_UniFfiForeignBytes>();
      selfForeignPtr.ref
        ..len = selfBytes.length
        ..data = selfPtr;
      final _UniFfiRustBuffer selfRustBuffer = _uniFfiRustBufferFromBytes(selfForeignPtr.ref, selfFromBytesStatusPtr);
      calloc.free(selfForeignPtr);
      final int selfFromBytesCode = selfFromBytesStatusPtr.ref.code;
      final _UniFfiRustBuffer selfFromBytesErrBuf = selfFromBytesStatusPtr.ref.errorBuf;
      calloc.free(selfFromBytesStatusPtr);
      if (selfFromBytesCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> selfFromBytesErrBufPtr = calloc<_UniFfiRustBuffer>();
        selfFromBytesErrBufPtr.ref
          ..capacity = selfFromBytesErrBuf.capacity
          ..len = selfFromBytesErrBuf.len
          ..data = selfFromBytesErrBuf.data;
        rustRetBufferPtrs.add(selfFromBytesErrBufPtr);
        throw StateError('UniFFI rustbuffer_from_bytes failed with status $selfFromBytesCode');
      }
      (argBuf + 0).ref.u64 = selfRustBuffer.capacity;
      (argBuf + 1).ref.u64 = selfRustBuffer.len;
      (argBuf + 2).ref.ptr = selfRustBuffer.data.cast<ffi.Void>();
      _methodstateWeightFfiBuffer(argBuf, returnBuf);
      final int statusCode = (returnBuf + 1).ref.i8;
      if (statusCode != _uniFfiRustCallStatusSuccess) {
        final ffi.Pointer<_UniFfiRustBuffer> errBufPtr = calloc<_UniFfiRustBuffer>();
        errBufPtr.ref
          ..capacity = (returnBuf + 2).ref.u64
          ..len = (returnBuf + 3).ref.u64
          ..data = (returnBuf + 4).ref.ptr.cast<ffi.Uint8>();
        rustRetBufferPtrs.add(errBufPtr);
        throw StateError('UniFFI ffibuffer call failed with status $statusCode');
      }
      return (returnBuf + 0).ref.u32;
    } finally {
      for (final ptr in foreignArgPtrs) {
        if (ptr != ffi.nullptr) {
          calloc.free(ptr);
        }
      }
      for (final bufPtr in rustRetBufferPtrs) {
        if (bufPtr.ref.data == ffi.nullptr && bufPtr.ref.len == 0 && bufPtr.ref.capacity == 0) {
          continue;
        }
        final ffi.Pointer<_UniFfiRustCallStatus> freeStatusPtr = calloc<_UniFfiRustCallStatus>();
        freeStatusPtr.ref.code = _uniFfiRustCallStatusSuccess;
        freeStatusPtr.ref.errorBuf
          ..capacity = 0
          ..len = 0
          ..data = ffi.nullptr;
        _uniFfiRustBufferFree(bufPtr.ref, freeStatusPtr);
        calloc.free(freeStatusPtr);
        calloc.free(bufPtr);
      }
      calloc.free(argBuf);
      calloc.free(returnBuf);
    }
  }
}

RecordEnumMethodsFfi? _defaultBindings;

RecordEnumMethodsFfi _bindings() => _defaultBindings ??= RecordEnumMethodsFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = RecordEnumMethodsFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

MethodOutcome methodOutcomeOk(int value) {
  return _bindings().methodOutcomeOk(value);
}

MethodPoint methodPointNew(int x, int y) {
  return _bindings().methodPointNew(x, y);
}

MethodState methodStateBusy() {
  return _bindings().methodStateBusy();
}

