// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unnecessary_non_null_assertion
library forward_refs_demo;

import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

class ForwardRefsDemoFfi {
  ForwardRefsDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_forward_refs_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final int Function() _createNodeA = _lib.lookupFunction<ffi.Uint64 Function(), int Function()>('create_node_a');

  NodeA createNodeA() {
      return NodeA._(this, _createNodeA());
  }

  late final void Function(int handle) _nodeAFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('nodea_free');

  late final int Function(int handle) _nodeAGetPartner = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle), int Function(int handle)>('nodea_get_partner');

  NodeB? nodeAInvokeGetPartner(int handle) {
    final int resultHandle = _nodeAGetPartner(handle);
    if (resultHandle == 0) {
      return null;
    }
    return NodeB._(_bindings(), resultHandle);
  }

  late final void Function(int handle) _nodeBFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('nodeb_free');

  late final int Function(int handle) _nodeBGetPartner = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle), int Function(int handle)>('nodeb_get_partner');

  NodeA? nodeBInvokeGetPartner(int handle) {
    final int resultHandle = _nodeBGetPartner(handle);
    if (resultHandle == 0) {
      return null;
    }
    return NodeA._(_bindings(), resultHandle);
  }
}

final class _NodeAFinalizerToken {
  const _NodeAFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class NodeA {
  NodeA._(this._ffi, this._handle) {
    _finalizer.attach(this, _NodeAFinalizerToken(_ffi._nodeAFree, _handle), detach: this);
  }

  final ForwardRefsDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_NodeAFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._nodeAFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('NodeA is closed');
    }
  }

  NodeB? getPartner() {
    _ensureOpen();
    return _ffi.nodeAInvokeGetPartner(_handle);
  }

}

final class NodeAFfiCodec {
  const NodeAFfiCodec._();

  static int lower(NodeA value) => value._handle;

  static NodeA lift(int handle) => NodeA._(_bindings(), handle);
}

final class _NodeBFinalizerToken {
  const _NodeBFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class NodeB {
  NodeB._(this._ffi, this._handle) {
    _finalizer.attach(this, _NodeBFinalizerToken(_ffi._nodeBFree, _handle), detach: this);
  }

  final ForwardRefsDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_NodeBFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._nodeBFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('NodeB is closed');
    }
  }

  NodeA? getPartner() {
    _ensureOpen();
    return _ffi.nodeBInvokeGetPartner(_handle);
  }

}

final class NodeBFfiCodec {
  const NodeBFfiCodec._();

  static int lower(NodeB value) => value._handle;

  static NodeB lift(int handle) => NodeB._(_bindings(), handle);
}

ForwardRefsDemoFfi? _defaultBindings;

ForwardRefsDemoFfi _bindings() => _defaultBindings ??= ForwardRefsDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = ForwardRefsDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

NodeA createNodeA() {
  return _bindings().createNodeA();
}

