// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unused_field, unnecessary_non_null_assertion
/// Namespace docs.
library docstrings_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

/// 2D point value.
class Point {
  const Point({
    /// Horizontal position.
    required this.x,
    /// Vertical position.
    required this.y,
  });

  /// Horizontal position.
  final int x;
  /// Vertical position.
  final int y;

  Map<String, dynamic> toJson() {
    return {
      'x': this.x,
      'y': this.y,
    };
  }

  factory Point.fromJson(Map<String, dynamic> json) {
    return Point(
      x: (json['x'] as num).toInt(),
      y: (json['y'] as num).toInt(),
    );
  }

  Point copyWith({
    int? x,
    int? y,
  }) {
    return Point(
      x: x ?? this.x,
      y: y ?? this.y,
    );
  }

  @override
  String toString() {
    return 'Point(x: $x, y: $y)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point && x == other.x && y == other.y;

  @override
  int get hashCode => Object.hash(x, y);
}

/// Mood state.
enum Mood {
  /// Positive.
  happy,
  /// Negative.
  sad,
}

String _encodeMood(Mood value) {
  return switch (value) {
    Mood.happy => 'happy',
    Mood.sad => 'sad',
  };
}

Mood _decodeMood(String raw) {
  return switch (raw) {
    'happy' => Mood.happy,
    'sad' => Mood.sad,
    _ => throw StateError('Unknown Mood variant: $raw'),
  };
}

final class MoodFfiCodec {
  const MoodFfiCodec._();

  static String encode(Mood value) => _encodeMood(value);

  static Mood decode(String raw) => _decodeMood(raw);
}

/// Callback reporter.
abstract interface class Reporter {
  /// Reports a message.
  void report(String message);
}

class DocstringsDemoFfi {
  DocstringsDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_docstrings_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final int Function(int left, int right) _addValues = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint32 left, ffi.Uint32 right), int Function(int left, int right)>('add_values');

  int addValues(int left, int right) {
      return _addValues(left, right);
  }

  late final void Function(int handle) _counterFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('counter_free');

  late final int Function() _counterCtorNew = _lib.lookupFunction<ffi.Uint64 Function(), int Function()>('counter_new');

  Counter counterCreateNew() {
    final int handle = _counterCtorNew();
    return Counter._(this, handle);
  }

  late final int Function(int handle) _counterCurrentValue = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint64 handle), int Function(int handle)>('counter_current_value');

  int counterInvokeCurrentValue(int handle) {
    return _counterCurrentValue(handle);
  }
}

final class _CounterFinalizerToken {
  const _CounterFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

/// Counter docs.
final class Counter {
  Counter._(this._ffi, this._handle) {
    _finalizer.attach(this, _CounterFinalizerToken(_ffi._counterFree, _handle), detach: this);
  }

  final DocstringsDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_CounterFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._counterFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('Counter is closed');
    }
  }

  /// Creates a counter.
  static Counter create() {
    return _bindings().counterCreateNew();
  }

  /// Returns current value.
  int currentValue() {
    _ensureOpen();
    return _ffi.counterInvokeCurrentValue(_handle);
  }

}

final class CounterFfiCodec {
  const CounterFfiCodec._();

  static int lower(Counter value) => value._handle;

  static Counter lift(int handle) => Counter._(_bindings(), handle);
}

DocstringsDemoFfi? _defaultBindings;

DocstringsDemoFfi _bindings() => _defaultBindings ??= DocstringsDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = DocstringsDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

/// Adds two values.
int addValues(int left, int right) {
  return _bindings().addValues(left, right);
}

