// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unnecessary_non_null_assertion
library trait_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

final class _RustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external ffi.Pointer<Utf8> errorBuf;
}

const int _rustCallStatusSuccess = 0;
const int _rustCallStatusError = 1;
const int _rustCallStatusUnexpectedError = 2;
const int _rustCallStatusCancelled = 3;
class TraitRecord {
  const TraitRecord({
    required this.name,
    required this.value,
  });

  final String name;
  final int value;

  Map<String, dynamic> toJson() {
    return {
      'name': this.name,
      'value': this.value,
    };
  }

  static TraitRecord fromJson(Map<String, dynamic> json) {
    return TraitRecord(
      name: json['name'] as String,
      value: (json['value'] as num).toInt(),
    );
  }

  TraitRecord copyWith({
    String? name,
    int? value,
  }) {
    return TraitRecord(
      name: name ?? this.name,
      value: value ?? this.value,
    );
  }

  @override
  String toString() {
    return 'TraitRecord(name: $name, value: $value)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TraitRecord && name == other.name && value == other.value;

  @override
  int get hashCode => Object.hash(name, value);
}

enum TraitColor {
  red,
  green,
  blue,
}

sealed class TraitShape {
  const TraitShape();
}

final class TraitShapeCircle extends TraitShape {
  const TraitShapeCircle({
    required this.radius,
  });
  final double radius;

  @override
  String toString() {
    return 'TraitShapeCircle(radius: $radius)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TraitShapeCircle && radius == other.radius;

  @override
  int get hashCode => Object.hash(radius);
}

final class TraitShapeRectangle extends TraitShape {
  const TraitShapeRectangle({
    required this.width,
    required this.height,
  });
  final double width;
  final double height;

  @override
  String toString() {
    return 'TraitShapeRectangle(width: $width, height: $height)';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TraitShapeRectangle && width == other.width && height == other.height;

  @override
  int get hashCode => Object.hash(width, height);
}

String _encodeTraitColor(TraitColor value) {
  return switch (value) {
    TraitColor.red => 'red',
    TraitColor.green => 'green',
    TraitColor.blue => 'blue',
  };
}

TraitColor _decodeTraitColor(String raw) {
  switch (raw) {
    case 'red':
      return TraitColor.red;
    case 'green':
      return TraitColor.green;
    case 'blue':
      return TraitColor.blue;
    default:
      throw StateError('Unknown TraitColor variant: $raw');
  }
}

String _encodeTraitShape(TraitShape value) {
  if (value is TraitShapeCircle) {
    return jsonEncode({
      'tag': 'circle',
      'radius': value.radius,
    });
  }
  if (value is TraitShapeRectangle) {
    return jsonEncode({
      'tag': 'rectangle',
      'width': value.width,
      'height': value.height,
    });
  }
  throw StateError('Unknown TraitShape variant instance: $value');
}

TraitShape _decodeTraitShape(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'circle':
      return TraitShapeCircle(
        radius: (map['radius'] as num).toDouble(),
      );
    case 'rectangle':
      return TraitShapeRectangle(
        width: (map['width'] as num).toDouble(),
        height: (map['height'] as num).toDouble(),
      );
    default:
      throw StateError('Unknown TraitShape variant tag: $tag');
  }
}

final class TraitColorFfiCodec {
  const TraitColorFfiCodec._();

  static String encode(TraitColor value) => _encodeTraitColor(value);

  static TraitColor decode(String raw) => _decodeTraitColor(raw);
}

final class TraitShapeFfiCodec {
  const TraitShapeFfiCodec._();

  static String encode(TraitShape value) => _encodeTraitShape(value);

  static TraitShape decode(String raw) => _decodeTraitShape(raw);
}

class TraitDemoFfi {
  TraitDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_trait_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final void Function(ffi.Pointer<_GreeterTraitVTable>) _greeterTraitCallbackInit = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_GreeterTraitVTable>), void Function(ffi.Pointer<_GreeterTraitVTable>)>('greeter_trait_callback_init');
  late final ffi.Pointer<_GreeterTraitVTable> _greeterTraitCallbackVTable = _GreeterTraitCallbackBridge.createVTable();
  late final bool _greeterTraitCallbackInitDone = (() {
    _greeterTraitCallbackInit(_greeterTraitCallbackVTable);
    return true;
  })();

  late final int Function() _getDefaultGreeter = _lib.lookupFunction<ffi.Uint64 Function(), int Function()>('get_default_greeter');

  Greeter getDefaultGreeter() {
      return _GreeterImpl._(this, _getDefaultGreeter());
  }

  late final ffi.Pointer<Utf8> Function(int greeter, ffi.Pointer<Utf8> name) _useGreeter = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 greeter, ffi.Pointer<Utf8> name), ffi.Pointer<Utf8> Function(int greeter, ffi.Pointer<Utf8> name)>('use_greeter');

  String useGreeter(Greeter greeter, String name) {
    final int greeterHandle = GreeterFfiCodec.lower(greeter);
    final ffi.Pointer<Utf8> nameNative = name.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _useGreeter(greeterHandle, nameNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for use_greeter');
      }
      try {
        return resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    calloc.free(nameNative);
    }
  }

  late final void Function(int handle) _greeterFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('greeter_free');

  late final ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<Utf8> name) _greeterGreet = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Pointer<Utf8> name), ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<Utf8> name)>('greeter_greet');

  String greeterInvokeGreet(int handle, String name) {
    final ffi.Pointer<Utf8> nameNative = name.toNativeUtf8();
    try {
    final ffi.Pointer<Utf8> resultPtr = _greeterGreet(handle, nameNative);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for greeter_greet');
    }
    try {
      return resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
    } finally {
    calloc.free(nameNative);
    }
  }
}

/// A trait that can be implemented in either Rust or Dart.
abstract interface class Greeter {
  /// Produce a greeting for the given name.
  String greet(String name);
}

final class _GreeterFinalizerToken {
  const _GreeterFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class _GreeterImpl implements Greeter {
  _GreeterImpl._(this._ffi, this._handle) {
    _finalizer.attach(this, _GreeterFinalizerToken(_ffi._greeterFree, _handle), detach: this);
  }

  final TraitDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_GreeterFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._greeterFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('_GreeterImpl is closed');
    }
  }

  /// Produce a greeting for the given name.
  @override
  String greet(String name) {
    _ensureOpen();
    return _ffi.greeterInvokeGreet(_handle, name);
  }

}

final class _GreeterTraitVTable extends ffi.Struct {
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle)>> uniffiFree;

  external ffi.Pointer<ffi.NativeFunction<ffi.Uint64 Function(ffi.Uint64 handle)>> uniffiClone;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> name, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>> greet;

}

final class _GreeterTraitCallbackBridge {
  _GreeterTraitCallbackBridge._();
  static final _GreeterTraitCallbackBridge instance = _GreeterTraitCallbackBridge._();

  final Map<int, Greeter> _callbacks = <int, Greeter>{};
  final Map<int, int> _refCounts = <int, int>{};
  int _nextHandle = 1;

  int register(Greeter callback) {
    final int handle = _nextHandle;
    _nextHandle += 2;
    _callbacks[handle] = callback;
    _refCounts[handle] = 1;
    return handle;
  }

  void release(int handle) {
    final int? refs = _refCounts[handle];
    if (refs == null) {
      return;
    }
    if (refs <= 1) {
      _refCounts.remove(handle);
      _callbacks.remove(handle);
      return;
    }
    _refCounts[handle] = refs - 1;
  }

  int cloneHandle(int handle) {
    final int? refs = _refCounts[handle];
    if (refs == null) {
      throw StateError('Invalid callback handle: $handle');
    }
    _refCounts[handle] = refs + 1;
    return handle;
  }

  Greeter? lookup(int handle) => _callbacks[handle];

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)> _freeNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    instance.release(handle);
  });

  static final ffi.NativeCallable<ffi.Uint64 Function(ffi.Uint64 handle)> _cloneNative = ffi.NativeCallable<ffi.Uint64 Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    return instance.cloneHandle(handle);
  }, exceptionalReturn: 0);

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> name, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)> _greetNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> name, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus)>.isolateLocal((int handle, ffi.Pointer<Utf8> name, ffi.Pointer<ffi.Pointer<Utf8>> outReturn, ffi.Pointer<_RustCallStatus> outStatus) {
    final Greeter? callback = instance.lookup(handle);
    if (callback == null) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      return;
    }
    try {
      final result = callback.greet(name == ffi.nullptr ? (throw StateError('Rust passed null string callback arg')) : name.toDartString());
      outReturn.value = result.toNativeUtf8();
      outStatus.ref
        ..code = _rustCallStatusSuccess
        ..errorBuf = ffi.nullptr;
    } catch (err) {
      outStatus.ref
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = err.toString().toNativeUtf8();
    }
  });

  static ffi.Pointer<_GreeterTraitVTable> createVTable() {
    final ffi.Pointer<_GreeterTraitVTable> vtablePtr = calloc<_GreeterTraitVTable>();
    vtablePtr.ref
      ..uniffiFree = _freeNative.nativeFunction
      ..uniffiClone = _cloneNative.nativeFunction
      ..greet = _greetNative.nativeFunction
    ;
    return vtablePtr;
  }
}

final class GreeterFfiCodec {
  const GreeterFfiCodec._();

  static int lower(Greeter value) {
    if (value is _GreeterImpl) {
      return value._handle;
    }
    _bindings()._greeterTraitCallbackInitDone;
    return _GreeterTraitCallbackBridge.instance.register(value);
  }

  static Greeter lift(int handle) => _GreeterImpl._(_bindings(), handle);
}

TraitDemoFfi? _defaultBindings;

TraitDemoFfi _bindings() => _defaultBindings ??= TraitDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = TraitDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

/// Get a Rust-implemented greeter.
Greeter getDefaultGreeter() {
  return _bindings().getDefaultGreeter();
}

/// Use a greeter to greet someone.
String useGreeter(Greeter greeter, String name) {
  return _bindings().useGreeter(greeter, name);
}

