// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unnecessary_non_null_assertion
library keywords_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

class Break {
  const Break({
    required this.class_,
    required this.return_,
    required this.is_,
  });

  final String class_;
  final int return_;
  final bool is_;

  Map<String, dynamic> toJson() {
    return {
      'class_': this.class_,
      'return_': this.return_,
      'is_': this.is_,
    };
  }

  static Break fromJson(Map<String, dynamic> json) {
    return Break(
      class_: json['class_'] as String,
      return_: (json['return_'] as num).toInt(),
      is_: json['is_'] as bool,
    );
  }

  Break copyWith({
    String? class_,
    int? return_,
    bool? is_,
  }) {
    return Break(
      class_: class_ ?? this.class_,
      return_: return_ ?? this.return_,
      is_: is_ ?? this.is_,
    );
  }
}

enum Async {
  void_,
  yield_,
  await_,
}

sealed class Throw {
  const Throw();
}

final class ThrowCatch extends Throw {
  const ThrowCatch();
}

final class ThrowRethrow extends Throw {
  const ThrowRethrow();
}

sealed class ThrowException implements Exception {
  const ThrowException();
}

final class ThrowExceptionCatch extends ThrowException {
  const ThrowExceptionCatch();
}

final class ThrowExceptionRethrow extends ThrowException {
  const ThrowExceptionRethrow();
}

String _encodeAsync(Async value) {
  return switch (value) {
    Async.void_ => 'void_',
    Async.yield_ => 'yield_',
    Async.await_ => 'await_',
  };
}

Async _decodeAsync(String raw) {
  switch (raw) {
    case 'void_':
      return Async.void_;
    case 'yield_':
      return Async.yield_;
    case 'await_':
      return Async.await_;
    default:
      throw StateError('Unknown Async variant: $raw');
  }
}

String _encodeThrow(Throw value) {
  if (value is ThrowCatch) {
    return jsonEncode({
      'tag': 'catch_',
    });
  }
  if (value is ThrowRethrow) {
    return jsonEncode({
      'tag': 'rethrow_',
    });
  }
  throw StateError('Unknown Throw variant instance: $value');
}

Throw _decodeThrow(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'catch_':
      return ThrowCatch(
      );
    case 'rethrow_':
      return ThrowRethrow(
      );
    default:
      throw StateError('Unknown Throw variant tag: $tag');
  }
}

String _encodeThrowException(ThrowException value) {
  if (value is ThrowExceptionCatch) {
    return jsonEncode({
      'tag': 'catch_',
    });
  }
  if (value is ThrowExceptionRethrow) {
    return jsonEncode({
      'tag': 'rethrow_',
    });
  }
  throw StateError('Unknown ThrowException exception instance: $value');
}

ThrowException _decodeThrowException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'catch_':
      return const ThrowExceptionCatch();
    case 'rethrow_':
      return const ThrowExceptionRethrow();
    default:
      throw StateError('Unknown ThrowException exception tag: $tag');
  }
}

final class AsyncFfiCodec {
  const AsyncFfiCodec._();

  static String encode(Async value) => _encodeAsync(value);

  static Async decode(String raw) => _decodeAsync(raw);
}

final class ThrowFfiCodec {
  const ThrowFfiCodec._();

  static String encode(Throw value) => _encodeThrow(value);

  static Throw decode(String raw) => _decodeThrow(raw);
}

final class ThrowExceptionFfiCodec {
  const ThrowExceptionFfiCodec._();

  static String encode(ThrowException value) => _encodeThrowException(value);

  static ThrowException decode(Object? raw) => _decodeThrowException(raw);
}

class KeywordsDemoFfi {
  KeywordsDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_keywords_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  void _ensureApiIntegrity(ffi.DynamicLibrary lib) {
    const int bindingsContractVersion = 30;
    final int scaffoldingContractVersion;
    try {
      final int Function() ffiContractVersion = lib.lookupFunction<ffi.Uint32 Function(), int Function()>('ffi_crate_name_uniffi_contract_version');
      scaffoldingContractVersion = ffiContractVersion();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI contract-version symbol `ffi_crate_name_uniffi_contract_version`: $err');
    }
    if (bindingsContractVersion != scaffoldingContractVersion) {
      throw StateError('UniFFI contract version mismatch: expected $bindingsContractVersion, got $scaffoldingContractVersion');
    }
    final int _checksum_uniffi_crate_name_checksum_func_class;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_class');
      _checksum_uniffi_crate_name_checksum_func_class = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_class`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_class != 18179) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_class`: expected 18179, got $_checksum_uniffi_crate_name_checksum_func_class');
    }
    final int _checksum_uniffi_crate_name_checksum_func_is;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_is');
      _checksum_uniffi_crate_name_checksum_func_is = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_is`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_is != 26495) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_is`: expected 26495, got $_checksum_uniffi_crate_name_checksum_func_is');
    }
    final int _checksum_uniffi_crate_name_checksum_func_return;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_return');
      _checksum_uniffi_crate_name_checksum_func_return = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_return`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_return != 19859) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_return`: expected 19859, got $_checksum_uniffi_crate_name_checksum_func_return');
    }
    final int _checksum_uniffi_crate_name_checksum_method_super_class;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_super_class');
      _checksum_uniffi_crate_name_checksum_method_super_class = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_super_class`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_super_class != 18661) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_super_class`: expected 18661, got $_checksum_uniffi_crate_name_checksum_method_super_class');
    }
    final int _checksum_uniffi_crate_name_checksum_method_super_return;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_super_return');
      _checksum_uniffi_crate_name_checksum_method_super_return = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_super_return`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_super_return != 18418) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_super_return`: expected 18418, got $_checksum_uniffi_crate_name_checksum_method_super_return');
    }
    final int _checksum_uniffi_crate_name_checksum_constructor_super_new;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_constructor_super_new');
      _checksum_uniffi_crate_name_checksum_constructor_super_new = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_constructor_super_new`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_constructor_super_new != 31965) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_constructor_super_new`: expected 31965, got $_checksum_uniffi_crate_name_checksum_constructor_super_new');
    }
  }

  late final ffi.DynamicLibrary _lib = (() {
    final ffi.DynamicLibrary lib = open();
    _ensureApiIntegrity(lib);
    return lib;
  })();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final int Function(int switch_) _class_ = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint32 switch_), int Function(int switch_)>('class');

  int class_(int switch_) {
      return _class_(switch_);
  }

  late final bool Function(bool sealed_) _is_ = _lib.lookupFunction<ffi.Bool Function(ffi.Bool sealed_), bool Function(bool sealed_)>('is');

  bool is_(bool sealed_) {
      return _is_(sealed_);
  }

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> var_) _return_ = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> var_), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> var_)>('return');

  String return_(String var_) {
    final ffi.Pointer<Utf8> var_Native = var_.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _return_(var_Native);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for return');
      }
      try {
        return resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    calloc.free(var_Native);
    }
  }

  late final void Function(int handle) _super_Free = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('super_free');

  late final int Function() _super_CtorNew = _lib.lookupFunction<ffi.Uint64 Function(), int Function()>('super_new');

  Super super_CreateNew() {
    final int handle = _super_CtorNew();
    return Super._(this, handle);
  }

  late final ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<Utf8> var_) _super_Class = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Pointer<Utf8> var_), ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<Utf8> var_)>('super_class');

  String super_InvokeClass(int handle, String var_) {
    final ffi.Pointer<Utf8> var_Native = var_.toNativeUtf8();
    try {
    final ffi.Pointer<Utf8> resultPtr = _super_Class(handle, var_Native);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for super_class');
    }
    try {
      return resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
    } finally {
    calloc.free(var_Native);
    }
  }

  late final int Function(int handle) _super_Return = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint64 handle), int Function(int handle)>('super_return');

  int super_InvokeReturn(int handle) {
    return _super_Return(handle);
  }
}

final class _SuperFinalizerToken {
  const _SuperFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class Super {
  Super._(this._ffi, this._handle) {
    _finalizer.attach(this, _SuperFinalizerToken(_ffi._super_Free, _handle), detach: this);
  }

  final KeywordsDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_SuperFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._super_Free(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('Super is closed');
    }
  }

  static Super create() {
    return _bindings().super_CreateNew();
  }

  String class_(String var_) {
    _ensureOpen();
    return _ffi.super_InvokeClass(_handle, var_);
  }

  int return_() {
    _ensureOpen();
    return _ffi.super_InvokeReturn(_handle);
  }

}

final class SuperFfiCodec {
  const SuperFfiCodec._();

  static int lower(Super value) => value._handle;

  static Super lift(int handle) => Super._(_bindings(), handle);
}

KeywordsDemoFfi? _defaultBindings;

KeywordsDemoFfi _bindings() => _defaultBindings ??= KeywordsDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = KeywordsDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

int class_(int switch_) {
  return _bindings().class_(switch_);
}

bool is_(bool sealed_) {
  return _bindings().is_(sealed_);
}

String return_(String var_) {
  return _bindings().return_(var_);
}

