// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unused_field, unnecessary_non_null_assertion
library error_types_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

class ErrorTypesDemoBindings {
  ErrorTypesDemoBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_error_types_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final int Function(ffi.Pointer<Utf8> message) _getError = _lib.lookupFunction<ffi.Uint64 Function(ffi.Pointer<Utf8> message), int Function(ffi.Pointer<Utf8> message)>('get_error');

  ErrorInterface getError(String message) {
    final ffi.Pointer<Utf8> messageNative = message.toNativeUtf8();
    try {
      return ErrorInterface._(this, _getError(messageNative));
    } finally {
    calloc.free(messageNative);
    }
  }

  late final ffi.Pointer<Utf8> Function() _oops = _lib.lookupFunction<ffi.Pointer<Utf8> Function(), ffi.Pointer<Utf8> Function()>('oops');

  void oops() {
      final ffi.Pointer<Utf8> resultPtr = _oops();
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for oops');
      }
      final String payload;
      try {
        payload = resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
      final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
      final Object? errRaw = envelope['err'];
      if (errRaw != null) {
        throw ErrorInterface._(this, (errRaw as num).toInt());
      }
      return;
  }

  late final void Function(int handle) _errorInterfaceFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('errorinterface_free');

  late final ffi.Pointer<Utf8> Function(int handle) _errorInterfaceChain = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('errorinterface_chain');

  List<String> errorInterfaceInvokeChain(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _errorInterfaceChain(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for errorinterface_chain');
    }
    try {
      final String payload = resultPtr.toDartString();
      return (jsonDecode(payload) as List).map((item) => item as String).toList();
    } finally {
      _rustStringFree(resultPtr);
    }
  }

  late final ffi.Pointer<Utf8> Function(int handle, int index) _errorInterfaceLink = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Uint64 index), ffi.Pointer<Utf8> Function(int handle, int index)>('errorinterface_link');

  String? errorInterfaceInvokeLink(int handle, int index) {
    final ffi.Pointer<Utf8> resultPtr = _errorInterfaceLink(handle, index);
    if (resultPtr == ffi.nullptr) {
      return null;
    }
    try {
      return resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
  }

  late final ffi.Pointer<Utf8> Function(int handle) _errorInterfaceUniffiTraitDebug = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('errorinterface_uniffi_trait_debug');

  String errorInterfaceInvokeUniffiTraitDebug(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _errorInterfaceUniffiTraitDebug(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for errorinterface_uniffi_trait_debug');
    }
    try {
      return resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
  }

  late final ffi.Pointer<Utf8> Function(int handle) _errorInterfaceUniffiTraitDisplay = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('errorinterface_uniffi_trait_display');

  String errorInterfaceInvokeUniffiTraitDisplay(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _errorInterfaceUniffiTraitDisplay(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for errorinterface_uniffi_trait_display');
    }
    try {
      return resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
  }

  late final void Function(int handle) _testInterfaceFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('testinterface_free');

  late final int Function() _testInterfaceCtorNew = _lib.lookupFunction<ffi.Uint64 Function(), int Function()>('testinterface_new');

  TestInterface testInterfaceCreateNew() {
    final int handle = _testInterfaceCtorNew();
    return TestInterface._(this, handle);
  }

  late final ffi.Pointer<Utf8> Function(int handle) _testInterfaceOops = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle), ffi.Pointer<Utf8> Function(int handle)>('testinterface_oops');

  void testInterfaceInvokeOops(int handle) {
    final ffi.Pointer<Utf8> resultPtr = _testInterfaceOops(handle);
    if (resultPtr == ffi.nullptr) {
      throw StateError('Rust returned null for testinterface_oops');
    }
    final String payload;
    try {
      payload = resultPtr.toDartString();
    } finally {
      _rustStringFree(resultPtr);
    }
    final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
    final Object? errRaw = envelope['err'];
    if (errRaw != null) {
      throw ErrorInterface._(this, (errRaw as num).toInt());
    }
    return;
  }
}

final class _ErrorInterfaceFinalizerToken {
  const _ErrorInterfaceFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class ErrorInterface implements Exception {
  ErrorInterface._(this._ffi, this._handle) {
    _finalizer.attach(this, _ErrorInterfaceFinalizerToken(_ffi._errorInterfaceFree, _handle), detach: this);
  }

  final ErrorTypesDemoBindings _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_ErrorInterfaceFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._errorInterfaceFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('ErrorInterface is closed');
    }
  }

  List<String> chain() {
    _ensureOpen();
    return _ffi.errorInterfaceInvokeChain(_handle);
  }

  String? link(int index) {
    _ensureOpen();
    return _ffi.errorInterfaceInvokeLink(_handle, index);
  }

  @override
  String toString() {
    if (_closed) {
      return 'ErrorInterface(closed)';
    }
    return _ffi.errorInterfaceInvokeUniffiTraitDisplay(_handle);
  }

}

final class ErrorInterfaceFfiCodec {
  const ErrorInterfaceFfiCodec._();

  static int lower(ErrorInterface value) => value._handle;

  static ErrorInterface lift(int handle) => ErrorInterface._(_bindings(), handle);
}

final class _TestInterfaceFinalizerToken {
  const _TestInterfaceFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class TestInterface {
  TestInterface._(this._ffi, this._handle) {
    _finalizer.attach(this, _TestInterfaceFinalizerToken(_ffi._testInterfaceFree, _handle), detach: this);
  }

  final ErrorTypesDemoBindings _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_TestInterfaceFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._testInterfaceFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('TestInterface is closed');
    }
  }

  static TestInterface create() {
    return _bindings().testInterfaceCreateNew();
  }

  void oops() {
    _ensureOpen();
    _ffi.testInterfaceInvokeOops(_handle);
  }

}

final class TestInterfaceFfiCodec {
  const TestInterfaceFfiCodec._();

  static int lower(TestInterface value) => value._handle;

  static TestInterface lift(int handle) => TestInterface._(_bindings(), handle);
}

ErrorTypesDemoBindings? _defaultBindings;

ErrorTypesDemoBindings _bindings() => _defaultBindings ??= ErrorTypesDemoBindings();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = ErrorTypesDemoBindings(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

ErrorInterface getError(String message) {
  return _bindings().getError(message);
}

void oops() {
  _bindings().oops();
}

