// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unnecessary_non_null_assertion
library callback_custom_async_demo;

import 'dart:async';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

final class _RustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external ffi.Pointer<Utf8> errorBuf;
}

const int _rustCallStatusSuccess = 0;
const int _rustCallStatusError = 1;
const int _rustCallStatusUnexpectedError = 2;
const int _rustCallStatusCancelled = 3;
const int _rustFuturePollReady = 0;
const int _rustFuturePollWake = 1;

abstract interface class Labeller {
  Future<String> labelAsync(String input);
}

final class _ForeignFutureDroppedCallbackStruct extends ffi.Struct {
  @ffi.Uint64()
  external int handle;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle)>> callback;
}

final class _LabellerLabelAsyncAsyncResult extends ffi.Struct {
  external ffi.Pointer<Utf8> returnValue;

  external _RustCallStatus callStatus;
}

final class _LabellerVTable extends ffi.Struct {
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle)>> uniffiFree;

  external ffi.Pointer<ffi.NativeFunction<ffi.Uint64 Function(ffi.Uint64 handle)>> uniffiClone;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> input, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, _LabellerLabelAsyncAsyncResult result)>> uniffiFutureCallback, ffi.Uint64 callbackData, ffi.Pointer<_ForeignFutureDroppedCallbackStruct> uniffiOutDroppedCallback)>> labelAsync;

}

final class _LabellerCallbackBridge {
  _LabellerCallbackBridge._();
  static final _LabellerCallbackBridge instance = _LabellerCallbackBridge._();

  final Map<int, Labeller> _callbacks = <int, Labeller>{};
  final Map<int, int> _refCounts = <int, int>{};
  int _nextHandle = 1;

  final Map<int, bool> _droppedFutures = <int, bool>{};
  int _nextDroppedFutureHandle = 1;

  int beginDroppedFutureTracking() {
    final int handle = _nextDroppedFutureHandle++;
    _droppedFutures[handle] = false;
    return handle;
  }

  void markDroppedFuture(int handle) {
    if (_droppedFutures.containsKey(handle)) {
      _droppedFutures[handle] = true;
    }
  }

  bool isDroppedFuture(int handle) {
    return _droppedFutures[handle] ?? true;
  }

  void finishDroppedFuture(int handle) {
    _droppedFutures.remove(handle);
  }

  int register(Labeller callback) {
    final int handle = _nextHandle++;
    _callbacks[handle] = callback;
    _refCounts[handle] = 1;
    return handle;
  }

  void release(int handle) {
    final int? refs = _refCounts[handle];
    if (refs == null) {
      return;
    }
    if (refs <= 1) {
      _refCounts.remove(handle);
      _callbacks.remove(handle);
      return;
    }
    _refCounts[handle] = refs - 1;
  }

  int cloneHandle(int handle) {
    final int? refs = _refCounts[handle];
    if (refs == null) {
      throw StateError('Invalid callback handle: $handle');
    }
    _refCounts[handle] = refs + 1;
    return handle;
  }

  Labeller? lookup(int handle) => _callbacks[handle];

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)> _freeNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    instance.release(handle);
  });

  static final ffi.NativeCallable<ffi.Uint64 Function(ffi.Uint64 handle)> _cloneNative = ffi.NativeCallable<ffi.Uint64 Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    return instance.cloneHandle(handle);
  }, exceptionalReturn: 0);

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)> _futureDroppedNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle)>.isolateLocal((int handle) {
    instance.markDroppedFuture(handle);
  });

  static final ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> input, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, _LabellerLabelAsyncAsyncResult result)>> uniffiFutureCallback, ffi.Uint64 callbackData, ffi.Pointer<_ForeignFutureDroppedCallbackStruct> uniffiOutDroppedCallback)> _labelAsyncNative = ffi.NativeCallable<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<Utf8> input, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, _LabellerLabelAsyncAsyncResult result)>> uniffiFutureCallback, ffi.Uint64 callbackData, ffi.Pointer<_ForeignFutureDroppedCallbackStruct> uniffiOutDroppedCallback)>.isolateLocal((int handle, ffi.Pointer<Utf8> input, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, _LabellerLabelAsyncAsyncResult result)>> uniffiFutureCallback, int callbackData, ffi.Pointer<_ForeignFutureDroppedCallbackStruct> uniffiOutDroppedCallback) {
    final Labeller? callback = instance.lookup(handle);
    final complete = uniffiFutureCallback.asFunction<void Function(int callbackData, _LabellerLabelAsyncAsyncResult result)>();
    final int droppedHandle = instance.beginDroppedFutureTracking();
    if (uniffiOutDroppedCallback != ffi.nullptr) {
      uniffiOutDroppedCallback.ref
        ..handle = droppedHandle
        ..callback = _futureDroppedNative.nativeFunction;
    }
    if (callback == null) {
      final ffi.Pointer<_LabellerLabelAsyncAsyncResult> resultPtr = calloc<_LabellerLabelAsyncAsyncResult>();
      resultPtr.ref.returnValue = ffi.nullptr;
      resultPtr.ref.callStatus
        ..code = _rustCallStatusUnexpectedError
        ..errorBuf = 'Invalid callback handle'.toNativeUtf8();
      final bool dropped = instance.isDroppedFuture(droppedHandle);
      if (!dropped) {
        complete(callbackData, resultPtr.ref);
      } else {
        if (resultPtr.ref.callStatus.errorBuf != ffi.nullptr) {
          calloc.free(resultPtr.ref.callStatus.errorBuf);
        }
        if (resultPtr.ref.returnValue != ffi.nullptr) {
          calloc.free(resultPtr.ref.returnValue);
        }
      }
      instance.finishDroppedFuture(droppedHandle);
      calloc.free(resultPtr);
      return;
    }
    () async {
      final ffi.Pointer<_LabellerLabelAsyncAsyncResult> resultPtr = calloc<_LabellerLabelAsyncAsyncResult>();
      resultPtr.ref.returnValue = ffi.nullptr;
      try {
        final result = await callback.labelAsync(input == ffi.nullptr ? (throw StateError('Rust passed null string callback arg')) : input.toDartString());
        resultPtr.ref.returnValue = result.toNativeUtf8();
        resultPtr.ref.callStatus
          ..code = _rustCallStatusSuccess
          ..errorBuf = ffi.nullptr;
      } catch (err) {
        resultPtr.ref.callStatus
          ..code = _rustCallStatusUnexpectedError
          ..errorBuf = err.toString().toNativeUtf8();
      } finally {
        final bool dropped = instance.isDroppedFuture(droppedHandle);
        if (!dropped) {
          complete(callbackData, resultPtr.ref);
        } else {
          if (resultPtr.ref.callStatus.errorBuf != ffi.nullptr) {
            calloc.free(resultPtr.ref.callStatus.errorBuf);
          }
          if (resultPtr.ref.returnValue != ffi.nullptr) {
            calloc.free(resultPtr.ref.returnValue);
          }
        }
        instance.finishDroppedFuture(droppedHandle);
        calloc.free(resultPtr);
      }
    }();
  });

  static ffi.Pointer<_LabellerVTable> createVTable() {
    final ffi.Pointer<_LabellerVTable> vtablePtr = calloc<_LabellerVTable>();
    vtablePtr.ref
      ..uniffiFree = _freeNative.nativeFunction
      ..uniffiClone = _cloneNative.nativeFunction
      ..labelAsync = _labelAsyncNative.nativeFunction
    ;
    return vtablePtr;
  }
}

class CallbackCustomAsyncDemoFfi {
  CallbackCustomAsyncDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_callback_custom_async_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  void _ensureApiIntegrity(ffi.DynamicLibrary lib) {
    const int bindingsContractVersion = 30;
    final int scaffoldingContractVersion;
    try {
      final int Function() ffiContractVersion = lib.lookupFunction<ffi.Uint32 Function(), int Function()>('ffi_crate_name_uniffi_contract_version');
      scaffoldingContractVersion = ffiContractVersion();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI contract-version symbol `ffi_crate_name_uniffi_contract_version`: $err');
    }
    if (bindingsContractVersion != scaffoldingContractVersion) {
      throw StateError('UniFFI contract version mismatch: expected $bindingsContractVersion, got $scaffoldingContractVersion');
    }
    final int _checksum_uniffi_crate_name_checksum_func_apply_label_async;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_apply_label_async');
      _checksum_uniffi_crate_name_checksum_func_apply_label_async = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_apply_label_async`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_apply_label_async != 40694) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_apply_label_async`: expected 40694, got $_checksum_uniffi_crate_name_checksum_func_apply_label_async');
    }
    final int _checksum_uniffi_crate_name_checksum_method_labeller_label_async;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_labeller_label_async');
      _checksum_uniffi_crate_name_checksum_method_labeller_label_async = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_labeller_label_async`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_labeller_label_async != 58825) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_labeller_label_async`: expected 58825, got $_checksum_uniffi_crate_name_checksum_method_labeller_label_async');
    }
  }

  late final ffi.DynamicLibrary _lib = (() {
    final ffi.DynamicLibrary lib = open();
    _ensureApiIntegrity(lib);
    return lib;
  })();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final void Function(ffi.Pointer<_LabellerVTable>) _labellerCallbackInit = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<_LabellerVTable>), void Function(ffi.Pointer<_LabellerVTable>)>('labeller_callback_init');
  late final ffi.Pointer<_LabellerVTable> _labellerCallbackVTable = _LabellerCallbackBridge.createVTable();
  late final bool _labellerCallbackInitDone = (() {
    _labellerCallbackInit(_labellerCallbackVTable);
    return true;
  })();

  late final int Function(int labeller, ffi.Pointer<Utf8> input) _applyLabelAsync = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 labeller, ffi.Pointer<Utf8> input), int Function(int labeller, ffi.Pointer<Utf8> input)>('apply_label_async');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _applyLabelAsyncRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('rust_future_poll_string');
  late final void Function(int handle) _applyLabelAsyncRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_cancel_string');
  late final ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<_RustCallStatus> outStatus) _applyLabelAsyncRustFutureComplete = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint64 handle, ffi.Pointer<_RustCallStatus> outStatus), ffi.Pointer<Utf8> Function(int handle, ffi.Pointer<_RustCallStatus> outStatus)>('rust_future_complete_string');
  late final void Function(int handle) _applyLabelAsyncRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_free_string');

  Future<String> applyLabelAsync(Labeller labeller, String input) async {
    _labellerCallbackInitDone;
    final int labellerHandle = _LabellerCallbackBridge.instance.register(labeller);
    final ffi.Pointer<Utf8> inputNative = input.toNativeUtf8();
    final int futureHandle;
    try {
      futureHandle = _applyLabelAsync(labellerHandle, inputNative);
    } finally {
    _LabellerCallbackBridge.instance.release(labellerHandle);
    calloc.free(inputNative);
    }
    final StreamController<int> pollEvents = StreamController<int>.broadcast();
    final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
      pollEvents.add(pollResult);
    });
    try {
      _applyLabelAsyncRustFuturePoll(futureHandle, callback.nativeFunction, 0);
      while (true) {
        final int pollResult = await pollEvents.stream.first;
        if (pollResult == _rustFuturePollReady) {
          break;
        }
        if (pollResult == _rustFuturePollWake) {
          _applyLabelAsyncRustFuturePoll(futureHandle, callback.nativeFunction, 0);
          continue;
        }
        throw StateError('Rust future poll returned invalid status for apply_label_async: $pollResult');
      }
      final ffi.Pointer<_RustCallStatus> outStatusPtr = calloc<_RustCallStatus>();
      try {
        final ffi.Pointer<Utf8> resultPtr = _applyLabelAsyncRustFutureComplete(futureHandle, outStatusPtr);
        final int statusCode = outStatusPtr.ref.code;
        if (statusCode == _rustCallStatusSuccess) {
          if (resultPtr == ffi.nullptr) {
            throw StateError('Rust returned null for apply_label_async');
          }
          try {
            return resultPtr.toDartString();
          } finally {
            _rustStringFree(resultPtr);
          }
        }
        if (statusCode == _rustCallStatusCancelled) {
          throw StateError('Rust future was cancelled for apply_label_async');
        }
        final ffi.Pointer<Utf8> errorPtr = outStatusPtr.ref.errorBuf;
        if (errorPtr != ffi.nullptr) {
          try {
            throw StateError(errorPtr.toDartString());
          } finally {
            _rustStringFree(errorPtr);
          }
        }
        throw StateError('Rust future failed for apply_label_async with status code: $statusCode');
      } finally {
        calloc.free(outStatusPtr);
      }
    } catch (_) {
      _applyLabelAsyncRustFutureCancel(futureHandle);
      rethrow;
    } finally {
      await pollEvents.close();
      callback.close();
      _applyLabelAsyncRustFutureFree(futureHandle);
    }
  }
}

CallbackCustomAsyncDemoFfi? _defaultBindings;

CallbackCustomAsyncDemoFfi _bindings() => _defaultBindings ??= CallbackCustomAsyncDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = CallbackCustomAsyncDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

Future<String> applyLabelAsync(Labeller labeller, String input) {
  return _bindings().applyLabelAsync(labeller, input);
}

