// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unnecessary_non_null_assertion
library defaults_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

class Config {
  const Config({
    required this.name,
    this.timeout = 30,
    this.verbose = false,
    this.label = null,
  });

  final String name;
  final int timeout;
  final bool verbose;
  final String? label;

  Map<String, dynamic> toJson() {
    return {
      'name': this.name,
      'timeout': this.timeout,
      'verbose': this.verbose,
      'label': this.label == null ? null : (() { final __tmp = this.label!; return __tmp; })(),
    };
  }

  static Config fromJson(Map<String, dynamic> json) {
    return Config(
      name: json['name'] as String,
      timeout: json.containsKey('timeout') ? (json['timeout'] as num).toInt() : 30,
      verbose: json.containsKey('verbose') ? json['verbose'] as bool : false,
      label: json.containsKey('label') ? json['label'] == null ? null : (() { final __tmp = json['label']; return __tmp as String; })() : null,
    );
  }

  Config copyWith({
    String? name,
    int? timeout,
    bool? verbose,
    String? label,
  }) {
    return Config(
      name: name ?? this.name,
      timeout: timeout ?? this.timeout,
      verbose: verbose ?? this.verbose,
      label: label ?? this.label,
    );
  }
}

class DefaultsDemoFfi {
  DefaultsDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_defaults_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  void _ensureApiIntegrity(ffi.DynamicLibrary lib) {
    const int bindingsContractVersion = 30;
    final int scaffoldingContractVersion;
    try {
      final int Function() ffiContractVersion = lib.lookupFunction<ffi.Uint32 Function(), int Function()>('ffi_crate_name_uniffi_contract_version');
      scaffoldingContractVersion = ffiContractVersion();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI contract-version symbol `ffi_crate_name_uniffi_contract_version`: $err');
    }
    if (bindingsContractVersion != scaffoldingContractVersion) {
      throw StateError('UniFFI contract version mismatch: expected $bindingsContractVersion, got $scaffoldingContractVersion');
    }
    final int _checksum_uniffi_crate_name_checksum_func_add_maybe;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_add_maybe');
      _checksum_uniffi_crate_name_checksum_func_add_maybe = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_add_maybe`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_add_maybe != 19295) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_add_maybe`: expected 19295, got $_checksum_uniffi_crate_name_checksum_func_add_maybe');
    }
    final int _checksum_uniffi_crate_name_checksum_func_greet;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_greet');
      _checksum_uniffi_crate_name_checksum_func_greet = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_greet`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_greet != 12006) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_greet`: expected 12006, got $_checksum_uniffi_crate_name_checksum_func_greet');
    }
  }

  late final ffi.DynamicLibrary _lib = (() {
    final ffi.DynamicLibrary lib = open();
    _ensureApiIntegrity(lib);
    return lib;
  })();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final int Function(int a, ffi.Pointer<Utf8> b) _addMaybe = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint32 a, ffi.Pointer<Utf8> b), int Function(int a, ffi.Pointer<Utf8> b)>('add_maybe');

  int addMaybe(int a, int? b) {
    final String bNativeJson = jsonEncode(b);
    final ffi.Pointer<Utf8> bNative = bNativeJson.toNativeUtf8();
    try {
      return _addMaybe(a, bNative);
    } finally {
    calloc.free(bNative);
    }
  }

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> name) _greet = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> name), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> name)>('greet');

  String greet(String? name) {
    final ffi.Pointer<Utf8> nameNative = name == null ? ffi.nullptr : name.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _greet(nameNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for greet');
      }
      try {
        return resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    if (nameNative != ffi.nullptr) calloc.free(nameNative);
    }
  }
}

DefaultsDemoFfi? _defaultBindings;

DefaultsDemoFfi _bindings() => _defaultBindings ??= DefaultsDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = DefaultsDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

int addMaybe({required int a, int? b = null}) {
  return _bindings().addMaybe(a, b);
}

String greet({String? name = null}) {
  return _bindings().greet(name);
}

