// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unused_import, unused_field, unnecessary_non_null_assertion
library rename_demo;

import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

class RenameDemoFfi {
  RenameDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_rename_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final int Function(int left, int right) _addNumbers = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint32 left, ffi.Uint32 right), int Function(int left, int right)>('add_numbers');

  int addNumbers(int left, int right) {
      return _addNumbers(left, right);
  }

  late final int Function(int value) _hiddenSum = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint32 value), int Function(int value)>('hidden_sum');

  int hiddenSum(int value) {
      return _hiddenSum(value);
  }

  late final void Function(int handle) _counterFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('counter_free');

  late final int Function(int initial) _counterCtorNew = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint32 initial), int Function(int initial)>('counter_new');

  Meter counterCreateNew(int initial) {
    final int handle = _counterCtorNew(initial);
    return Meter._(this, handle);
  }

  late final int Function(int seed) _counterCtorWithSeed = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint32 seed), int Function(int seed)>('counter_with_seed');

  Meter counterCreateWithSeed(int seed) {
    final int handle = _counterCtorWithSeed(seed);
    return Meter._(this, handle);
  }

  late final int Function(int handle) _counterCurrentValue = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint64 handle), int Function(int handle)>('counter_current_value');

  int counterInvokeCurrentValue(int handle) {
    return _counterCurrentValue(handle);
  }

  late final int Function(int handle) _counterHiddenValue = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint64 handle), int Function(int handle)>('counter_hidden_value');

  int counterInvokeHiddenValue(int handle) {
    return _counterHiddenValue(handle);
  }
}

final class _MeterFinalizerToken {
  const _MeterFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class Meter {
  Meter._(this._ffi, this._handle) {
    _finalizer.attach(this, _MeterFinalizerToken(_ffi._counterFree, _handle), detach: this);
  }

  final RenameDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_MeterFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._counterFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('Meter is closed');
    }
  }

  static Meter create(int initial) {
    return _bindings().counterCreateNew(initial);
  }

  static Meter seeded(int seed) {
    return _bindings().counterCreateWithSeed(seed);
  }

  int valueNow() {
    _ensureOpen();
    return _ffi.counterInvokeCurrentValue(_handle);
  }

}

final class CounterFfiCodec {
  const CounterFfiCodec._();

  static int lower(Meter value) => value._handle;

  static Meter lift(int handle) => Meter._(_bindings(), handle);
}

RenameDemoFfi? _defaultBindings;

RenameDemoFfi _bindings() => _defaultBindings ??= RenameDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = RenameDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

int sumValues(int left, int right) {
  return _bindings().addNumbers(left, right);
}

