// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unnecessary_non_null_assertion
library rename_demo;

import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';

class RenameDemoFfi {
  RenameDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_rename_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  void _ensureApiIntegrity(ffi.DynamicLibrary lib) {
    const int bindingsContractVersion = 30;
    final int scaffoldingContractVersion;
    try {
      final int Function() ffiContractVersion = lib.lookupFunction<ffi.Uint32 Function(), int Function()>('ffi_crate_name_uniffi_contract_version');
      scaffoldingContractVersion = ffiContractVersion();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI contract-version symbol `ffi_crate_name_uniffi_contract_version`: $err');
    }
    if (bindingsContractVersion != scaffoldingContractVersion) {
      throw StateError('UniFFI contract version mismatch: expected $bindingsContractVersion, got $scaffoldingContractVersion');
    }
    final int _checksum_uniffi_crate_name_checksum_func_add_numbers;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_add_numbers');
      _checksum_uniffi_crate_name_checksum_func_add_numbers = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_add_numbers`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_add_numbers != 46412) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_add_numbers`: expected 46412, got $_checksum_uniffi_crate_name_checksum_func_add_numbers');
    }
    final int _checksum_uniffi_crate_name_checksum_func_hidden_sum;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_func_hidden_sum');
      _checksum_uniffi_crate_name_checksum_func_hidden_sum = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_func_hidden_sum`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_func_hidden_sum != 12282) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_func_hidden_sum`: expected 12282, got $_checksum_uniffi_crate_name_checksum_func_hidden_sum');
    }
    final int _checksum_uniffi_crate_name_checksum_method_counter_current_value;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_counter_current_value');
      _checksum_uniffi_crate_name_checksum_method_counter_current_value = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_counter_current_value`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_counter_current_value != 28266) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_counter_current_value`: expected 28266, got $_checksum_uniffi_crate_name_checksum_method_counter_current_value');
    }
    final int _checksum_uniffi_crate_name_checksum_method_counter_hidden_value;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_method_counter_hidden_value');
      _checksum_uniffi_crate_name_checksum_method_counter_hidden_value = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_method_counter_hidden_value`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_method_counter_hidden_value != 19255) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_method_counter_hidden_value`: expected 19255, got $_checksum_uniffi_crate_name_checksum_method_counter_hidden_value');
    }
    final int _checksum_uniffi_crate_name_checksum_constructor_counter_new;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_constructor_counter_new');
      _checksum_uniffi_crate_name_checksum_constructor_counter_new = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_constructor_counter_new`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_constructor_counter_new != 59192) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_constructor_counter_new`: expected 59192, got $_checksum_uniffi_crate_name_checksum_constructor_counter_new');
    }
    final int _checksum_uniffi_crate_name_checksum_constructor_counter_with_seed;
    try {
      final int Function() checksumFn = lib.lookupFunction<ffi.Uint16 Function(), int Function()>('uniffi_crate_name_checksum_constructor_counter_with_seed');
      _checksum_uniffi_crate_name_checksum_constructor_counter_with_seed = checksumFn();
    } catch (err) {
      throw StateError('Missing or invalid UniFFI checksum symbol `uniffi_crate_name_checksum_constructor_counter_with_seed`: $err');
    }
    if (_checksum_uniffi_crate_name_checksum_constructor_counter_with_seed != 60338) {
      throw StateError('UniFFI API checksum mismatch for `uniffi_crate_name_checksum_constructor_counter_with_seed`: expected 60338, got $_checksum_uniffi_crate_name_checksum_constructor_counter_with_seed');
    }
  }

  late final ffi.DynamicLibrary _lib = (() {
    final ffi.DynamicLibrary lib = open();
    _ensureApiIntegrity(lib);
    return lib;
  })();

  late final int Function(int left, int right) _addNumbers = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint32 left, ffi.Uint32 right), int Function(int left, int right)>('add_numbers');

  int addNumbers(int left, int right) {
      return _addNumbers(left, right);
  }

  late final int Function(int value) _hiddenSum = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint32 value), int Function(int value)>('hidden_sum');

  int hiddenSum(int value) {
      return _hiddenSum(value);
  }

  late final void Function(int handle) _counterFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('counter_free');

  late final int Function(int initial) _counterCtorNew = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint32 initial), int Function(int initial)>('counter_new');

  Counter counterCreateNew(int initial) {
    final int handle = _counterCtorNew(initial);
    return Counter._(this, handle);
  }

  late final int Function(int seed) _counterCtorWithSeed = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint32 seed), int Function(int seed)>('counter_with_seed');

  Counter counterCreateWithSeed(int seed) {
    final int handle = _counterCtorWithSeed(seed);
    return Counter._(this, handle);
  }

  late final int Function(int handle) _counterCurrentValue = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint64 handle), int Function(int handle)>('counter_current_value');

  int counterInvokeCurrentValue(int handle) {
    return _counterCurrentValue(handle);
  }

  late final int Function(int handle) _counterHiddenValue = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint64 handle), int Function(int handle)>('counter_hidden_value');

  int counterInvokeHiddenValue(int handle) {
    return _counterHiddenValue(handle);
  }
}

final class _MeterFinalizerToken {
  const _MeterFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class Meter {
  Meter._(this._ffi, this._handle) {
    _finalizer.attach(this, _MeterFinalizerToken(_ffi._counterFree, _handle), detach: this);
  }

  final RenameDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_MeterFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._counterFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('Meter is closed');
    }
  }

  static Meter create(int initial) {
    return _bindings().counterCreateNew(initial);
  }

  static Meter seeded(int seed) {
    return _bindings().counterCreateWithSeed(seed);
  }

  int valueNow() {
    _ensureOpen();
    return _ffi.counterInvokeCurrentValue(_handle);
  }

}

final class CounterFfiCodec {
  const CounterFfiCodec._();

  static int lower(Meter value) => value._handle;

  static Meter lift(int handle) => Meter._(_bindings(), handle);
}

RenameDemoFfi? _defaultBindings;

RenameDemoFfi _bindings() => _defaultBindings ??= RenameDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = RenameDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

int sumValues(int left, int right) {
  return _bindings().addNumbers(left, right);
}

