// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unnecessary_non_null_assertion
library non_exhaustive_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;

sealed class AppError {
  const AppError();
}

final class AppErrorNotFound extends AppError {
  const AppErrorNotFound();
}

final class AppErrorPermissionDenied extends AppError {
  const AppErrorPermissionDenied();
}

/// Unknown variant for forward-compatibility with non-exhaustive enums.
final class AppErrorUnknown extends AppError {
  const AppErrorUnknown();
}

enum Status {
  active,
  inactive,
  /// Unknown variant for forward-compatibility with non-exhaustive enums.
  unknown,
}

sealed class AppErrorException implements Exception {
  const AppErrorException();
}

final class AppErrorExceptionNotFound extends AppErrorException {
  const AppErrorExceptionNotFound();
}

final class AppErrorExceptionPermissionDenied extends AppErrorException {
  const AppErrorExceptionPermissionDenied();
}

/// Unknown variant for forward-compatibility with non-exhaustive error enums.
final class AppErrorExceptionUnknown extends AppErrorException {
  const AppErrorExceptionUnknown();
}

String _encodeAppError(AppError value) {
  if (value is AppErrorNotFound) {
    return jsonEncode({
      'tag': 'notFound',
    });
  }
  if (value is AppErrorPermissionDenied) {
    return jsonEncode({
      'tag': 'permissionDenied',
    });
  }
  throw StateError('Unknown AppError variant instance: $value');
}

AppError _decodeAppError(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'notFound':
      return AppErrorNotFound(
      );
    case 'permissionDenied':
      return AppErrorPermissionDenied(
      );
    default:
      return const AppErrorUnknown();
  }
}

String _encodeStatus(Status value) {
  return switch (value) {
    Status.active => 'active',
    Status.inactive => 'inactive',
    Status.unknown => 'unknown',
  };
}

Status _decodeStatus(String raw) {
  switch (raw) {
    case 'active':
      return Status.active;
    case 'inactive':
      return Status.inactive;
    default:
      return Status.unknown;
  }
}

String _encodeAppErrorException(AppErrorException value) {
  if (value is AppErrorExceptionNotFound) {
    return jsonEncode({
      'tag': 'notFound',
    });
  }
  if (value is AppErrorExceptionPermissionDenied) {
    return jsonEncode({
      'tag': 'permissionDenied',
    });
  }
  throw StateError('Unknown AppErrorException exception instance: $value');
}

AppErrorException _decodeAppErrorException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'notFound':
      return const AppErrorExceptionNotFound();
    case 'permissionDenied':
      return const AppErrorExceptionPermissionDenied();
    default:
      return const AppErrorExceptionUnknown();
  }
}

final class AppErrorFfiCodec {
  const AppErrorFfiCodec._();

  static String encode(AppError value) => _encodeAppError(value);

  static AppError decode(String raw) => _decodeAppError(raw);
}

final class StatusFfiCodec {
  const StatusFfiCodec._();

  static String encode(Status value) => _encodeStatus(value);

  static Status decode(String raw) => _decodeStatus(raw);
}

final class AppErrorExceptionFfiCodec {
  const AppErrorExceptionFfiCodec._();

  static String encode(AppErrorException value) => _encodeAppErrorException(value);

  static AppErrorException decode(Object? raw) => _decodeAppErrorException(raw);
}

class NonExhaustiveDemoFfi {
  NonExhaustiveDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_non_exhaustive_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();
}
