// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element
library ext_types_demo;

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:other_bindings/other_bindings.dart';

final class _RustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external ffi.Pointer<Utf8> errorBuf;
}

const int _rustCallStatusSuccess = 0;
const int _rustCallStatusError = 1;
const int _rustCallStatusUnexpectedError = 2;
const int _rustCallStatusCancelled = 3;
const int _rustFuturePollReady = 0;
const int _rustFuturePollWake = 1;

class ExtTypesDemoFfi {
  ExtTypesDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_ext_types_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input) _echoRemote = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input)>('echo_remote');

  RemoteThing echoRemote(RemoteThing input) {
    final String inputNativeJson = jsonEncode(input.toJson());
    final ffi.Pointer<Utf8> inputNative = inputNativeJson.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _echoRemote(inputNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for echo_remote');
      }
      try {
        final String payload = resultPtr.toDartString();
        return RemoteThing.fromJson(jsonDecode(payload) as Map<String, dynamic>);
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    calloc.free(inputNative);
    }
  }

  late final int Function(int input) _echoRemoteCounter = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 input), int Function(int input)>('echo_remote_counter');

  RemoteCounter echoRemoteCounter(RemoteCounter input) {
    final int inputHandle = RemoteCounterFfiCodec.lower(input);
      return RemoteCounterFfiCodec.lift(_echoRemoteCounter(inputHandle));
  }

  late final int Function(int input) _echoRemoteCounterAsync = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 input), int Function(int input)>('echo_remote_counter_async');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _echoRemoteCounterAsyncRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('rust_future_poll_u64');
  late final void Function(int handle) _echoRemoteCounterAsyncRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_cancel_u64');
  late final int Function(int handle, ffi.Pointer<_RustCallStatus> outStatus) _echoRemoteCounterAsyncRustFutureComplete = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle, ffi.Pointer<_RustCallStatus> outStatus), int Function(int handle, ffi.Pointer<_RustCallStatus> outStatus)>('rust_future_complete_u64');
  late final void Function(int handle) _echoRemoteCounterAsyncRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_free_u64');

  Future<RemoteCounter> echoRemoteCounterAsync(RemoteCounter input) async {
    final int inputHandle = RemoteCounterFfiCodec.lower(input);
    final int futureHandle;
    futureHandle = _echoRemoteCounterAsync(inputHandle);
    final StreamController<int> pollEvents = StreamController<int>.broadcast();
    final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
      pollEvents.add(pollResult);
    });
    try {
      _echoRemoteCounterAsyncRustFuturePoll(futureHandle, callback.nativeFunction, 0);
      while (true) {
        final int pollResult = await pollEvents.stream.first;
        if (pollResult == _rustFuturePollReady) {
          break;
        }
        if (pollResult == _rustFuturePollWake) {
          _echoRemoteCounterAsyncRustFuturePoll(futureHandle, callback.nativeFunction, 0);
          continue;
        }
        throw StateError('Rust future poll returned invalid status for echo_remote_counter_async: $pollResult');
      }
      final ffi.Pointer<_RustCallStatus> outStatusPtr = calloc<_RustCallStatus>();
      try {
        final int resultValue = _echoRemoteCounterAsyncRustFutureComplete(futureHandle, outStatusPtr);
        final int statusCode = outStatusPtr.ref.code;
        if (statusCode == _rustCallStatusSuccess) {
          return RemoteCounterFfiCodec.lift(resultValue);
        }
        if (statusCode == _rustCallStatusCancelled) {
          throw StateError('Rust future was cancelled for echo_remote_counter_async');
        }
        final ffi.Pointer<Utf8> errorPtr = outStatusPtr.ref.errorBuf;
        if (errorPtr != ffi.nullptr) {
          try {
            throw StateError(errorPtr.toDartString());
          } finally {
            _rustStringFree(errorPtr);
          }
        }
        throw StateError('Rust future failed for echo_remote_counter_async with status code: $statusCode');
      } finally {
        calloc.free(outStatusPtr);
      }
    } catch (_) {
      _echoRemoteCounterAsyncRustFutureCancel(futureHandle);
      rethrow;
    } finally {
      await pollEvents.close();
      callback.close();
      _echoRemoteCounterAsyncRustFutureFree(futureHandle);
    }
  }

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input) _echoRemoteState = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input)>('echo_remote_state');

  RemoteState echoRemoteState(RemoteState input) {
    final String inputNativeJson = RemoteStateFfiCodec.encode(input);
    final ffi.Pointer<Utf8> inputNative = inputNativeJson.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _echoRemoteState(inputNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for echo_remote_state');
      }
      try {
        final String payload = resultPtr.toDartString();
        return RemoteStateFfiCodec.decode(payload);
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    calloc.free(inputNative);
    }
  }

  late final ffi.Pointer<Utf8> Function(int input) _riskyRemoteCount = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Int32 input), ffi.Pointer<Utf8> Function(int input)>('risky_remote_count');

  int riskyRemoteCount(int input) {
      final ffi.Pointer<Utf8> resultPtr = _riskyRemoteCount(input);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for risky_remote_count');
      }
      final String payload;
      try {
        payload = resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
      final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
      final Object? errRaw = envelope['err'];
      if (errRaw != null) {
        throw RemoteFailureExceptionFfiCodec.decode(errRaw);
      }
      if (!envelope.containsKey('ok')) {
        throw StateError('Rust returned malformed result for risky_remote_count');
      }
      final Object? okRaw = envelope['ok'];
      return (okRaw as num).toInt();
  }
}

ExtTypesDemoFfi? _defaultBindings;

ExtTypesDemoFfi _bindings() => _defaultBindings ??= ExtTypesDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = ExtTypesDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

RemoteThing echoRemote(RemoteThing input) {
  return _bindings().echoRemote(input);
}

RemoteCounter echoRemoteCounter(RemoteCounter input) {
  return _bindings().echoRemoteCounter(input);
}

Future<RemoteCounter> echoRemoteCounterAsync(RemoteCounter input) {
  return _bindings().echoRemoteCounterAsync(input);
}

RemoteState echoRemoteState(RemoteState input) {
  return _bindings().echoRemoteState(input);
}

int riskyRemoteCount(int input) {
  return _bindings().riskyRemoteCount(input);
}

