// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element
library ext_types_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:other_bindings/other_bindings.dart';

class ExtTypesDemoFfi {
  ExtTypesDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_ext_types_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input) _echoRemote = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> input)>('echo_remote');

  RemoteThing echoRemote(RemoteThing input) {
    final String inputNativeJson = jsonEncode(input.toJson());
    final ffi.Pointer<Utf8> inputNative = inputNativeJson.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _echoRemote(inputNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for echo_remote');
      }
      try {
        final String payload = resultPtr.toDartString();
        return RemoteThing.fromJson(jsonDecode(payload) as Map<String, dynamic>);
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    calloc.free(inputNative);
    }
  }
}

ExtTypesDemoFfi? _defaultBindings;

ExtTypesDemoFfi _bindings() => _defaultBindings ??= ExtTypesDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = ExtTypesDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

RemoteThing echoRemote(RemoteThing input) {
  return _bindings().echoRemote(input);
}

