// Generated by uniffi-bindgen-dart. DO NOT EDIT.
library simple_fns;

import 'dart:ffi' as ffi;

class SimpleFnsBindings {
  const SimpleFnsBindings();

  static const String libraryName = 'uniffi_simple_fns';

  ffi.DynamicLibrary open() {
    return ffi.DynamicLibrary.open(libraryName);
  }
}

int add(int left, int right) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

