// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element
library type_limits_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'dart:typed_data';

final class _RustBuffer extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Uint64()
  external int len;
}

enum LargeEnum {
  variant1,
  variant2,
  variant3,
  variant4,
  variant5,
  variant6,
  variant7,
  variant8,
  variant9,
  variant10,
  variant11,
  variant12,
  variant13,
  variant14,
  variant15,
  variant16,
  variant17,
  variant18,
  variant19,
  variant20,
  variant21,
  variant22,
  variant23,
  variant24,
  variant25,
  variant26,
  variant27,
  variant28,
  variant29,
  variant30,
  variant31,
  variant32,
  variant33,
  variant34,
  variant35,
  variant36,
  variant37,
  variant38,
  variant39,
  variant40,
  variant41,
  variant42,
  variant43,
  variant44,
  variant45,
  variant46,
  variant47,
  variant48,
  variant49,
  variant50,
}

sealed class LargeError {
  const LargeError();
}

final class LargeErrorCase1 extends LargeError {
  const LargeErrorCase1();
}

final class LargeErrorCase2 extends LargeError {
  const LargeErrorCase2();
}

final class LargeErrorCase3 extends LargeError {
  const LargeErrorCase3();
}

final class LargeErrorCase4 extends LargeError {
  const LargeErrorCase4();
}

final class LargeErrorCase5 extends LargeError {
  const LargeErrorCase5();
}

final class LargeErrorCase6 extends LargeError {
  const LargeErrorCase6();
}

final class LargeErrorCase7 extends LargeError {
  const LargeErrorCase7();
}

final class LargeErrorCase8 extends LargeError {
  const LargeErrorCase8();
}

final class LargeErrorCase9 extends LargeError {
  const LargeErrorCase9();
}

final class LargeErrorCase10 extends LargeError {
  const LargeErrorCase10();
}

final class LargeErrorCase11 extends LargeError {
  const LargeErrorCase11();
}

final class LargeErrorCase12 extends LargeError {
  const LargeErrorCase12();
}

final class LargeErrorCase13 extends LargeError {
  const LargeErrorCase13();
}

final class LargeErrorCase14 extends LargeError {
  const LargeErrorCase14();
}

final class LargeErrorCase15 extends LargeError {
  const LargeErrorCase15();
}

final class LargeErrorCase16 extends LargeError {
  const LargeErrorCase16();
}

final class LargeErrorCase17 extends LargeError {
  const LargeErrorCase17();
}

final class LargeErrorCase18 extends LargeError {
  const LargeErrorCase18();
}

final class LargeErrorCase19 extends LargeError {
  const LargeErrorCase19();
}

final class LargeErrorCase20 extends LargeError {
  const LargeErrorCase20();
}

final class LargeErrorCase21 extends LargeError {
  const LargeErrorCase21();
}

final class LargeErrorCase22 extends LargeError {
  const LargeErrorCase22();
}

final class LargeErrorCase23 extends LargeError {
  const LargeErrorCase23();
}

final class LargeErrorCase24 extends LargeError {
  const LargeErrorCase24();
}

final class LargeErrorCase25 extends LargeError {
  const LargeErrorCase25();
}

final class LargeErrorCase26 extends LargeError {
  const LargeErrorCase26();
}

final class LargeErrorCase27 extends LargeError {
  const LargeErrorCase27();
}

final class LargeErrorCase28 extends LargeError {
  const LargeErrorCase28();
}

final class LargeErrorCase29 extends LargeError {
  const LargeErrorCase29();
}

final class LargeErrorCase30 extends LargeError {
  const LargeErrorCase30();
}

sealed class LargeErrorException implements Exception {
  const LargeErrorException();
}

final class LargeErrorExceptionCase1 extends LargeErrorException {
  const LargeErrorExceptionCase1();
}

final class LargeErrorExceptionCase2 extends LargeErrorException {
  const LargeErrorExceptionCase2();
}

final class LargeErrorExceptionCase3 extends LargeErrorException {
  const LargeErrorExceptionCase3();
}

final class LargeErrorExceptionCase4 extends LargeErrorException {
  const LargeErrorExceptionCase4();
}

final class LargeErrorExceptionCase5 extends LargeErrorException {
  const LargeErrorExceptionCase5();
}

final class LargeErrorExceptionCase6 extends LargeErrorException {
  const LargeErrorExceptionCase6();
}

final class LargeErrorExceptionCase7 extends LargeErrorException {
  const LargeErrorExceptionCase7();
}

final class LargeErrorExceptionCase8 extends LargeErrorException {
  const LargeErrorExceptionCase8();
}

final class LargeErrorExceptionCase9 extends LargeErrorException {
  const LargeErrorExceptionCase9();
}

final class LargeErrorExceptionCase10 extends LargeErrorException {
  const LargeErrorExceptionCase10();
}

final class LargeErrorExceptionCase11 extends LargeErrorException {
  const LargeErrorExceptionCase11();
}

final class LargeErrorExceptionCase12 extends LargeErrorException {
  const LargeErrorExceptionCase12();
}

final class LargeErrorExceptionCase13 extends LargeErrorException {
  const LargeErrorExceptionCase13();
}

final class LargeErrorExceptionCase14 extends LargeErrorException {
  const LargeErrorExceptionCase14();
}

final class LargeErrorExceptionCase15 extends LargeErrorException {
  const LargeErrorExceptionCase15();
}

final class LargeErrorExceptionCase16 extends LargeErrorException {
  const LargeErrorExceptionCase16();
}

final class LargeErrorExceptionCase17 extends LargeErrorException {
  const LargeErrorExceptionCase17();
}

final class LargeErrorExceptionCase18 extends LargeErrorException {
  const LargeErrorExceptionCase18();
}

final class LargeErrorExceptionCase19 extends LargeErrorException {
  const LargeErrorExceptionCase19();
}

final class LargeErrorExceptionCase20 extends LargeErrorException {
  const LargeErrorExceptionCase20();
}

final class LargeErrorExceptionCase21 extends LargeErrorException {
  const LargeErrorExceptionCase21();
}

final class LargeErrorExceptionCase22 extends LargeErrorException {
  const LargeErrorExceptionCase22();
}

final class LargeErrorExceptionCase23 extends LargeErrorException {
  const LargeErrorExceptionCase23();
}

final class LargeErrorExceptionCase24 extends LargeErrorException {
  const LargeErrorExceptionCase24();
}

final class LargeErrorExceptionCase25 extends LargeErrorException {
  const LargeErrorExceptionCase25();
}

final class LargeErrorExceptionCase26 extends LargeErrorException {
  const LargeErrorExceptionCase26();
}

final class LargeErrorExceptionCase27 extends LargeErrorException {
  const LargeErrorExceptionCase27();
}

final class LargeErrorExceptionCase28 extends LargeErrorException {
  const LargeErrorExceptionCase28();
}

final class LargeErrorExceptionCase29 extends LargeErrorException {
  const LargeErrorExceptionCase29();
}

final class LargeErrorExceptionCase30 extends LargeErrorException {
  const LargeErrorExceptionCase30();
}

String _encodeLargeEnum(LargeEnum value) {
  return switch (value) {
    LargeEnum.variant1 => 'variant1',
    LargeEnum.variant2 => 'variant2',
    LargeEnum.variant3 => 'variant3',
    LargeEnum.variant4 => 'variant4',
    LargeEnum.variant5 => 'variant5',
    LargeEnum.variant6 => 'variant6',
    LargeEnum.variant7 => 'variant7',
    LargeEnum.variant8 => 'variant8',
    LargeEnum.variant9 => 'variant9',
    LargeEnum.variant10 => 'variant10',
    LargeEnum.variant11 => 'variant11',
    LargeEnum.variant12 => 'variant12',
    LargeEnum.variant13 => 'variant13',
    LargeEnum.variant14 => 'variant14',
    LargeEnum.variant15 => 'variant15',
    LargeEnum.variant16 => 'variant16',
    LargeEnum.variant17 => 'variant17',
    LargeEnum.variant18 => 'variant18',
    LargeEnum.variant19 => 'variant19',
    LargeEnum.variant20 => 'variant20',
    LargeEnum.variant21 => 'variant21',
    LargeEnum.variant22 => 'variant22',
    LargeEnum.variant23 => 'variant23',
    LargeEnum.variant24 => 'variant24',
    LargeEnum.variant25 => 'variant25',
    LargeEnum.variant26 => 'variant26',
    LargeEnum.variant27 => 'variant27',
    LargeEnum.variant28 => 'variant28',
    LargeEnum.variant29 => 'variant29',
    LargeEnum.variant30 => 'variant30',
    LargeEnum.variant31 => 'variant31',
    LargeEnum.variant32 => 'variant32',
    LargeEnum.variant33 => 'variant33',
    LargeEnum.variant34 => 'variant34',
    LargeEnum.variant35 => 'variant35',
    LargeEnum.variant36 => 'variant36',
    LargeEnum.variant37 => 'variant37',
    LargeEnum.variant38 => 'variant38',
    LargeEnum.variant39 => 'variant39',
    LargeEnum.variant40 => 'variant40',
    LargeEnum.variant41 => 'variant41',
    LargeEnum.variant42 => 'variant42',
    LargeEnum.variant43 => 'variant43',
    LargeEnum.variant44 => 'variant44',
    LargeEnum.variant45 => 'variant45',
    LargeEnum.variant46 => 'variant46',
    LargeEnum.variant47 => 'variant47',
    LargeEnum.variant48 => 'variant48',
    LargeEnum.variant49 => 'variant49',
    LargeEnum.variant50 => 'variant50',
  };
}

LargeEnum _decodeLargeEnum(String raw) {
  switch (raw) {
    case 'variant1':
      return LargeEnum.variant1;
    case 'variant2':
      return LargeEnum.variant2;
    case 'variant3':
      return LargeEnum.variant3;
    case 'variant4':
      return LargeEnum.variant4;
    case 'variant5':
      return LargeEnum.variant5;
    case 'variant6':
      return LargeEnum.variant6;
    case 'variant7':
      return LargeEnum.variant7;
    case 'variant8':
      return LargeEnum.variant8;
    case 'variant9':
      return LargeEnum.variant9;
    case 'variant10':
      return LargeEnum.variant10;
    case 'variant11':
      return LargeEnum.variant11;
    case 'variant12':
      return LargeEnum.variant12;
    case 'variant13':
      return LargeEnum.variant13;
    case 'variant14':
      return LargeEnum.variant14;
    case 'variant15':
      return LargeEnum.variant15;
    case 'variant16':
      return LargeEnum.variant16;
    case 'variant17':
      return LargeEnum.variant17;
    case 'variant18':
      return LargeEnum.variant18;
    case 'variant19':
      return LargeEnum.variant19;
    case 'variant20':
      return LargeEnum.variant20;
    case 'variant21':
      return LargeEnum.variant21;
    case 'variant22':
      return LargeEnum.variant22;
    case 'variant23':
      return LargeEnum.variant23;
    case 'variant24':
      return LargeEnum.variant24;
    case 'variant25':
      return LargeEnum.variant25;
    case 'variant26':
      return LargeEnum.variant26;
    case 'variant27':
      return LargeEnum.variant27;
    case 'variant28':
      return LargeEnum.variant28;
    case 'variant29':
      return LargeEnum.variant29;
    case 'variant30':
      return LargeEnum.variant30;
    case 'variant31':
      return LargeEnum.variant31;
    case 'variant32':
      return LargeEnum.variant32;
    case 'variant33':
      return LargeEnum.variant33;
    case 'variant34':
      return LargeEnum.variant34;
    case 'variant35':
      return LargeEnum.variant35;
    case 'variant36':
      return LargeEnum.variant36;
    case 'variant37':
      return LargeEnum.variant37;
    case 'variant38':
      return LargeEnum.variant38;
    case 'variant39':
      return LargeEnum.variant39;
    case 'variant40':
      return LargeEnum.variant40;
    case 'variant41':
      return LargeEnum.variant41;
    case 'variant42':
      return LargeEnum.variant42;
    case 'variant43':
      return LargeEnum.variant43;
    case 'variant44':
      return LargeEnum.variant44;
    case 'variant45':
      return LargeEnum.variant45;
    case 'variant46':
      return LargeEnum.variant46;
    case 'variant47':
      return LargeEnum.variant47;
    case 'variant48':
      return LargeEnum.variant48;
    case 'variant49':
      return LargeEnum.variant49;
    case 'variant50':
      return LargeEnum.variant50;
    default:
      throw StateError('Unknown LargeEnum variant: $raw');
  }
}

String _encodeLargeError(LargeError value) {
  if (value is LargeErrorCase1) {
    return jsonEncode({
      'tag': 'case1',
    });
  }
  if (value is LargeErrorCase2) {
    return jsonEncode({
      'tag': 'case2',
    });
  }
  if (value is LargeErrorCase3) {
    return jsonEncode({
      'tag': 'case3',
    });
  }
  if (value is LargeErrorCase4) {
    return jsonEncode({
      'tag': 'case4',
    });
  }
  if (value is LargeErrorCase5) {
    return jsonEncode({
      'tag': 'case5',
    });
  }
  if (value is LargeErrorCase6) {
    return jsonEncode({
      'tag': 'case6',
    });
  }
  if (value is LargeErrorCase7) {
    return jsonEncode({
      'tag': 'case7',
    });
  }
  if (value is LargeErrorCase8) {
    return jsonEncode({
      'tag': 'case8',
    });
  }
  if (value is LargeErrorCase9) {
    return jsonEncode({
      'tag': 'case9',
    });
  }
  if (value is LargeErrorCase10) {
    return jsonEncode({
      'tag': 'case10',
    });
  }
  if (value is LargeErrorCase11) {
    return jsonEncode({
      'tag': 'case11',
    });
  }
  if (value is LargeErrorCase12) {
    return jsonEncode({
      'tag': 'case12',
    });
  }
  if (value is LargeErrorCase13) {
    return jsonEncode({
      'tag': 'case13',
    });
  }
  if (value is LargeErrorCase14) {
    return jsonEncode({
      'tag': 'case14',
    });
  }
  if (value is LargeErrorCase15) {
    return jsonEncode({
      'tag': 'case15',
    });
  }
  if (value is LargeErrorCase16) {
    return jsonEncode({
      'tag': 'case16',
    });
  }
  if (value is LargeErrorCase17) {
    return jsonEncode({
      'tag': 'case17',
    });
  }
  if (value is LargeErrorCase18) {
    return jsonEncode({
      'tag': 'case18',
    });
  }
  if (value is LargeErrorCase19) {
    return jsonEncode({
      'tag': 'case19',
    });
  }
  if (value is LargeErrorCase20) {
    return jsonEncode({
      'tag': 'case20',
    });
  }
  if (value is LargeErrorCase21) {
    return jsonEncode({
      'tag': 'case21',
    });
  }
  if (value is LargeErrorCase22) {
    return jsonEncode({
      'tag': 'case22',
    });
  }
  if (value is LargeErrorCase23) {
    return jsonEncode({
      'tag': 'case23',
    });
  }
  if (value is LargeErrorCase24) {
    return jsonEncode({
      'tag': 'case24',
    });
  }
  if (value is LargeErrorCase25) {
    return jsonEncode({
      'tag': 'case25',
    });
  }
  if (value is LargeErrorCase26) {
    return jsonEncode({
      'tag': 'case26',
    });
  }
  if (value is LargeErrorCase27) {
    return jsonEncode({
      'tag': 'case27',
    });
  }
  if (value is LargeErrorCase28) {
    return jsonEncode({
      'tag': 'case28',
    });
  }
  if (value is LargeErrorCase29) {
    return jsonEncode({
      'tag': 'case29',
    });
  }
  if (value is LargeErrorCase30) {
    return jsonEncode({
      'tag': 'case30',
    });
  }
  throw StateError('Unknown LargeError variant instance: $value');
}

LargeError _decodeLargeError(String raw) {
  final Map<String, dynamic> map = jsonDecode(raw) as Map<String, dynamic>;
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'case1':
      return LargeErrorCase1(
      );
    case 'case2':
      return LargeErrorCase2(
      );
    case 'case3':
      return LargeErrorCase3(
      );
    case 'case4':
      return LargeErrorCase4(
      );
    case 'case5':
      return LargeErrorCase5(
      );
    case 'case6':
      return LargeErrorCase6(
      );
    case 'case7':
      return LargeErrorCase7(
      );
    case 'case8':
      return LargeErrorCase8(
      );
    case 'case9':
      return LargeErrorCase9(
      );
    case 'case10':
      return LargeErrorCase10(
      );
    case 'case11':
      return LargeErrorCase11(
      );
    case 'case12':
      return LargeErrorCase12(
      );
    case 'case13':
      return LargeErrorCase13(
      );
    case 'case14':
      return LargeErrorCase14(
      );
    case 'case15':
      return LargeErrorCase15(
      );
    case 'case16':
      return LargeErrorCase16(
      );
    case 'case17':
      return LargeErrorCase17(
      );
    case 'case18':
      return LargeErrorCase18(
      );
    case 'case19':
      return LargeErrorCase19(
      );
    case 'case20':
      return LargeErrorCase20(
      );
    case 'case21':
      return LargeErrorCase21(
      );
    case 'case22':
      return LargeErrorCase22(
      );
    case 'case23':
      return LargeErrorCase23(
      );
    case 'case24':
      return LargeErrorCase24(
      );
    case 'case25':
      return LargeErrorCase25(
      );
    case 'case26':
      return LargeErrorCase26(
      );
    case 'case27':
      return LargeErrorCase27(
      );
    case 'case28':
      return LargeErrorCase28(
      );
    case 'case29':
      return LargeErrorCase29(
      );
    case 'case30':
      return LargeErrorCase30(
      );
    default:
      throw StateError('Unknown LargeError variant tag: $tag');
  }
}

String _encodeLargeErrorException(LargeErrorException value) {
  if (value is LargeErrorExceptionCase1) {
    return jsonEncode({
      'tag': 'case1',
    });
  }
  if (value is LargeErrorExceptionCase2) {
    return jsonEncode({
      'tag': 'case2',
    });
  }
  if (value is LargeErrorExceptionCase3) {
    return jsonEncode({
      'tag': 'case3',
    });
  }
  if (value is LargeErrorExceptionCase4) {
    return jsonEncode({
      'tag': 'case4',
    });
  }
  if (value is LargeErrorExceptionCase5) {
    return jsonEncode({
      'tag': 'case5',
    });
  }
  if (value is LargeErrorExceptionCase6) {
    return jsonEncode({
      'tag': 'case6',
    });
  }
  if (value is LargeErrorExceptionCase7) {
    return jsonEncode({
      'tag': 'case7',
    });
  }
  if (value is LargeErrorExceptionCase8) {
    return jsonEncode({
      'tag': 'case8',
    });
  }
  if (value is LargeErrorExceptionCase9) {
    return jsonEncode({
      'tag': 'case9',
    });
  }
  if (value is LargeErrorExceptionCase10) {
    return jsonEncode({
      'tag': 'case10',
    });
  }
  if (value is LargeErrorExceptionCase11) {
    return jsonEncode({
      'tag': 'case11',
    });
  }
  if (value is LargeErrorExceptionCase12) {
    return jsonEncode({
      'tag': 'case12',
    });
  }
  if (value is LargeErrorExceptionCase13) {
    return jsonEncode({
      'tag': 'case13',
    });
  }
  if (value is LargeErrorExceptionCase14) {
    return jsonEncode({
      'tag': 'case14',
    });
  }
  if (value is LargeErrorExceptionCase15) {
    return jsonEncode({
      'tag': 'case15',
    });
  }
  if (value is LargeErrorExceptionCase16) {
    return jsonEncode({
      'tag': 'case16',
    });
  }
  if (value is LargeErrorExceptionCase17) {
    return jsonEncode({
      'tag': 'case17',
    });
  }
  if (value is LargeErrorExceptionCase18) {
    return jsonEncode({
      'tag': 'case18',
    });
  }
  if (value is LargeErrorExceptionCase19) {
    return jsonEncode({
      'tag': 'case19',
    });
  }
  if (value is LargeErrorExceptionCase20) {
    return jsonEncode({
      'tag': 'case20',
    });
  }
  if (value is LargeErrorExceptionCase21) {
    return jsonEncode({
      'tag': 'case21',
    });
  }
  if (value is LargeErrorExceptionCase22) {
    return jsonEncode({
      'tag': 'case22',
    });
  }
  if (value is LargeErrorExceptionCase23) {
    return jsonEncode({
      'tag': 'case23',
    });
  }
  if (value is LargeErrorExceptionCase24) {
    return jsonEncode({
      'tag': 'case24',
    });
  }
  if (value is LargeErrorExceptionCase25) {
    return jsonEncode({
      'tag': 'case25',
    });
  }
  if (value is LargeErrorExceptionCase26) {
    return jsonEncode({
      'tag': 'case26',
    });
  }
  if (value is LargeErrorExceptionCase27) {
    return jsonEncode({
      'tag': 'case27',
    });
  }
  if (value is LargeErrorExceptionCase28) {
    return jsonEncode({
      'tag': 'case28',
    });
  }
  if (value is LargeErrorExceptionCase29) {
    return jsonEncode({
      'tag': 'case29',
    });
  }
  if (value is LargeErrorExceptionCase30) {
    return jsonEncode({
      'tag': 'case30',
    });
  }
  throw StateError('Unknown LargeErrorException exception instance: $value');
}

LargeErrorException _decodeLargeErrorException(Object? raw) {
  final Map<String, dynamic> map = raw is String ? (jsonDecode(raw) as Map<String, dynamic>) : (raw as Map<String, dynamic>);
  final String? tag = map['tag'] as String?;
  switch (tag) {
    case 'case1':
      return const LargeErrorExceptionCase1();
    case 'case2':
      return const LargeErrorExceptionCase2();
    case 'case3':
      return const LargeErrorExceptionCase3();
    case 'case4':
      return const LargeErrorExceptionCase4();
    case 'case5':
      return const LargeErrorExceptionCase5();
    case 'case6':
      return const LargeErrorExceptionCase6();
    case 'case7':
      return const LargeErrorExceptionCase7();
    case 'case8':
      return const LargeErrorExceptionCase8();
    case 'case9':
      return const LargeErrorExceptionCase9();
    case 'case10':
      return const LargeErrorExceptionCase10();
    case 'case11':
      return const LargeErrorExceptionCase11();
    case 'case12':
      return const LargeErrorExceptionCase12();
    case 'case13':
      return const LargeErrorExceptionCase13();
    case 'case14':
      return const LargeErrorExceptionCase14();
    case 'case15':
      return const LargeErrorExceptionCase15();
    case 'case16':
      return const LargeErrorExceptionCase16();
    case 'case17':
      return const LargeErrorExceptionCase17();
    case 'case18':
      return const LargeErrorExceptionCase18();
    case 'case19':
      return const LargeErrorExceptionCase19();
    case 'case20':
      return const LargeErrorExceptionCase20();
    case 'case21':
      return const LargeErrorExceptionCase21();
    case 'case22':
      return const LargeErrorExceptionCase22();
    case 'case23':
      return const LargeErrorExceptionCase23();
    case 'case24':
      return const LargeErrorExceptionCase24();
    case 'case25':
      return const LargeErrorExceptionCase25();
    case 'case26':
      return const LargeErrorExceptionCase26();
    case 'case27':
      return const LargeErrorExceptionCase27();
    case 'case28':
      return const LargeErrorExceptionCase28();
    case 'case29':
      return const LargeErrorExceptionCase29();
    case 'case30':
      return const LargeErrorExceptionCase30();
    default:
      throw StateError('Unknown LargeErrorException exception tag: $tag');
  }
}

final class LargeEnumFfiCodec {
  const LargeEnumFfiCodec._();

  static String encode(LargeEnum value) => _encodeLargeEnum(value);

  static LargeEnum decode(String raw) => _decodeLargeEnum(raw);
}

final class LargeErrorFfiCodec {
  const LargeErrorFfiCodec._();

  static String encode(LargeError value) => _encodeLargeError(value);

  static LargeError decode(String raw) => _decodeLargeError(raw);
}

final class LargeErrorExceptionFfiCodec {
  const LargeErrorExceptionFfiCodec._();

  static String encode(LargeErrorException value) => _encodeLargeErrorException(value);

  static LargeErrorException decode(Object? raw) => _decodeLargeErrorException(raw);
}

class TypeLimitsDemoFfi {
  TypeLimitsDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_type_limits_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final void Function(_RustBuffer) _rustBytesFree = _lib.lookupFunction<ffi.Void Function(_RustBuffer), void Function(_RustBuffer)>('rust_bytes_free');

  late final ffi.Pointer<Utf8> Function(int idx) _maybeThrow = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Uint32 idx), ffi.Pointer<Utf8> Function(int idx)>('maybe_throw');

  void maybeThrow(int idx) {
      final ffi.Pointer<Utf8> resultPtr = _maybeThrow(idx);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for maybe_throw');
      }
      final String payload;
      try {
        payload = resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
      final Map<String, dynamic> envelope = jsonDecode(payload) as Map<String, dynamic>;
      final Object? errRaw = envelope['err'];
      if (errRaw != null) {
        throw LargeErrorExceptionFfiCodec.decode(errRaw);
      }
      return;
  }

  late final _RustBuffer Function(_RustBuffer v) _takeBytes = _lib.lookupFunction<_RustBuffer Function(_RustBuffer v), _RustBuffer Function(_RustBuffer v)>('take_bytes');

  Uint8List takeBytes(Uint8List v) {
    final ffi.Pointer<ffi.Uint8> vData = v.isEmpty ? ffi.nullptr : calloc<ffi.Uint8>(v.length);
    if (vData != ffi.nullptr) {
      vData.asTypedList(v.length).setAll(0, v);
    }
    final ffi.Pointer<_RustBuffer> vBufferPtr = calloc<_RustBuffer>();
    vBufferPtr.ref.data = vData;
    vBufferPtr.ref.len = v.length;
    final _RustBuffer vNative = vBufferPtr.ref;
    try {
      final _RustBuffer resultBuf = _takeBytes(vNative);
      final ffi.Pointer<ffi.Uint8> resultData = resultBuf.data;
      final int resultLen = resultBuf.len;
      if (resultData == ffi.nullptr) {
        if (resultLen == 0) {
          _rustBytesFree(resultBuf);
          return Uint8List(0);
        }
        throw StateError('Rust returned invalid buffer for take_bytes');
      }
      try {
        return Uint8List.fromList(resultData.asTypedList(resultLen));
      } finally {
        _rustBytesFree(resultBuf);
      }
    } finally {
    if (vData != ffi.nullptr) calloc.free(vData);
    calloc.free(vBufferPtr);
    }
  }

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> v) _takeEnum = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> v), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> v)>('take_enum');

  LargeEnum takeEnum(LargeEnum v) {
    final String vNativeJson = LargeEnumFfiCodec.encode(v);
    final ffi.Pointer<Utf8> vNative = vNativeJson.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _takeEnum(vNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for take_enum');
      }
      try {
        final String payload = resultPtr.toDartString();
        return LargeEnumFfiCodec.decode(payload);
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    calloc.free(vNative);
    }
  }

  late final double Function(double v) _takeF32 = _lib.lookupFunction<ffi.Float Function(ffi.Float v), double Function(double v)>('take_f32');

  double takeF32(double v) {
      return _takeF32(v);
  }

  late final double Function(double v) _takeF64 = _lib.lookupFunction<ffi.Double Function(ffi.Double v), double Function(double v)>('take_f64');

  double takeF64(double v) {
      return _takeF64(v);
  }

  late final int Function(int v) _takeI16 = _lib.lookupFunction<ffi.Int16 Function(ffi.Int16 v), int Function(int v)>('take_i16');

  int takeI16(int v) {
      return _takeI16(v);
  }

  late final int Function(int v) _takeI32 = _lib.lookupFunction<ffi.Int32 Function(ffi.Int32 v), int Function(int v)>('take_i32');

  int takeI32(int v) {
      return _takeI32(v);
  }

  late final int Function(int v) _takeI64 = _lib.lookupFunction<ffi.Int64 Function(ffi.Int64 v), int Function(int v)>('take_i64');

  int takeI64(int v) {
      return _takeI64(v);
  }

  late final int Function(int v) _takeI8 = _lib.lookupFunction<ffi.Int8 Function(ffi.Int8 v), int Function(int v)>('take_i8');

  int takeI8(int v) {
      return _takeI8(v);
  }

  late final ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> v) _takeString = _lib.lookupFunction<ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> v), ffi.Pointer<Utf8> Function(ffi.Pointer<Utf8> v)>('take_string');

  String takeString(String v) {
    final ffi.Pointer<Utf8> vNative = v.toNativeUtf8();
    try {
      final ffi.Pointer<Utf8> resultPtr = _takeString(vNative);
      if (resultPtr == ffi.nullptr) {
        throw StateError('Rust returned null for take_string');
      }
      try {
        return resultPtr.toDartString();
      } finally {
        _rustStringFree(resultPtr);
      }
    } finally {
    calloc.free(vNative);
    }
  }

  late final int Function(int v) _takeU16 = _lib.lookupFunction<ffi.Uint16 Function(ffi.Uint16 v), int Function(int v)>('take_u16');

  int takeU16(int v) {
      return _takeU16(v);
  }

  late final int Function(int v) _takeU32 = _lib.lookupFunction<ffi.Uint32 Function(ffi.Uint32 v), int Function(int v)>('take_u32');

  int takeU32(int v) {
      return _takeU32(v);
  }

  late final int Function(int v) _takeU64 = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 v), int Function(int v)>('take_u64');

  int takeU64(int v) {
      return _takeU64(v);
  }

  late final int Function(int v) _takeU8 = _lib.lookupFunction<ffi.Uint8 Function(ffi.Uint8 v), int Function(int v)>('take_u8');

  int takeU8(int v) {
      return _takeU8(v);
  }
}

TypeLimitsDemoFfi? _defaultBindings;

TypeLimitsDemoFfi _bindings() => _defaultBindings ??= TypeLimitsDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = TypeLimitsDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

void maybeThrow(int idx) {
  _bindings().maybeThrow(idx);
}

Uint8List takeBytes(Uint8List v) {
  return _bindings().takeBytes(v);
}

LargeEnum takeEnum(LargeEnum v) {
  return _bindings().takeEnum(v);
}

double takeF32(double v) {
  return _bindings().takeF32(v);
}

double takeF64(double v) {
  return _bindings().takeF64(v);
}

int takeI16(int v) {
  return _bindings().takeI16(v);
}

int takeI32(int v) {
  return _bindings().takeI32(v);
}

int takeI64(int v) {
  return _bindings().takeI64(v);
}

int takeI8(int v) {
  return _bindings().takeI8(v);
}

String takeString(String v) {
  return _bindings().takeString(v);
}

int takeU16(int v) {
  return _bindings().takeU16(v);
}

int takeU32(int v) {
  return _bindings().takeU32(v);
}

int takeU64(int v) {
  return _bindings().takeU64(v);
}

int takeU8(int v) {
  return _bindings().takeU8(v);
}

