// Generated by uniffi-bindgen-dart. DO NOT EDIT.
// ignore_for_file: unused_element, unnecessary_non_null_assertion
library async_object_lift_demo;

import 'dart:async';
import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart';
import 'package:other_bindings/other_bindings.dart';

final class _RustCallStatus extends ffi.Struct {
  @ffi.Int8()
  external int code;

  external ffi.Pointer<Utf8> errorBuf;
}

const int _rustCallStatusSuccess = 0;
const int _rustCallStatusError = 1;
const int _rustCallStatusUnexpectedError = 2;
const int _rustCallStatusCancelled = 3;
const int _rustFuturePollReady = 0;
const int _rustFuturePollWake = 1;

class AsyncObjectLiftDemoFfi {
  AsyncObjectLiftDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_async_object_lift_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();

  late final void Function(ffi.Pointer<Utf8>) _rustStringFree = _lib.lookupFunction<ffi.Void Function(ffi.Pointer<Utf8>), void Function(ffi.Pointer<Utf8>)>('rust_string_free');

  late final int Function(int input) _echoRemoteCounterAsync = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 input), int Function(int input)>('echo_remote_counter_async');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _echoRemoteCounterAsyncRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('rust_future_poll_u64');
  late final void Function(int handle) _echoRemoteCounterAsyncRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_cancel_u64');
  late final int Function(int handle, ffi.Pointer<_RustCallStatus> outStatus) _echoRemoteCounterAsyncRustFutureComplete = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle, ffi.Pointer<_RustCallStatus> outStatus), int Function(int handle, ffi.Pointer<_RustCallStatus> outStatus)>('rust_future_complete_u64');
  late final void Function(int handle) _echoRemoteCounterAsyncRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_free_u64');

  Future<RemoteCounter> echoRemoteCounterAsync(RemoteCounter input) async {
    final int inputHandle = RemoteCounterFfiCodec.lower(input);
    final int futureHandle;
    futureHandle = _echoRemoteCounterAsync(inputHandle);
    final StreamController<int> pollEvents = StreamController<int>.broadcast();
    final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
      pollEvents.add(pollResult);
    });
    try {
      _echoRemoteCounterAsyncRustFuturePoll(futureHandle, callback.nativeFunction, 0);
      while (true) {
        final int pollResult = await pollEvents.stream.first;
        if (pollResult == _rustFuturePollReady) {
          break;
        }
        if (pollResult == _rustFuturePollWake) {
          _echoRemoteCounterAsyncRustFuturePoll(futureHandle, callback.nativeFunction, 0);
          continue;
        }
        throw StateError('Rust future poll returned invalid status for echo_remote_counter_async: $pollResult');
      }
      final ffi.Pointer<_RustCallStatus> outStatusPtr = calloc<_RustCallStatus>();
      try {
        final int resultValue = _echoRemoteCounterAsyncRustFutureComplete(futureHandle, outStatusPtr);
        final int statusCode = outStatusPtr.ref.code;
        if (statusCode == _rustCallStatusSuccess) {
          return RemoteCounterFfiCodec.lift(resultValue);
        }
        if (statusCode == _rustCallStatusCancelled) {
          throw StateError('Rust future was cancelled for echo_remote_counter_async');
        }
        final ffi.Pointer<Utf8> errorPtr = outStatusPtr.ref.errorBuf;
        if (errorPtr != ffi.nullptr) {
          try {
            throw StateError(errorPtr.toDartString());
          } finally {
            _rustStringFree(errorPtr);
          }
        }
        throw StateError('Rust future failed for echo_remote_counter_async with status code: $statusCode');
      } finally {
        calloc.free(outStatusPtr);
      }
    } catch (_) {
      _echoRemoteCounterAsyncRustFutureCancel(futureHandle);
      rethrow;
    } finally {
      await pollEvents.close();
      callback.close();
      _echoRemoteCounterAsyncRustFutureFree(futureHandle);
    }
  }

  late final void Function(int handle) _counterFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('counter_free');

  late final int Function(int initial) _counterCtorNew = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint32 initial), int Function(int initial)>('counter_new');

  Counter counterCreateNew(int initial) {
    final int handle = _counterCtorNew(initial);
    return Counter._(this, handle);
  }

  late final int Function(int handle) _counterSpawnNext = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle), int Function(int handle)>('counter_spawn_next');
  late final void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData) _counterSpawnNextRustFuturePoll = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, ffi.Uint64 callbackData), void Function(int handle, ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Uint64 callbackData, ffi.Int8 pollResult)>> callback, int callbackData)>('rust_future_poll_u64');
  late final void Function(int handle) _counterSpawnNextRustFutureCancel = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_cancel_u64');
  late final int Function(int handle, ffi.Pointer<_RustCallStatus> outStatus) _counterSpawnNextRustFutureComplete = _lib.lookupFunction<ffi.Uint64 Function(ffi.Uint64 handle, ffi.Pointer<_RustCallStatus> outStatus), int Function(int handle, ffi.Pointer<_RustCallStatus> outStatus)>('rust_future_complete_u64');
  late final void Function(int handle) _counterSpawnNextRustFutureFree = _lib.lookupFunction<ffi.Void Function(ffi.Uint64 handle), void Function(int handle)>('rust_future_free_u64');

  Future<Counter> counterInvokeSpawnNext(int handle) async {
    final int futureHandle;
    futureHandle = _counterSpawnNext(handle);
    final StreamController<int> pollEvents = StreamController<int>.broadcast();
    final callback = ffi.NativeCallable<ffi.Void Function(ffi.Uint64, ffi.Int8)>.listener((int _, int pollResult) {
      pollEvents.add(pollResult);
    });
    try {
      _counterSpawnNextRustFuturePoll(futureHandle, callback.nativeFunction, 0);
      while (true) {
        final int pollResult = await pollEvents.stream.first;
        if (pollResult == _rustFuturePollReady) {
          break;
        }
        if (pollResult == _rustFuturePollWake) {
          _counterSpawnNextRustFuturePoll(futureHandle, callback.nativeFunction, 0);
          continue;
        }
        throw StateError('Rust future poll returned invalid status for counter_spawn_next: $pollResult');
      }
      final ffi.Pointer<_RustCallStatus> outStatusPtr = calloc<_RustCallStatus>();
      try {
        final int resultValue = _counterSpawnNextRustFutureComplete(futureHandle, outStatusPtr);
        final int statusCode = outStatusPtr.ref.code;
        if (statusCode == _rustCallStatusSuccess) {
          return resultValue;
        }
        if (statusCode == _rustCallStatusCancelled) {
          throw StateError('Rust future was cancelled for counter_spawn_next');
        }
        final ffi.Pointer<Utf8> errorPtr = outStatusPtr.ref.errorBuf;
        if (errorPtr != ffi.nullptr) {
          try {
            throw StateError(errorPtr.toDartString());
          } finally {
            _rustStringFree(errorPtr);
          }
        }
        throw StateError('Rust future failed for counter_spawn_next with status code: $statusCode');
      } finally {
        calloc.free(outStatusPtr);
      }
    } catch (_) {
      _counterSpawnNextRustFutureCancel(futureHandle);
      rethrow;
    } finally {
      await pollEvents.close();
      callback.close();
      _counterSpawnNextRustFutureFree(futureHandle);
    }
  }
}

final class _CounterFinalizerToken {
  const _CounterFinalizerToken(this.free, this.handle);
  final void Function(int) free;
  final int handle;
}

final class Counter {
  Counter._(this._ffi, this._handle) {
    _finalizer.attach(this, _CounterFinalizerToken(_ffi._counterFree, _handle), detach: this);
  }

  final AsyncObjectLiftDemoFfi _ffi;
  int _handle;
  bool _closed = false;

  static final Finalizer<_CounterFinalizerToken> _finalizer = Finalizer((token) {
    token.free(token.handle);
  });

  bool get isClosed => _closed;

  void close() {
    if (_closed) {
      return;
    }
    _closed = true;
    _finalizer.detach(this);
    _ffi._counterFree(_handle);
  }

  void _ensureOpen() {
    if (_closed) {
      throw StateError('Counter is closed');
    }
  }

  static Counter create(int initial) {
    return _bindings().counterCreateNew(initial);
  }

  Future<Counter> spawnNext() {
    _ensureOpen();
    return _ffi.counterInvokeSpawnNext(_handle);
  }

}

final class CounterFfiCodec {
  const CounterFfiCodec._();

  static int lower(Counter value) => value._handle;

  static Counter lift(int handle) => Counter._(_bindings(), handle);
}

AsyncObjectLiftDemoFfi? _defaultBindings;

AsyncObjectLiftDemoFfi _bindings() => _defaultBindings ??= AsyncObjectLiftDemoFfi();

void configureDefaultBindings({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath}) {
  _defaultBindings = AsyncObjectLiftDemoFfi(dynamicLibrary: dynamicLibrary, libraryPath: libraryPath);
}

void resetDefaultBindings() {
  _defaultBindings = null;
}

Future<RemoteCounter> echoRemoteCounterAsync(RemoteCounter input) {
  return _bindings().echoRemoteCounterAsync(input);
}

