// Generated by uniffi-bindgen-dart. DO NOT EDIT.
library model_types_demo;

import 'dart:convert';
import 'dart:ffi' as ffi;

class Person {
  const Person({
    required this.name,
    required this.age,
    required this.nickname,
  });

  final String name;
  final int age;
  final String? nickname;

  Map<String, dynamic> toJson() {
    return {
      'name': this.name,
      'age': this.age,
      'nickname': this.nickname == null ? null : (() { final value = this.nickname; return value; })(),
    };
  }

  static Person fromJson(Map<String, dynamic> json) {
    return Person(
      name: json['name'] as String,
      age: (json['age'] as num).toInt(),
      nickname: json['nickname'] == null ? null : (() { final value = json['nickname']; return value as String; })(),
    );
  }

  Person copyWith({
    String? name,
    int? age,
    String? nickname,
  }) {
    return Person(
      name: name ?? this.name,
      age: age ?? this.age,
      nickname: nickname ?? this.nickname,
    );
  }
}

enum Color {
  red,
  green,
  blue,
}

sealed class Outcome {
  const Outcome();
}

final class OutcomeSuccess extends Outcome {
  const OutcomeSuccess({
    required this.message,
  });
  final String message;
}

final class OutcomeFailure extends Outcome {
  const OutcomeFailure({
    required this.code,
    required this.reason,
  });
  final int code;
  final String reason;
}

String _encodeColor(Color value) {
  return switch (value) {
    Color.red => 'red',
    Color.green => 'green',
    Color.blue => 'blue',
  };
}

Color _decodeColor(String raw) {
  switch (raw) {
    case 'red':
      return Color.red;
    case 'green':
      return Color.green;
    case 'blue':
      return Color.blue;
    default:
      throw StateError('Unknown Color variant: $raw');
  }
}

class ModelTypesDemoFfi {
  ModelTypesDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_model_types_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();
}
