// Generated by uniffi-bindgen-dart. DO NOT EDIT.
library model_types_demo;

import 'dart:ffi' as ffi;

class Person {
  const Person({
    required this.name,
    required this.age,
    required this.nickname,
  });

  final String name;
  final int age;
  final String? nickname;

  Person copyWith({
    String? name,
    int? age,
    String? nickname,
  }) {
    return Person(
      name: name ?? this.name,
      age: age ?? this.age,
      nickname: nickname ?? this.nickname,
    );
  }
}

enum Color {
  red,
  green,
  blue,
}

sealed class Outcome {
  const Outcome();
}

final class OutcomeSuccess extends Outcome {
  const OutcomeSuccess({
    required this.message,
  });
  final String message;
}

final class OutcomeFailure extends Outcome {
  const OutcomeFailure({
    required this.code,
    required this.reason,
  });
  final int code;
  final String reason;
}

class ModelTypesDemoFfi {
  ModelTypesDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_model_types_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();
}
