// Generated by uniffi-bindgen-dart. DO NOT EDIT.
library compound_demo;

import 'dart:ffi' as ffi;
import 'dart:typed_data';

class CompoundDemoFfi {
  const CompoundDemoFfi();

  static const String libraryName = 'uniffi_compound_demo';

  ffi.DynamicLibrary open() {
    return ffi.DynamicLibrary.open(libraryName);
  }
}

List<Uint8List> chunk(List<Uint8List> input) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

Map<String, int> counts(Map<String, int> items) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

List<int> listify(List<int> values) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

String? maybeName(String? value) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

