// Generated by uniffi-bindgen-dart. DO NOT EDIT.
library compound_demo;

import 'dart:ffi' as ffi;
import 'dart:typed_data';

class CompoundDemoFfi {
  CompoundDemoFfi({ffi.DynamicLibrary? dynamicLibrary, String? libraryPath})
      : _dynamicLibrary = dynamicLibrary,
        _libraryPath = libraryPath;

  final ffi.DynamicLibrary? _dynamicLibrary;
  final String? _libraryPath;

  static const String libraryName = 'uniffi_compound_demo';

  ffi.DynamicLibrary open() {
    final provided = _dynamicLibrary;
    if (provided != null) {
      return provided;
    }
    return ffi.DynamicLibrary.open(_libraryPath ?? libraryName);
  }

  late final ffi.DynamicLibrary _lib = open();
}

List<Uint8List> chunk(List<Uint8List> input) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

Map<String, int> counts(Map<String, int> items) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

List<int> listify(List<int> values) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

String? maybeName(String? value) {
  throw UnimplementedError('TODO: bind to Rust FFI');
}

