name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test workspace
        run: cargo test --workspace
      - name: Generate bindings artifacts
        run: ./scripts/build_bindings.sh
      - name: Upload generated bindings artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-bindings
          path: binding_tests/generated

  test-bindings:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Download generated bindings artifact
        uses: actions/download-artifact@v4
        with:
          name: generated-bindings
          path: binding_tests/generated
      - name: Dart tests
        run: |
          cd binding_tests
          dart pub get
          dart analyze
          dart test
